// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' | 'Phone Open' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "../chunks/chunk-4UZRJMMT.js";
import { stdin_default2 as stdin_default3 } from "../chunks/chunk-BZHV5ZRO.js";
import { stdin_default } from "../chunks/chunk-YY62L3WU.js";
import "../chunks/chunk-VU34HTVO.js";
import "../chunks/chunk-MM5BHUY4.js";
import "../chunks/chunk-NULYBL27.js";
import { routes } from "../chunks/chunk-6YUVG4ZJ.js";

// virtual:navigation/navigation-bar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qnzBrEwFiUcP2ORWQfgv/YlskXTsa53JBW2jbMemk/t4OAPb8Bp.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS as withCSS3,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/OHAeXRVuIuIhNnwnuAwt/TPQajJk793opWxAlkyhw/mGRcFilE4.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ezTt3ayMo: fill ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { style, className, layoutId, variant, ezTt3ayMo, ...restProps } =
		getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-5tOwe", className)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--21h8s6": ezTt3ayMo,
				...style,
			}}
		/>
	);
});
var css = [
	`.framer-5tOwe { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url('data:image/svg+xml,<svg aria-label="Plus" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 18 9 C 18 9.414 17.664 9.75 17.25 9.75 L 9.75 9.75 L 9.75 17.25 C 9.75 17.664 9.414 18 9 18 C 8.586 18 8.25 17.664 8.25 17.25 L 8.25 9.75 L 0.75 9.75 C 0.336 9.75 0 9.414 0 9 C 0 8.586 0.336 8.25 0.75 8.25 L 8.25 8.25 L 8.25 0.75 C 8.25 0.336 8.586 0 9 0 C 9.414 0 9.75 0.336 9.75 0.75 L 9.75 8.25 L 17.25 8.25 C 17.664 8.25 18 8.586 18 9 Z" fill="var(--21h8s6, rgb(0,0,0))" height="18px" id="dCW9rfinU" opacity="1" transform="translate(3 3)" width="18px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon = withCSS(Component, css, "framer-5tOwe");
var stdin_default4 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType.Color,
	},
});

// /:https://framerusercontent.com/modules/s2R6EA5wxsJaZK7qI6h6/WaXv1vcAsmGEE0ELmQpv/DuMVcrStb.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion2.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps2 = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ezTt3ayMo: fill ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { style, className, layoutId, variant, ezTt3ayMo, ...restProps } =
		getProps2(props);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-mi20F", className)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--21h8s6": ezTt3ayMo,
				...style,
			}}
		/>
	);
});
var css2 = [
	`.framer-mi20F { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url('data:image/svg+xml,<svg aria-label="List Dashes" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 5.25 0.75 C 5.25 0.336 5.586 0 6 0 L 17.25 0 C 17.664 0 18 0.336 18 0.75 C 18 1.164 17.664 1.5 17.25 1.5 L 6 1.5 C 5.586 1.5 5.25 1.164 5.25 0.75 Z M 17.25 6 L 6 6 C 5.586 6 5.25 6.336 5.25 6.75 C 5.25 7.164 5.586 7.5 6 7.5 L 17.25 7.5 C 17.664 7.5 18 7.164 18 6.75 C 18 6.336 17.664 6 17.25 6 Z M 17.25 12 L 6 12 C 5.586 12 5.25 12.336 5.25 12.75 C 5.25 13.164 5.586 13.5 6 13.5 L 17.25 13.5 C 17.664 13.5 18 13.164 18 12.75 C 18 12.336 17.664 12 17.25 12 Z M 2.25 0 L 0.75 0 C 0.336 0 0 0.336 0 0.75 C 0 1.164 0.336 1.5 0.75 1.5 L 2.25 1.5 C 2.664 1.5 3 1.164 3 0.75 C 3 0.336 2.664 0 2.25 0 Z M 2.25 6 L 0.75 6 C 0.336 6 0 6.336 0 6.75 C 0 7.164 0.336 7.5 0.75 7.5 L 2.25 7.5 C 2.664 7.5 3 7.164 3 6.75 C 3 6.336 2.664 6 2.25 6 Z M 2.25 12 L 0.75 12 C 0.336 12 0 12.336 0 12.75 C 0 13.164 0.336 13.5 0.75 13.5 L 2.25 13.5 C 2.664 13.5 3 13.164 3 12.75 C 3 12.336 2.664 12 2.25 12 Z" fill="var(--21h8s6, rgb(0,0,0))" height="13.5px" id="RzKWvkHCV" opacity="1" transform="translate(3 5.25)" width="18px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css2, "framer-mi20F");
var stdin_default5 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType2.Color,
	},
});

// /:https://framerusercontent.com/modules/qnzBrEwFiUcP2ORWQfgv/YlskXTsa53JBW2jbMemk/t4OAPb8Bp.js
var LogoFonts = getFonts(stdin_default3);
var IconFonts = getFonts(stdin_default5);
var Icon1Fonts = getFonts(stdin_default4);
var LinkFonts = getFonts(stdin_default2);
var ButtonButtonFonts = getFonts(stdin_default);
var cycleOrder = ["iYCxTGtVM", "BSWPs3H_g", "y7ork0Jbc"];
var serializationHash = "framer-H2m1B";
var variantClassNames = {
	BSWPs3H_g: "framer-v-mo7pm4",
	iYCxTGtVM: "framer-v-1fl0sgc",
	y7ork0Jbc: "framer-v-1p3qe8f",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition2 = {
	duration: 0,
	type: "tween",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var transition3 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 600,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion3.create(React3.Fragment);
var humanReadableVariantMap = {
	"Phone Open": "y7ork0Jbc",
	Desktop: "iYCxTGtVM",
	Phone: "BSWPs3H_g",
};
var getProps3 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "iYCxTGtVM",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } =
		getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "iYCxTGtVM",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1cxnk96 = activeVariantCallback(async (...args) => {
		setVariant("y7ork0Jbc");
	});
	const onTap7slb3l = activeVariantCallback(async (...args) => {
		setVariant("BSWPs3H_g");
	});
	const QLgiJ9IsJ146usl5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("BSWPs3H_g"), 100);
	});
	const QLgiJ9IsJ7slb3l = activeVariantCallback(async (...args) => {
		setVariant("BSWPs3H_g");
	});
	const rBh3iGJA57slb3l = activeVariantCallback(async (...args) => {
		setVariant("BSWPs3H_g");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["BSWPs3H_g", "y7ork0Jbc"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "BSWPs3H_g") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "y7ork0Jbc") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "BSWPs3H_g") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							BSWPs3H_g: {
								value: transition2,
							},
							y7ork0Jbc: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion3.nav
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-1fl0sgc",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						data-hide-scrollbars={true}
						layoutDependency={layoutDependency}
						layoutId={"iYCxTGtVM"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(230, 230, 230))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "dashed",
							"--border-top-width": "1px",
							backdropFilter: "blur(45px)",
							backgroundColor:
								"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
							WebkitBackdropFilter: "blur(45px)",
							...style,
						}}
						variants={{
							BSWPs3H_g: {
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
							y7ork0Jbc: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
						}}
						{...addPropertyOverrides(
							{
								BSWPs3H_g: {
									"data-framer-name": "Phone",
								},
								y7ork0Jbc: {
									"data-framer-name": "Phone Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-18u4ozg"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"clCAJrXfP"}
						>
							<motion3.div
								className={"framer-khsa7b"}
								data-framer-name={"Name"}
								layoutDependency={layoutDependency}
								layoutId={"hcMjjb37N"}
							>
								<motion3.div
									className={"framer-1hgsjoy"}
									data-framer-name={"Logo Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"mOfJl_EO_"}
								>
									<ComponentViewportProvider
										height={40}
										y={
											(componentViewport?.y || 0) +
											10 +
											(0 +
												0 +
												(((componentViewport?.height || 75) - 20 - 55) / 1) *
													0) +
											7.5 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												BSWPs3H_g: {
													y: (componentViewport?.y || 0) + 0 + 0 + 0 + 12 + 0,
												},
												y7ork0Jbc: {
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														0 +
														0 +
														12 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-mubbsx-container"}
											layoutDependency={layoutDependency}
											layoutId={"OYQgz23sU-container"}
											nodeId={"OYQgz23sU"}
											rendersWithMotion={true}
											scopeId={"t4OAPb8Bp"}
										>
											{_jsx3(stdin_default3, {
												height: "100%",
												id: "OYQgz23sU",
												layoutId: "OYQgz23sU",
												variant: "oqpkr_RIF",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion3.div>
								{isDisplayed() && (
									<motion3.div
										className={"framer-1i2qaio"}
										data-framer-name={"Hamburger"}
										layoutDependency={layoutDependency}
										layoutId={"S_oG_CnpE"}
										style={{
											"--border-bottom-width": "0px",
											"--border-color": "rgba(0, 0, 0, 0)",
											"--border-left-width": "0px",
											"--border-right-width": "0px",
											"--border-style": "solid",
											"--border-top-width": "0px",
											backgroundColor: "rgba(0, 0, 0, 0)",
											borderBottomLeftRadius: 0,
											borderBottomRightRadius: 0,
											borderTopLeftRadius: 0,
											borderTopRightRadius: 0,
											boxShadow:
												"0px 1.3436836425447838px 0.5374734570179134px -0.625px rgba(0, 0, 0, 0.09), 0px 3.184767494094558px 1.273906997637823px -1.25px rgba(0, 0, 0, 0.09), 0px 5.80934510345105px 2.3237380413804196px -1.875px rgba(0, 0, 0, 0.08), 0px 9.658024572418071px 3.8632098289672276px -2.5px rgba(0, 0, 0, 0.08), 0px 15.596922177565284px 6.238768871026112px -3.125px rgba(0, 0, 0, 0.07), 0px 25.530614085937845px 10.212245634375137px -3.75px rgba(0, 0, 0, 0.06), 0px 43.96199341069441px 17.58479736427776px -4.375px rgba(0, 0, 0, 0.04), 0px 80px 31.999999999999993px -5px rgba(0, 0, 0, 0)",
										}}
										variants={{
											BSWPs3H_g: {
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-b7e61bf6-93c6-45ca-b0e7-ce895d683d69, rgba(0, 0, 0, 0.4))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor:
													"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 10,
												boxShadow:
													"0px 1.3436836425447838px 1.3436836425447838px -0.625px rgba(0, 0, 0, 0.09), 0px 3.184767494094558px 3.184767494094558px -1.25px rgba(0, 0, 0, 0.09), 0px 5.80934510345105px 5.80934510345105px -1.875px rgba(0, 0, 0, 0.08), 0px 9.658024572418071px 9.658024572418071px -2.5px rgba(0, 0, 0, 0.08), 0px 15.596922177565284px 15.596922177565284px -3.125px rgba(0, 0, 0, 0.07), 0px 25.530614085937845px 25.530614085937845px -3.75px rgba(0, 0, 0, 0.06), 0px 43.96199341069441px 43.96199341069441px -4.375px rgba(0, 0, 0, 0.04), 0px 80px 80px -5px rgba(0, 0, 0, 0)",
											},
											y7ork0Jbc: {
												"--border-bottom-width": "0px",
												"--border-left-width": "0px",
												"--border-right-width": "0px",
												"--border-top-width": "0px",
												backgroundColor:
													"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
												borderBottomLeftRadius: 10,
												borderBottomRightRadius: 10,
												borderTopLeftRadius: 10,
												borderTopRightRadius: 10,
												boxShadow:
													"0px 1.3436836425447838px 1.3436836425447838px -0.625px rgba(0, 0, 0, 0.09), 0px 3.184767494094558px 3.184767494094558px -1.25px rgba(0, 0, 0, 0.09), 0px 5.80934510345105px 5.80934510345105px -1.875px rgba(0, 0, 0, 0.08), 0px 9.658024572418071px 9.658024572418071px -2.5px rgba(0, 0, 0, 0.08), 0px 15.596922177565284px 15.596922177565284px -3.125px rgba(0, 0, 0, 0.07), 0px 25.530614085937845px 25.530614085937845px -3.75px rgba(0, 0, 0, 0.06), 0px 43.96199341069441px 43.96199341069441px -4.375px rgba(0, 0, 0, 0.04), 0px 80px 80px -5px rgba(0, 0, 0, 0)",
											},
										}}
										{...addPropertyOverrides(
											{
												BSWPs3H_g: {
													"data-border": true,
													"data-highlight": true,
													onTap: onTap1cxnk96,
												},
												y7ork0Jbc: {
													"data-highlight": true,
													onTap: onTap7slb3l,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{isDisplayed1() &&
											_jsx3(stdin_default5, {
												animated: true,
												className: "framer-1ff6aj9",
												layoutDependency,
												layoutId: "GtqWaOJ7M",
												style: {
													"--21h8s6":
														"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
												},
											})}
										{isDisplayed2() &&
											_jsx3(stdin_default4, {
												animated: true,
												className: "framer-8u6qs4",
												layoutDependency,
												layoutId: "Y4aesxlyz",
												style: {
													"--21h8s6":
														"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
													rotate: 45,
												},
												transformTemplate: transformTemplate1,
												...addPropertyOverrides(
													{
														y7ork0Jbc: {
															transformTemplate: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
									</motion3.div>
								)}
							</motion3.div>
							{isDisplayed3() && (
								<Transition
									{...addPropertyOverrides(
										{
											y7ork0Jbc: {
												value: transition3,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion3.div
										className={"framer-1yfdksk"}
										data-framer-name={"Links"}
										layoutDependency={layoutDependency}
										layoutId={"hTicR3lGj"}
									>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":q7jn9iT4k",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":q7jn9iT4k",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													height={30}
													y={
														(componentViewport?.y || 0) +
														10 +
														(0 +
															0 +
															(((componentViewport?.height || 75) - 20 - 55) /
																1) *
																0) +
														6.5 +
														6
													}
													{...addPropertyOverrides(
														{
															y7ork0Jbc: {
																height: 50,
																y:
																	(componentViewport?.y || 0) +
																	0 +
																	0 +
																	0 +
																	84 +
																	0 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-416di-container"}
														layoutDependency={layoutDependency}
														layoutId={"Wk6DB0kpN-container"}
														nodeId={"Wk6DB0kpN"}
														rendersWithMotion={true}
														scopeId={"t4OAPb8Bp"}
													>
														{_jsx3(stdin_default2, {
															height: "100%",
															id: "Wk6DB0kpN",
															layoutId: "Wk6DB0kpN",
															vr3GalQZm: "Services",
															width: "100%",
															x7kSahbL4: resolvedLinks[0],
															...addPropertyOverrides(
																{
																	y7ork0Jbc: {
																		QLgiJ9IsJ: QLgiJ9IsJ146usl5,
																		style: {
																			height: "100%",
																		},
																		x7kSahbL4: resolvedLinks[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":ianedYltk",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":ianedYltk",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks1) => (
												<ComponentViewportProvider
													height={30}
													y={
														(componentViewport?.y || 0) +
														10 +
														(0 +
															0 +
															(((componentViewport?.height || 75) - 20 - 55) /
																1) *
																0) +
														6.5 +
														6
													}
													{...addPropertyOverrides(
														{
															y7ork0Jbc: {
																height: 50,
																y:
																	(componentViewport?.y || 0) +
																	0 +
																	0 +
																	0 +
																	84 +
																	0 +
																	100,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-mcxpb4-container"}
														layoutDependency={layoutDependency}
														layoutId={"OMVlZP1MB-container"}
														nodeId={"OMVlZP1MB"}
														rendersWithMotion={true}
														scopeId={"t4OAPb8Bp"}
													>
														{_jsx3(stdin_default2, {
															height: "100%",
															id: "OMVlZP1MB",
															layoutId: "OMVlZP1MB",
															vr3GalQZm: "Process",
															width: "100%",
															x7kSahbL4: resolvedLinks1[0],
															...addPropertyOverrides(
																{
																	y7ork0Jbc: {
																		QLgiJ9IsJ: QLgiJ9IsJ7slb3l,
																		style: {
																			height: "100%",
																		},
																		x7kSahbL4: resolvedLinks1[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "ONaKvcShR",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "ONaKvcShR",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks2) => (
												<ComponentViewportProvider
													height={30}
													y={
														(componentViewport?.y || 0) +
														10 +
														(0 +
															0 +
															(((componentViewport?.height || 75) - 20 - 55) /
																1) *
																0) +
														6.5 +
														6
													}
													{...addPropertyOverrides(
														{
															y7ork0Jbc: {
																height: 50,
																y:
																	(componentViewport?.y || 0) +
																	0 +
																	0 +
																	0 +
																	84 +
																	0 +
																	50,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-ubp8oh-container"}
														layoutDependency={layoutDependency}
														layoutId={"Dj3JMr5D2-container"}
														nodeId={"Dj3JMr5D2"}
														rendersWithMotion={true}
														scopeId={"t4OAPb8Bp"}
													>
														{_jsx3(stdin_default2, {
															height: "100%",
															id: "Dj3JMr5D2",
															layoutId: "Dj3JMr5D2",
															vr3GalQZm: "Works",
															width: "100%",
															x7kSahbL4: resolvedLinks2[0],
															...addPropertyOverrides(
																{
																	y7ork0Jbc: {
																		QLgiJ9IsJ: QLgiJ9IsJ7slb3l,
																		style: {
																			height: "100%",
																		},
																		x7kSahbL4: resolvedLinks2[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":SE_HGs4kj",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":SE_HGs4kj",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks3) => (
												<ComponentViewportProvider
													height={30}
													y={
														(componentViewport?.y || 0) +
														10 +
														(0 +
															0 +
															(((componentViewport?.height || 75) - 20 - 55) /
																1) *
																0) +
														6.5 +
														6
													}
													{...addPropertyOverrides(
														{
															y7ork0Jbc: {
																height: 50,
																y:
																	(componentViewport?.y || 0) +
																	0 +
																	0 +
																	0 +
																	84 +
																	0 +
																	300,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-19xmimc-container"}
														layoutDependency={layoutDependency}
														layoutId={"WULVK5MOO-container"}
														nodeId={"WULVK5MOO"}
														rendersWithMotion={true}
														scopeId={"t4OAPb8Bp"}
													>
														{_jsx3(stdin_default2, {
															height: "100%",
															id: "WULVK5MOO",
															layoutId: "WULVK5MOO",
															vr3GalQZm: "Pricing",
															width: "100%",
															x7kSahbL4: resolvedLinks3[0],
															...addPropertyOverrides(
																{
																	y7ork0Jbc: {
																		QLgiJ9IsJ: QLgiJ9IsJ7slb3l,
																		style: {
																			height: "100%",
																		},
																		x7kSahbL4: resolvedLinks3[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":CRnkfwqXz",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":CRnkfwqXz",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks4) => (
												<ComponentViewportProvider
													height={30}
													y={
														(componentViewport?.y || 0) +
														10 +
														(0 +
															0 +
															(((componentViewport?.height || 75) - 20 - 55) /
																1) *
																0) +
														6.5 +
														6
													}
													{...addPropertyOverrides(
														{
															y7ork0Jbc: {
																height: 50,
																y:
																	(componentViewport?.y || 0) +
																	0 +
																	0 +
																	0 +
																	84 +
																	0 +
																	150,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-54zb69-container"}
														layoutDependency={layoutDependency}
														layoutId={"bHadRFW5R-container"}
														nodeId={"bHadRFW5R"}
														rendersWithMotion={true}
														scopeId={"t4OAPb8Bp"}
													>
														{_jsx3(stdin_default2, {
															height: "100%",
															id: "bHadRFW5R",
															layoutId: "bHadRFW5R",
															vr3GalQZm: "Reviews",
															width: "100%",
															x7kSahbL4: resolvedLinks4[0],
															...addPropertyOverrides(
																{
																	y7ork0Jbc: {
																		QLgiJ9IsJ: QLgiJ9IsJ7slb3l,
																		style: {
																			height: "100%",
																		},
																		x7kSahbL4: resolvedLinks4[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":OLPFkzjAU",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":OLPFkzjAU",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks5) => (
												<ComponentViewportProvider
													height={30}
													y={
														(componentViewport?.y || 0) +
														10 +
														(0 +
															0 +
															(((componentViewport?.height || 75) - 20 - 55) /
																1) *
																0) +
														6.5 +
														6
													}
													{...addPropertyOverrides(
														{
															y7ork0Jbc: {
																height: 50,
																y:
																	(componentViewport?.y || 0) +
																	0 +
																	0 +
																	0 +
																	84 +
																	0 +
																	200,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-1wquugj-container"}
														layoutDependency={layoutDependency}
														layoutId={"oM1FqQUiC-container"}
														nodeId={"oM1FqQUiC"}
														rendersWithMotion={true}
														scopeId={"t4OAPb8Bp"}
													>
														{_jsx3(stdin_default2, {
															height: "100%",
															id: "oM1FqQUiC",
															layoutId: "oM1FqQUiC",
															vr3GalQZm: "FAQ",
															width: "100%",
															x7kSahbL4: resolvedLinks5[0],
															...addPropertyOverrides(
																{
																	y7ork0Jbc: {
																		QLgiJ9IsJ: QLgiJ9IsJ7slb3l,
																		style: {
																			height: "100%",
																		},
																		x7kSahbL4: resolvedLinks5[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "e3oVeWGzu",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "e3oVeWGzu",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks6) => (
												<ComponentViewportProvider
													height={30}
													y={
														(componentViewport?.y || 0) +
														10 +
														(0 +
															0 +
															(((componentViewport?.height || 75) - 20 - 55) /
																1) *
																0) +
														6.5 +
														6
													}
													{...addPropertyOverrides(
														{
															y7ork0Jbc: {
																height: 50,
																y:
																	(componentViewport?.y || 0) +
																	0 +
																	0 +
																	0 +
																	84 +
																	0 +
																	250,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-orn40b-container"}
														layoutDependency={layoutDependency}
														layoutId={"lmcMX3EK5-container"}
														nodeId={"lmcMX3EK5"}
														rendersWithMotion={true}
														scopeId={"t4OAPb8Bp"}
													>
														{_jsx3(stdin_default2, {
															height: "100%",
															id: "lmcMX3EK5",
															layoutId: "lmcMX3EK5",
															vr3GalQZm: "Blog",
															width: "100%",
															x7kSahbL4: resolvedLinks6[0],
															...addPropertyOverrides(
																{
																	y7ork0Jbc: {
																		QLgiJ9IsJ: QLgiJ9IsJ7slb3l,
																		style: {
																			height: "100%",
																		},
																		x7kSahbL4: resolvedLinks6[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion3.div>
								</Transition>
							)}
							{isDisplayed3() && (
								<motion3.div
									className={"framer-1dofrp2"}
									data-framer-name={"Button Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"Ie5sMAhzt"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "FrIewJr2E",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "FrIewJr2E",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks7) => (
											<ComponentViewportProvider
												height={55}
												width={"140px"}
												y={
													(componentViewport?.y || 0) +
													10 +
													(0 +
														0 +
														(((componentViewport?.height || 75) - 20 - 55) /
															1) *
															0) +
													0 +
													0
												}
												{...addPropertyOverrides(
													{
														y7ork0Jbc: {
															y:
																(componentViewport?.y || 0) +
																0 +
																0 +
																0 +
																454 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-etrl9i-container"}
													layoutDependency={layoutDependency}
													layoutId={"VnnsKbdwX-container"}
													nodeId={"VnnsKbdwX"}
													rendersWithMotion={true}
													scopeId={"t4OAPb8Bp"}
												>
													{_jsx3(stdin_default, {
														height: "100%",
														id: "VnnsKbdwX",
														layoutId: "VnnsKbdwX",
														QPXgBsk7h: "Contact",
														style: {
															height: "100%",
															maxHeight: "100%",
															width: "100%",
														},
														T5oKm0XoU: resolvedLinks7[0],
														variant: "JLDUHK2uy",
														width: "100%",
														...addPropertyOverrides(
															{
																y7ork0Jbc: {
																	rBh3iGJA5: rBh3iGJA57slb3l,
																	T5oKm0XoU: resolvedLinks7[1],
																	variant: "xUewAf79X",
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</motion3.div>
							)}
						</motion3.div>
					</motion3.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-H2m1B.framer-1makegv, .framer-H2m1B .framer-1makegv { display: block; }",
	".framer-H2m1B.framer-1fl0sgc { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 10px 40px 10px 40px; position: relative; width: 1200px; }",
	".framer-H2m1B .framer-18u4ozg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-H2m1B .framer-khsa7b { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-H2m1B .framer-1hgsjoy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-H2m1B .framer-mubbsx-container, .framer-H2m1B .framer-416di-container, .framer-H2m1B .framer-mcxpb4-container, .framer-H2m1B .framer-ubp8oh-container, .framer-H2m1B .framer-19xmimc-container, .framer-H2m1B .framer-54zb69-container, .framer-H2m1B .framer-1wquugj-container, .framer-H2m1B .framer-orn40b-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-H2m1B .framer-1i2qaio { flex: none; height: 40px; overflow: hidden; position: relative; width: 40px; }",
	".framer-H2m1B .framer-1ff6aj9 { flex: none; height: var(--framer-aspect-ratio-supported, 24px); left: 13px; position: absolute; top: -3px; width: 24px; z-index: 3; }",
	".framer-H2m1B .framer-8u6qs4 { flex: none; height: var(--framer-aspect-ratio-supported, 24px); left: 50%; position: absolute; top: 50%; width: 24px; }",
	".framer-H2m1B .framer-1yfdksk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 6px; position: relative; width: min-content; }",
	".framer-H2m1B .framer-1dofrp2 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-H2m1B .framer-etrl9i-container { flex: none; height: 55px; max-height: 55px; position: relative; width: 140px; }",
	".framer-H2m1B.framer-v-mo7pm4.framer-1fl0sgc { gap: 0px; justify-content: flex-start; padding: 0px; width: 390px; }",
	".framer-H2m1B.framer-v-mo7pm4 .framer-18u4ozg, .framer-H2m1B.framer-v-mo7pm4 .framer-1hgsjoy, .framer-H2m1B.framer-v-1p3qe8f .framer-1hgsjoy { order: 0; }",
	".framer-H2m1B.framer-v-mo7pm4 .framer-khsa7b { gap: unset; height: 64px; justify-content: space-between; padding: 0px 12px 0px 20px; z-index: 2; }",
	".framer-H2m1B.framer-v-mo7pm4 .framer-1i2qaio { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: center; order: 1; padding: 0px; width: 44px; will-change: var(--framer-will-change-override, transform); }",
	".framer-H2m1B.framer-v-mo7pm4 .framer-1ff6aj9 { left: unset; order: 0; position: relative; top: unset; }",
	".framer-H2m1B.framer-v-1p3qe8f.framer-1fl0sgc { gap: 37px; justify-content: flex-start; max-height: calc(var(--framer-viewport-height, 100vh) * 1); overflow: auto; overscroll-behavior: contain; padding: 0px 0px 30px 0px; width: 390px; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-18u4ozg { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 20px; justify-content: flex-start; order: 0; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-khsa7b { flex: none; gap: unset; height: 64px; justify-content: space-between; padding: 0px 12px 0px 20px; width: 100%; z-index: 2; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-1i2qaio { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: center; order: 1; padding: 0px; width: 44px; will-change: var(--framer-will-change-override, transform); }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-8u6qs4 { left: unset; order: 1; position: relative; top: unset; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-1yfdksk { align-content: flex-start; align-items: flex-start; flex-direction: column; justify-content: flex-start; padding: 0px 40px 0px 40px; z-index: 2; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-416di-container { height: 50px; order: 0; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-mcxpb4-container { height: 50px; order: 2; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-ubp8oh-container { height: 50px; order: 1; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-19xmimc-container { height: 50px; order: 6; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-54zb69-container { height: 50px; order: 3; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-1wquugj-container { height: 50px; order: 4; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-orn40b-container { height: 50px; order: 5; }",
	".framer-H2m1B.framer-v-1p3qe8f .framer-1dofrp2 { flex: none; justify-content: center; padding: 0px 40px 0px 40px; width: min-content; }",
	'.framer-H2m1B[data-border="true"]::after, .framer-H2m1B [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	'.framer-H2m1B[data-hide-scrollbars="true"]::-webkit-scrollbar, .framer-H2m1B [data-hide-scrollbars="true"]::-webkit-scrollbar { width: 0px; height: 0px; }',
	'.framer-H2m1B[data-hide-scrollbars="true"]::-webkit-scrollbar-thumb, .framer-H2m1B [data-hide-scrollbars="true"]::-webkit-scrollbar-thumb { background: transparent; }',
	'.framer-H2m1B[data-hide-scrollbars="true"], .framer-H2m1B [data-hide-scrollbars="true"] { scrollbar-width: none; }',
];
var Framert4OAPb8Bp = withCSS3(Component3, css3, "framer-H2m1B");
var stdin_default6 = Framert4OAPb8Bp;
Framert4OAPb8Bp.displayName = "Navigation / Navigation Bar";
Framert4OAPb8Bp.defaultProps = {
	height: 75,
	width: 1200,
};
addPropertyControls3(Framert4OAPb8Bp, {
	variant: {
		options: ["iYCxTGtVM", "BSWPs3H_g", "y7ork0Jbc"],
		optionTitles: ["Desktop", "Phone", "Phone Open"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts(
	Framert4OAPb8Bp,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LogoFonts,
		...IconFonts,
		...Icon1Fonts,
		...LinkFonts,
		...ButtonButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/navigation-bar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "BSWPs3H_g",
	xl: "iYCxTGtVM",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationBarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var navigation_bar_default = ComponentWithRoot;
export { navigation_bar_default as default };
