// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Review Compact Size' | 'Review' | 'Mobile Version' | 'Mobile Version 2' // Variant
 * logo?: {src: string, srcSet?: string, alt?: string} // Logo
 * userImage?: {src: string, srcSet?: string, alt?: string} // User Image
 * userId?: string // user id
 * comment?: string // Comment
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-2LE5K7IJ.js";
import { Icon } from "./chunks/chunk-NS43VYZ6.js";
import { className, css, fonts } from "./chunks/chunk-VU34HTVO.js";
import "./chunks/chunk-MM5BHUY4.js";
import "./chunks/chunk-NULYBL27.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-3BOD4WL3.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:comment-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rFYRlMw8EzlDMWqpFFAe/YaAU4YGg8sarnLvFKR0J/gOqWIhZ81.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["PTcc526xJ", "rlIsphzc8", "sMevRrMhH", "qz0QYMdbf"];
var serializationHash = "framer-1yOBp";
var variantClassNames = {
	PTcc526xJ: "framer-v-150pdxy",
	qz0QYMdbf: "framer-v-19bw58k",
	rlIsphzc8: "framer-v-1bcm3vq",
	sMevRrMhH: "framer-v-ihju7a",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Mobile Version 2": "qz0QYMdbf",
	"Mobile Version": "sMevRrMhH",
	"Review Compact Size": "PTcc526xJ",
	Review: "rlIsphzc8",
};
var getProps = ({
	comment,
	height,
	id,
	logo,
	userId,
	userImage,
	width,
	...props
}) => {
	return {
		...props,
		cK8coHtT3: comment ?? props.cK8coHtT3 ?? "You! My Name is Benzaaamin!",
		cZnZe5DNo: logo ??
			props.cZnZe5DNo ?? {
				alt: "",
				pixelHeight: 160,
				pixelWidth: 160,
				src: "https://framerusercontent.com/images/FIRQ1C62VwXfKsg0Rn3rcRHoE.png",
			},
		MwYZSC7DU: userImage ??
			props.MwYZSC7DU ?? {
				alt: "",
				pixelHeight: 3264,
				pixelWidth: 4928,
				src: "https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg 4928w",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "PTcc526xJ",
		YUzF8O6Eo: userId ?? props.YUzF8O6Eo ?? "@mark_locus",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		cZnZe5DNo,
		MwYZSC7DU,
		YUzF8O6Eo,
		cK8coHtT3,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "PTcc526xJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onClickwu3rjm = activeVariantCallback(async (...args) => {
		setVariant("PTcc526xJ");
	});
	const sharedStyleClassNames = [className3, className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["rlIsphzc8", "qz0QYMdbf"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-150pdxy",
							className4,
							classNames,
						)}
						data-framer-name={"Review Compact Size"}
						layoutDependency={layoutDependency}
						layoutId={"PTcc526xJ"}
						ref={refBinding}
						style={{
							boxShadow: "5px 5px 15px 0px rgba(0, 0, 0, 0.02)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								qz0QYMdbf: {
									"data-framer-name": "Mobile Version 2",
								},
								rlIsphzc8: {
									"data-framer-name": "Review",
								},
								sMevRrMhH: {
									"data-framer-name": "Mobile Version",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-110yfck"}
							data-border={true}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"V7yP9rk1p"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(217, 217, 217))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "dashed",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 0 + 25,
									),
									pixelHeight: 3264,
									pixelWidth: 4928,
									sizes: "57px",
									...toResponsiveImage(MwYZSC7DU),
								}}
								className={"framer-b8ob2a"}
								data-framer-name={"Logo"}
								layoutDependency={layoutDependency}
								layoutId={"CtCwb7JZi"}
								style={{
									borderBottomLeftRadius: 90,
									borderBottomRightRadius: 90,
									borderTopLeftRadius: 90,
									borderTopRightRadius: 90,
								}}
								{...addPropertyOverrides(
									{
										qz0QYMdbf: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 10,
												),
												pixelHeight: 3264,
												pixelWidth: 4928,
												sizes: "57px",
												...toResponsiveImage(MwYZSC7DU),
											},
										},
										sMevRrMhH: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 10,
												),
												pixelHeight: 3264,
												pixelWidth: 4928,
												sizes: "57px",
												...toResponsiveImage(MwYZSC7DU),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-5lh3q4"}
								data-framer-name={"Text content"}
								layoutDependency={layoutDependency}
								layoutId={"RhWmE2DlP"}
							>
								<motion.div
									className={"framer-nmea"}
									data-framer-name={"Username + date"}
									layoutDependency={layoutDependency}
									layoutId={"l7h6oGHjl"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1lvrmnp"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"xJwvy5ANn"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={YUzF8O6Eo}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												rlIsphzc8: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-71c1l6"}
																data-styles-preset={"r7igaR65_"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
																}}
															>
																{"@mark_locus"}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-19bvac3"}
												data-styles-preset={"ZTKtBvUjS"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
												}}
											>
												{"@mark_locus"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-znd297"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"bHrfjqfOF"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={cK8coHtT3}
									variants={{
										rlIsphzc8: {
											"--extracted-1w1cjl5":
												"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											qz0QYMdbf: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-19bvac3"}
															data-styles-preset={"ZTKtBvUjS"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
															}}
														>
															{"You! My Name is Benzaaamin!"}
														</motion.p>
													</React.Fragment>
												),
											},
											rlIsphzc8: {
												children: (
													<React.Fragment>
														<motion.h6
															className={"framer-styles-preset-1tc4cz7"}
															data-styles-preset={"nlLyRgfpO"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1w1cjl5, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
															}}
														>
															{"You! My Name is Benzaaamin!"}
														</motion.h6>
													</React.Fragment>
												),
											},
											sMevRrMhH: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-19bvac3"}
															data-styles-preset={"ZTKtBvUjS"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
															}}
														>
															{"You! My Name is Benzaaamin!"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-71c1l6"}
											data-styles-preset={"r7igaR65_"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
											}}
										>
											{"You! My Name is Benzaaamin!"}
										</motion.p>
									</React.Fragment>
								</RichText>
								{isDisplayed() && (
									<motion.div
										className={"framer-s4jusr"}
										data-framer-name={"Youtube Comment UI"}
										layoutDependency={layoutDependency}
										layoutId={"jAOZoYGUX"}
									>
										<motion.div
											className={"framer-1i1egt0"}
											data-framer-name={"Icons"}
											layoutDependency={layoutDependency}
											layoutId={"Dky8k8lKK"}
										>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-1fymjge-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"zjtnmGP_p-container"}
													nodeId={"zjtnmGP_p"}
													rendersWithMotion={true}
													scopeId={"gOqWIhZ81"}
												>
													<Icon
														color={
															"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))"
														}
														height={"100%"}
														iconSearch={"thumbs up"}
														iconSelection={"House"}
														id={"zjtnmGP_p"}
														layoutId={"zjtnmGP_p"}
														mirrored={false}
														onClick={onClickwu3rjm}
														selectByList={false}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"regular"}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<ComponentViewportProvider>
												<SmartComponentScopedContainer
													className={"framer-z2cimi-container"}
													isAuthoredByUser={true}
													isModuleExternal={true}
													layoutDependency={layoutDependency}
													layoutId={"MU9sL01fh-container"}
													nodeId={"MU9sL01fh"}
													rendersWithMotion={true}
													scopeId={"gOqWIhZ81"}
													style={{
														rotate: -180,
													}}
												>
													<Icon
														color={
															"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))"
														}
														height={"100%"}
														iconSearch={"thumbs up"}
														iconSelection={"House"}
														id={"MU9sL01fh"}
														layoutId={"MU9sL01fh"}
														mirrored={false}
														onClick={onClickwu3rjm}
														selectByList={false}
														style={{
															height: "100%",
															width: "100%",
														}}
														weight={"regular"}
														width={"100%"}
													/>
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										</motion.div>
										<motion.div
											className={"framer-jowjlo"}
											data-framer-name={"Logo Icon"}
											layoutDependency={layoutDependency}
											layoutId={"CQQi51GsI"}
										>
											<Image
												background={{
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															25 +
															0 +
															170.4 +
															0 +
															0,
													),
													pixelHeight: 160,
													pixelWidth: 160,
													sizes: "26.5px",
													...toResponsiveImage(cZnZe5DNo),
												}}
												className={"framer-q63l67"}
												data-framer-name={"content"}
												layoutDependency={layoutDependency}
												layoutId={"dOBCycEIQ"}
												style={{
													borderBottomLeftRadius: 26.5,
													borderBottomRightRadius: 26.5,
													borderTopLeftRadius: 26.5,
													borderTopRightRadius: 26.5,
												}}
												{...addPropertyOverrides(
													{
														sMevRrMhH: {
															background: {
																alt: "",
																fit: "fill",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		0 +
																		10 +
																		0 +
																		154.4 +
																		0 +
																		0,
																),
																pixelHeight: 160,
																pixelWidth: 160,
																sizes: "26.5px",
																...toResponsiveImage(cZnZe5DNo),
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-1duj58x-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"XdzNOYzY1-container"}
														nodeId={"XdzNOYzY1"}
														rendersWithMotion={true}
														scopeId={"gOqWIhZ81"}
													>
														<Icon
															color={"rgb(255, 255, 255)"}
															height={"100%"}
															iconSearch={"heart"}
															iconSelection={"House"}
															id={"XdzNOYzY1"}
															layoutId={"XdzNOYzY1"}
															mirrored={false}
															onClick={onClickwu3rjm}
															selectByList={false}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"fill"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</Image>
										</motion.div>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-11w9mr6"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Kxq1zYmus"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													sMevRrMhH: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-19bvac3"}
																	data-styles-preset={"ZTKtBvUjS"}
																>
																	{"Reply"}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
													}}
												>
													{"Reply"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								)}
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-1yOBp.framer-x0wvyo, .framer-1yOBp .framer-x0wvyo { display: block; }",
	".framer-1yOBp.framer-150pdxy { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 337px; }",
	".framer-1yOBp .framer-110yfck { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 25px; position: relative; width: 1px; }",
	".framer-1yOBp .framer-b8ob2a { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 57px); overflow: hidden; position: relative; width: 57px; will-change: var(--framer-will-change-override, transform); }",
	".framer-1yOBp .framer-5lh3q4 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-1yOBp .framer-nmea { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-1yOBp .framer-1lvrmnp, .framer-1yOBp .framer-11w9mr6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-1yOBp .framer-znd297 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-1yOBp .framer-s4jusr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-1yOBp .framer-1i1egt0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-1yOBp .framer-1fymjge-container, .framer-1yOBp .framer-z2cimi-container { flex: none; height: 18px; position: relative; width: 18px; }",
	".framer-1yOBp .framer-jowjlo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-1yOBp .framer-q63l67 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6.63px; height: var(--framer-aspect-ratio-supported, 27px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 27px; }",
	".framer-1yOBp .framer-1duj58x-container { bottom: -1px; flex: none; height: 13px; position: absolute; right: -2px; width: 13px; z-index: 1; }",
	".framer-1yOBp.framer-v-1bcm3vq.framer-150pdxy { width: 500px; }",
	".framer-1yOBp.framer-v-ihju7a .framer-110yfck { flex: none; padding: 10px; width: 318px; }",
	".framer-1yOBp.framer-v-19bw58k.framer-150pdxy { width: 277px; }",
	".framer-1yOBp.framer-v-19bw58k .framer-110yfck { flex: none; padding: 10px; width: 217px; }",
	...css3,
	...css2,
	...css,
	'.framer-1yOBp[data-border="true"]::after, .framer-1yOBp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramergOqWIhZ81 = withCSS(Component, css4, "framer-1yOBp");
var stdin_default = FramergOqWIhZ81;
FramergOqWIhZ81.displayName = "Comment Card";
FramergOqWIhZ81.defaultProps = {
	height: 143.5,
	width: 336.5,
};
addPropertyControls(FramergOqWIhZ81, {
	variant: {
		options: ["PTcc526xJ", "rlIsphzc8", "sMevRrMhH", "qz0QYMdbf"],
		optionTitles: [
			"Review Compact Size",
			"Review",
			"Mobile Version",
			"Mobile Version 2",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	cZnZe5DNo: {
		__defaultAssetReference:
			"data:framer/asset-reference,FIRQ1C62VwXfKsg0Rn3rcRHoE.png?originalFilename=Stack%404x.png&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,FIRQ1C62VwXfKsg0Rn3rcRHoE.png?originalFilename=Stack%404x.png&preferredSize=auto",
		},
		title: "Logo",
		type: ControlType.ResponsiveImage,
	},
	MwYZSC7DU: {
		__defaultAssetReference:
			"data:framer/asset-reference,IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?originalFilename=photo-1564564321837-a57b7070ac4f%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw2fHxtYW58ZW58MHx8fHwxNzQ2NDA5MDg3fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?originalFilename=photo-1564564321837-a57b7070ac4f%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw2fHxtYW58ZW58MHx8fHwxNzQ2NDA5MDg3fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		},
		title: "User Image",
		type: ControlType.ResponsiveImage,
	},
	YUzF8O6Eo: {
		defaultValue: "@mark_locus",
		displayTextArea: false,
		title: "user id",
		type: ControlType.String,
	},
	cK8coHtT3: {
		defaultValue: "You! My Name is Benzaaamin!",
		displayTextArea: false,
		title: "Comment",
		type: ControlType.String,
	},
});
addFonts(
	FramergOqWIhZ81,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:comment-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "qz0QYMdbf",
	xl: "PTcc526xJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CommentCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var comment_card_default = ComponentWithRoot;
export { comment_card_default as default };
