// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-QAKPHGHA.js";
import { className, css, fonts } from "./chunks/chunk-J45GE5O3.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-2LE5K7IJ.js";
import { stdin_default } from "./chunks/chunk-XRQ2RYSH.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-YY62L3WU.js";
import "./chunks/chunk-VU34HTVO.js";
import "./chunks/chunk-MM5BHUY4.js";
import "./chunks/chunk-NULYBL27.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:cta-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/yEsawBIr6FfIWjjFO6HZ/8baI6FlSR9uGooAysDt9/vCAXZqRK3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var ButtonButtonFonts = getFonts(stdin_default2);
var ParticlesFonts = getFonts(stdin_default);
var cycleOrder = ["imxaIyynY", "F8p0ihxO9", "hxeaGOJpv"];
var serializationHash = "framer-8SoDK";
var variantClassNames = {
	F8p0ihxO9: "framer-v-1let27h",
	hxeaGOJpv: "framer-v-d420s7",
	imxaIyynY: "framer-v-1oayy7x",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0.6,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "imxaIyynY",
	Phone: "hxeaGOJpv",
	Tablet: "F8p0ihxO9",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "imxaIyynY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "imxaIyynY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "hxeaGOJpv") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1oayy7x",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"imxaIyynY"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								F8p0ihxO9: {
									"data-framer-name": "Tablet",
								},
								hxeaGOJpv: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1f86kh7"}
							data-framer-name={"Section Title"}
							layoutDependency={layoutDependency}
							layoutId={"jBqkkobxK"}
							style={{
								backgroundColor:
									"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						>
							<motion.div
								className={"framer-8hc4j"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"q_JxZ3G9Z"}
							>
								<RichTextWithFXWithOptimizedAppearEffect
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-jx14v9"}
									data-framer-appear-id={"jx14v9"}
									data-framer-name={"Title"}
									fonts={["Inter"]}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"KgpQ_EaVF"}
									optimized={true}
									style={{
										"--extracted-1of0zx5":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											className={"framer-styles-preset-4fkw8l"}
											data-styles-preset={"x3k2llX6m"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
											}}
										>
											{"Ready to Level Up?"}
										</motion.h2>
									</React.Fragment>
								</RichTextWithFXWithOptimizedAppearEffect>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-q5tl1b"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ciwCxsAjX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(230, 230, 230))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-6bhg54"}
											data-styles-preset={"Hjw3T0c61"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(230, 230, 230)))",
											}}
										>
											{
												"Whether it\u2019s a one-off edit or a full channel transformation, we\u2019re ready when you are. Let\u2019s talk ideas."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<ComponentViewportProvider
								height={60}
								y={(componentViewport?.y || 0) + 0 + 0 + 60 + 232.6}
							>
								<SmartComponentScopedContainer
									className={"framer-986pgy-container"}
									layoutDependency={layoutDependency}
									layoutId={"hzQcsccNN-container"}
									nodeId={"hzQcsccNN"}
									rendersWithMotion={true}
									scopeId={"vCAXZqRK3"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "hzQcsccNN",
										layoutId: "hzQcsccNN",
										QPXgBsk7h: "Get Started",
										variant: matchVariant("httELeRMt"),
										width: "100%",
										...addPropertyOverrides(
											{
												hxeaGOJpv: {
													variant: matchVariant("XS4Fn3AGp"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={128}
								width={componentViewport?.width || "100vw"}
								y={(componentViewport?.y || 0) + 0 + 0 + 412.6 - 128}
								{...addPropertyOverrides(
									{
										F8p0ihxO9: {
											width: `calc(${componentViewport?.width || "100vw"} - 20px)`,
										},
										hxeaGOJpv: {
											width: "900px",
											y: (componentViewport?.y || 0) + 0 + 0 + 412.6 - 131,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1ineusg-container"}
									layoutDependency={layoutDependency}
									layoutId={"olbX14Eum-container"}
									nodeId={"olbX14Eum"}
									rendersWithMotion={true}
									scopeId={"vCAXZqRK3"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "olbX14Eum",
										layoutId: "olbX14Eum",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion.div
								className={"framer-1blxp5v"}
								data-framer-name={"Point 1"}
								layoutDependency={layoutDependency}
								layoutId={"fpZbmF1jp"}
								style={{
									backgroundColor:
										"var(--token-c9831028-2838-4766-90a4-c4911c0f418b, rgb(255, 81, 0))",
									borderBottomLeftRadius: 11.79,
									borderBottomRightRadius: 11.79,
									borderTopLeftRadius: 11.79,
									borderTopRightRadius: 11.79,
									boxShadow:
										"-16.07px -2.42px 54px 0px rgba(255, 81, 0, 0.4), inset 0px 1.62px 24px 0px rgba(255, 255, 255, 0.25)",
									rotate: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									hxeaGOJpv: {
										rotate: -4,
									},
								}}
								{...addPropertyOverrides(
									{
										F8p0ihxO9: {
											transformTemplate: transformTemplate2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1isywwl"}
									data-framer-name={"Working on it now!"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"V2JPITUl6"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-19bvac3"}
											data-styles-preset={"ZTKtBvUjS"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
											}}
										>
											{"Conversion Boost"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-ef665a"}
								data-framer-name={"Point 1"}
								layoutDependency={layoutDependency}
								layoutId={"yoo3Su4xp"}
								style={{
									backgroundColor:
										"var(--token-c9831028-2838-4766-90a4-c4911c0f418b, rgb(255, 81, 0))",
									borderBottomLeftRadius: 11.79,
									borderBottomRightRadius: 11.79,
									borderTopLeftRadius: 11.79,
									borderTopRightRadius: 11.79,
									boxShadow:
										"-16.07px -2.42px 54px 0px rgba(255, 81, 0, 0.4), inset 0px 1.62px 24px 0px rgba(255, 255, 255, 0.25)",
								}}
								transformTemplate={transformTemplate1}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1559t6s"}
									data-framer-name={"Working on it now!"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ptkGpEcbY"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-19bvac3"}
											data-styles-preset={"ZTKtBvUjS"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
											}}
										>
											{"No Editor?  No Problem"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<ComponentViewportProvider
									height={41.4}
									y={(componentViewport?.y || 0) + 0 + 0 + 412.6 - 40.9 + 0}
								>
									<SmartComponentScopedContainer
										className={"framer-secnlk-container"}
										layoutDependency={layoutDependency}
										layoutId={"l4cHsMkJ1-container"}
										nodeId={"l4cHsMkJ1"}
										rendersWithMotion={true}
										scopeId={"vCAXZqRK3"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "l4cHsMkJ1",
											layoutId: "l4cHsMkJ1",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<motion.div
								className={"framer-rjnf1l"}
								data-border={true}
								data-framer-name={"Point 3"}
								layoutDependency={layoutDependency}
								layoutId={"faxobBDtx"}
								style={{
									"--border-bottom-width": "0.8px",
									"--border-color":
										"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
									"--border-left-width": "0.8px",
									"--border-right-width": "0.8px",
									"--border-style": "dashed",
									"--border-top-width": "0.8px",
									backgroundColor:
										"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
									borderBottomLeftRadius: 11.79,
									borderBottomRightRadius: 11.79,
									borderTopLeftRadius: 11.79,
									borderTopRightRadius: 11.79,
									rotate: 13,
								}}
								transformTemplate={transformTemplate2}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-z3vjc6"}
									data-framer-name={"Working on it now!"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"D9xhdJakr"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											hxeaGOJpv: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-19bvac3"}
															data-styles-preset={"ZTKtBvUjS"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															{"Fixed CTR"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-19bvac3"}
											data-styles-preset={"ZTKtBvUjS"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
											}}
										>
											{"Low Views? Fixed"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-10jyet7"}
								data-border={true}
								data-framer-name={"Point 3"}
								layoutDependency={layoutDependency}
								layoutId={"rIeTclqwd"}
								style={{
									"--border-bottom-width": "0.8px",
									"--border-color":
										"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
									"--border-left-width": "0.8px",
									"--border-right-width": "0.8px",
									"--border-style": "dashed",
									"--border-top-width": "0.8px",
									backgroundColor:
										"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
									borderBottomLeftRadius: 11.79,
									borderBottomRightRadius: 11.79,
									borderTopLeftRadius: 11.79,
									borderTopRightRadius: 11.79,
									rotate: -25,
								}}
								transformTemplate={transformTemplate2}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1it69xm"}
									data-framer-name={"Working on it now!"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"QFKn60x8C"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-19bvac3"}
											data-styles-preset={"ZTKtBvUjS"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
											}}
										>
											{"Watch Time Wins"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<ComponentViewportProvider
									height={40.9}
									y={(componentViewport?.y || 0) + 0 + 0 + 328.9832 + 0}
									{...addPropertyOverrides(
										{
											F8p0ihxO9: {
												height: 41,
												width: "145px",
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													324.9167 +
													-0.3025,
											},
											hxeaGOJpv: {
												height: 41,
												width: "145px",
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													328.9832 +
													-0.3025,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1s41rww-container"}
										layoutDependency={layoutDependency}
										layoutId={"Y9UQ5spXw-container"}
										nodeId={"Y9UQ5spXw"}
										rendersWithMotion={true}
										scopeId={"vCAXZqRK3"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "Y9UQ5spXw",
											layoutId: "Y9UQ5spXw",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-8bq6zn"}
									data-border={true}
									data-framer-name={"Point 3"}
									layoutDependency={layoutDependency}
									layoutId={"Mja2aYcSi"}
									style={{
										"--border-bottom-width": "0.8px",
										"--border-color":
											"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
										"--border-left-width": "0.8px",
										"--border-right-width": "0.8px",
										"--border-style": "dashed",
										"--border-top-width": "0.8px",
										backgroundColor:
											"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
										borderBottomLeftRadius: 11.79,
										borderBottomRightRadius: 11.79,
										borderTopLeftRadius: 11.79,
										borderTopRightRadius: 11.79,
										rotate: -21,
									}}
									transformTemplate={transformTemplate2}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-x485lr"}
										data-framer-name={"Working on it now!"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"soj1k5kNN"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-19bvac3"}
												data-styles-preset={"ZTKtBvUjS"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
												}}
											>
												{"From meh to wow!"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							)}
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8SoDK.framer-158tf2a, .framer-8SoDK .framer-158tf2a { display: block; }",
	".framer-8SoDK.framer-1oayy7x { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; max-width: 900px; overflow: hidden; padding: 0px; position: relative; width: 900px; }",
	".framer-8SoDK .framer-1f86kh7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 60px 20px 60px 20px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-8SoDK .framer-8hc4j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: wrap; gap: 16px 10px; height: min-content; justify-content: flex-start; max-width: 600px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 4; }",
	".framer-8SoDK .framer-jx14v9, .framer-8SoDK .framer-q5tl1b { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-8SoDK .framer-986pgy-container { flex: none; height: auto; position: relative; width: auto; z-index: 5; }",
	".framer-8SoDK .framer-1ineusg-container { bottom: 0px; flex: none; height: 128px; left: 0px; position: absolute; right: 0px; z-index: 1; }",
	".framer-8SoDK .framer-1blxp5v { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14.73px; height: min-content; justify-content: center; left: 82%; overflow: visible; padding: 8.04px 16.07px 10.46px 16.07px; position: absolute; width: min-content; z-index: 2; }",
	".framer-8SoDK .framer-1isywwl, .framer-8SoDK .framer-1559t6s, .framer-8SoDK .framer-z3vjc6, .framer-8SoDK .framer-1it69xm, .framer-8SoDK .framer-x485lr { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-8SoDK .framer-ef665a { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14.73px; height: min-content; justify-content: center; left: 23%; overflow: visible; padding: 8.04px 16.07px 10.46px 16.07px; position: absolute; width: min-content; z-index: 2; }",
	".framer-8SoDK .framer-secnlk-container, .framer-8SoDK .framer-1s41rww-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-8SoDK .framer-rjnf1l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14.73px; height: min-content; justify-content: center; left: 91%; overflow: visible; padding: 8.04px 16.07px 10.46px 16.07px; position: absolute; top: 81%; width: min-content; z-index: 1; }",
	".framer-8SoDK .framer-10jyet7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14.73px; height: min-content; justify-content: center; left: 70%; overflow: visible; padding: 8.04px 16.07px 10.46px 16.07px; position: absolute; top: 85%; width: min-content; z-index: 1; }",
	".framer-8SoDK .framer-8bq6zn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14.73px; height: min-content; justify-content: center; left: 7%; overflow: visible; padding: 8.04px 16.07px 10.46px 16.07px; position: absolute; top: 86%; width: min-content; z-index: 1; }",
	".framer-8SoDK.framer-v-1let27h.framer-1oayy7x { padding: 0px 10px 0px 10px; width: 810px; }",
	".framer-8SoDK.framer-v-1let27h .framer-1blxp5v { bottom: unset; left: 82%; top: 93%; }",
	".framer-8SoDK.framer-v-1let27h .framer-rjnf1l { left: 91%; top: 80%; }",
	".framer-8SoDK.framer-v-1let27h .framer-10jyet7 { left: 69%; top: 84%; }",
	".framer-8SoDK.framer-v-1let27h .framer-1s41rww-container, .framer-8SoDK.framer-v-d420s7 .framer-1s41rww-container { bottom: unset; height: 41px; left: calc(49.655172413793125% - 145px / 2); right: unset; top: calc(49.382716049382736% - 41px / 2); width: 145px; }",
	".framer-8SoDK.framer-v-1let27h .framer-8bq6zn { left: 9%; top: 82%; }",
	".framer-8SoDK.framer-v-d420s7.framer-1oayy7x { padding: 0px 10px 0px 10px; width: 390px; }",
	".framer-8SoDK.framer-v-d420s7 .framer-1ineusg-container { bottom: 3px; left: 97px; right: unset; width: 900px; }",
	".framer-8SoDK.framer-v-d420s7 .framer-1blxp5v { bottom: -3px; left: 80%; }",
	".framer-8SoDK.framer-v-d420s7 .framer-ef665a { left: 25%; }",
	".framer-8SoDK.framer-v-d420s7 .framer-rjnf1l { left: 18%; top: 84%; }",
	...css,
	...css3,
	...css2,
	'.framer-8SoDK[data-border="true"]::after, .framer-8SoDK [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramervCAXZqRK3 = withCSS(Component, css4, "framer-8SoDK");
var stdin_default3 = FramervCAXZqRK3;
FramervCAXZqRK3.displayName = "CTA Card";
FramervCAXZqRK3.defaultProps = {
	height: 332,
	width: 900,
};
addPropertyControls(FramervCAXZqRK3, {
	variant: {
		options: ["imxaIyynY", "F8p0ihxO9", "hxeaGOJpv"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramervCAXZqRK3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonButtonFonts,
		...ParticlesFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramervCAXZqRK3.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:cta-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "hxeaGOJpv",
	md: "F8p0ihxO9",
	xl: "imxaIyynY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var cta_card_default = ComponentWithRoot;
export { cta_card_default as default };
