// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Open ' | 'Close' // Variant
 * question?: string // Question
 * answer?: string // Answer
 * click?: Function // Click
}} Props

 */
import { Icon } from "./chunks/chunk-66EJKQKM.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PRGAOH24.js";
import { stdin_default } from "./chunks/chunk-LHCNLORJ.js";
import "./chunks/chunk-NULYBL27.js";
import { className, css, fonts } from "./chunks/chunk-DFDE4R6M.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:faq-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ipvOUNKcMdPlWeGGMIeN/eQ26cMUCj2H91veJwNxy/YvR6xnOIO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var FeatherFonts = getFonts(Icon);
var ParticlesFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var cycleOrder = ["kKpQn0BQi", "L42y4_ufu"];
var serializationHash = "framer-W9nGf";
var variantClassNames = {
	kKpQn0BQi: "framer-v-1x3y2yn",
	L42y4_ufu: "framer-v-osegjc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 50,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Open ": "kKpQn0BQi",
	Close: "L42y4_ufu",
};
var getProps = ({ answer, click, height, id, question, width, ...props }) => {
	return {
		...props,
		Nj2z_khhV:
			question ?? props.Nj2z_khhV ?? "What types of videos do you edit?",
		OBqVdO87N: answer ?? props.OBqVdO87N ?? "What types of videos do you edit?",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "kKpQn0BQi",
		ynZzrUCLU: click ?? props.ynZzrUCLU,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		Nj2z_khhV,
		OBqVdO87N,
		ynZzrUCLU,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "kKpQn0BQi",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1mn5fmo = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (ynZzrUCLU) {
			const res = await ynZzrUCLU(...args);
			if (res === false) return false;
		}
		setVariant("L42y4_ufu");
	});
	const onTap1u007gf = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (ynZzrUCLU) {
			const res = await ynZzrUCLU(...args);
			if (res === false) return false;
		}
		setVariant("kKpQn0BQi");
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "L42y4_ufu") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1x3y2yn",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Open "}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"kKpQn0BQi"}
						onTap={onTap1mn5fmo}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "dashed",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
							borderBottomLeftRadius: 12,
							borderBottomRightRadius: 12,
							borderTopLeftRadius: 12,
							borderTopRightRadius: 12,
							boxShadow: "none",
							...style,
						}}
						variants={{
							L42y4_ufu: {
								"--border-color":
									"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(230, 230, 230))",
								backgroundColor:
									"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
								boxShadow: "5px 5px 15px 0px rgba(0, 0, 0, 0.02)",
							},
						}}
						{...addPropertyOverrides(
							{
								L42y4_ufu: {
									"data-framer-name": "Close",
									onTap: onTap1u007gf,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1maml1f"}
							data-framer-name={"Question "}
							layoutDependency={layoutDependency}
							layoutId={"qiwOswxVs"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1badrel"}
								data-framer-name={"Do you offer a free trial?"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"H55XQX6p1"}
								style={{
									"--extracted-1w1cjl5":
										"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={Nj2z_khhV}
								variants={{
									L42y4_ufu: {
										"--extracted-1w1cjl5":
											"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										L42y4_ufu: {
											children: (
												<React.Fragment>
													<motion.h6
														className={"framer-styles-preset-1tc4cz7"}
														data-styles-preset={"nlLyRgfpO"}
														style={{
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
														}}
													>
														{"What types of videos do you edit?"}
													</motion.h6>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-1tc4cz7"}
										data-styles-preset={"nlLyRgfpO"}
										style={{
											"--framer-text-color":
												"var(--extracted-1w1cjl5, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
										}}
									>
										{"What types of videos do you edit?"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-159xa2d-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"DJ7BOG2dV-container"}
									nodeId={"DJ7BOG2dV"}
									rendersWithMotion={true}
									scopeId={"YvR6xnOIO"}
									style={{
										rotate: 0,
									}}
									variants={{
										L42y4_ufu: {
											rotate: 180,
										},
									}}
								>
									<Icon
										color={
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))"
										}
										height={"100%"}
										iconSearch={"Home"}
										iconSelection={"chevron-up"}
										id={"DJ7BOG2dV"}
										layoutId={"DJ7BOG2dV"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
										{...addPropertyOverrides(
											{
												L42y4_ufu: {
													color:
														"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-140uev3"}
								data-framer-name={"Supporting text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"uKOtbjaXm"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={OBqVdO87N}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-71c1l6"}
										data-styles-preset={"r7igaR65_"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
										}}
									>
										{"What types of videos do you edit?"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						<ComponentViewportProvider
							height={30}
							width={"70px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 114) -
								21
							}
							{...addPropertyOverrides(
								{
									L42y4_ufu: {
										y:
											(componentViewport?.y || 0) +
											(componentViewport?.height || 77) -
											21,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={false}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-tunvza-container"}
								layoutDependency={layoutDependency}
								layoutId={"ari4FndMd-container"}
								nodeId={"ari4FndMd"}
								rendersWithMotion={true}
								scopeId={"YvR6xnOIO"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "ari4FndMd",
									layoutId: "ari4FndMd",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-W9nGf.framer-m6fr1t, .framer-W9nGf .framer-m6fr1t { display: block; }",
	".framer-W9nGf.framer-1x3y2yn { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 25px; position: relative; width: 608px; will-change: var(--framer-will-change-override, transform); }",
	".framer-W9nGf .framer-1maml1f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-W9nGf .framer-1badrel { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-W9nGf .framer-159xa2d-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 27px); position: relative; width: 24px; }",
	".framer-W9nGf .framer-140uev3 { flex: none; height: auto; max-width: 514px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-W9nGf .framer-tunvza-container { bottom: -9px; flex: none; height: 30px; position: absolute; right: 109px; width: 70px; z-index: 1; }",
	...css,
	...css2,
	'.framer-W9nGf[data-border="true"]::after, .framer-W9nGf [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerYvR6xnOIO = withCSS(Component, css3, "framer-W9nGf");
var stdin_default2 = FramerYvR6xnOIO;
FramerYvR6xnOIO.displayName = "Faq Card";
FramerYvR6xnOIO.defaultProps = {
	height: 114,
	width: 608,
};
addPropertyControls(FramerYvR6xnOIO, {
	variant: {
		options: ["kKpQn0BQi", "L42y4_ufu"],
		optionTitles: ["Open ", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Nj2z_khhV: {
		defaultValue: "What types of videos do you edit?",
		displayTextArea: false,
		title: "Question",
		type: ControlType.String,
	},
	OBqVdO87N: {
		defaultValue: "What types of videos do you edit?",
		displayTextArea: false,
		title: "Answer",
		type: ControlType.String,
	},
	ynZzrUCLU: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerYvR6xnOIO,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FeatherFonts,
		...ParticlesFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "L42y4_ufu",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_card_default = ComponentWithRoot;
export { faq_card_default as default };
