// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import {
	stdin_default as stdin_default2,
	stdin_default2 as stdin_default3,
} from "./chunks/chunk-BZHV5ZRO.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-54CILDJG.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-QAKPHGHA.js";
import { stdin_default } from "./chunks/chunk-XRQ2RYSH.js";
import { className, css, fonts } from "./chunks/chunk-3BOD4WL3.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/h7GV2wpmuu4iW3KVnp22/oO0Uo0OCssnJxQeJLJEt/yvjzglA30.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var LogoFonts = getFonts(stdin_default3);
var ParticlesFonts = getFonts(stdin_default);
var cycleOrder = ["C9ZJFndku", "Ohmrc2dBG", "GC4oZv7lw"];
var serializationHash = "framer-FW3Gp";
var variantClassNames = {
	C9ZJFndku: "framer-v-1n6h0kc",
	GC4oZv7lw: "framer-v-ufa31p",
	Ohmrc2dBG: "framer-v-rjflw2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "C9ZJFndku",
	Phone: "GC4oZv7lw",
	Tablet: "Ohmrc2dBG",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "C9ZJFndku",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "C9ZJFndku",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "GC4oZv7lw") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "GC4oZv7lw") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1n6h0kc",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"C9ZJFndku"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								GC4oZv7lw: {
									"data-framer-name": "Phone",
								},
								Ohmrc2dBG: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-muuk97"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"xJNx1BQYI"}
						>
							<motion.div
								className={"framer-ybd4wy"}
								data-framer-name={"Top content"}
								layoutDependency={layoutDependency}
								layoutId={"fgLeZJPnf"}
							>
								<motion.div
									className={"framer-4shon"}
									data-framer-name={"Logo & text"}
									layoutDependency={layoutDependency}
									layoutId={"WaUCfJLx5"}
								>
									<ComponentViewportProvider
										height={40}
										y={
											(componentViewport?.y || 0) +
											(120 +
												((componentViewport?.height || 620) - 240 - 379.6) /
													2) +
											0 +
											0 +
											0 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												GC4oZv7lw: {
													y:
														(componentViewport?.y || 0) +
														(80 +
															((componentViewport?.height || 200) -
																160 -
																903.6) /
																2) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												Ohmrc2dBG: {
													y:
														(componentViewport?.y || 0) +
														(80 +
															((componentViewport?.height || 480) -
																160 -
																319.6) /
																2) +
														0 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1ltz9qh-container"}
											layoutDependency={layoutDependency}
											layoutId={"jY1VCT43x-container"}
											nodeId={"jY1VCT43x"}
											rendersWithMotion={true}
											scopeId={"yvjzglA30"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "jY1VCT43x",
												layoutId: "jY1VCT43x",
												variant: matchVariant("gsnSyItA3"),
												width: "100%",
												zy_Wh_sny: stdin_default2,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-kataef"}
										data-framer-name={
											"Develops conceptual design ideas, refines them into detailed plans."
										}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Z42QvXlwk"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												GC4oZv7lw: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-71c1l6"}
																data-styles-preset={"r7igaR65_"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
																}}
															>
																{
																	"Helping youtubers stand out with pro edits, fast delivery and what not!"
																}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-71c1l6"}
												data-styles-preset={"r7igaR65_"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
												}}
											>
												{
													"Helping youtubers stand out with pro edits, fast delivery and what not!"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-nw4itf"}
									data-framer-name={"Link"}
									layoutDependency={layoutDependency}
									layoutId={"ORE4bbi_S"}
								>
									<motion.div
										className={"framer-fgt1kh"}
										data-framer-name={"Widget one"}
										layoutDependency={layoutDependency}
										layoutId={"mzaPiwnbU"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-cqapl5"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"WbO_XH9Zx"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
												"--framer-paragraph-spacing": "0px",
												opacity: 0.5,
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-6bhg54"}
													data-styles-preset={"Hjw3T0c61"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
													}}
												>
													{"Company"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-1t7vfb4"}
											data-framer-name={"Footer links"}
											layoutDependency={layoutDependency}
											layoutId={"aspNUhyW4"}
										>
											<motion.div
												className={"framer-1bunktm"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"PaqZ61Elo"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-13el9e3"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"PaqZ61ElonQqhDrmSE"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	webPageId: "augiA20Il",
																}}
																motionChild={true}
																nodeId={"PaqZ61ElonQqhDrmSE"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Home"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-12zpnsk"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"Q4ElwPLRT"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-mcjkyb"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"EwORxF_rl"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	hash: ":q7jn9iT4k",
																	webPageId: "augiA20Il",
																}}
																motionChild={true}
																nodeId={"EwORxF_rl"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={true}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Services"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-wy8061"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"KewVXPLH3"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1i1dg0n"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"PAY_aNhed"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	webPageId: "ONaKvcShR",
																}}
																motionChild={true}
																nodeId={"PAY_aNhed"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={true}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Works"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-1cqizg0"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"F_P5r2W2c"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-17aag3j"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"BY7Eho9f6"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	hash: ":CRnkfwqXz",
																	webPageId: "augiA20Il",
																}}
																motionChild={true}
																nodeId={"BY7Eho9f6"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={true}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Reviews"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-1lkgzsn"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"gZQHzyU3j"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1519vjw"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"lDq6XyDne"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	hash: ":OLPFkzjAU",
																	webPageId: "augiA20Il",
																}}
																motionChild={true}
																nodeId={"lDq6XyDne"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={true}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"FAQ"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-1aorf2w"}
										data-framer-name={"Widget two"}
										layoutDependency={layoutDependency}
										layoutId={"xA1tVGflO"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1q53fdo"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"mqMsNvnoR"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
												"--framer-paragraph-spacing": "0px",
												opacity: 0.5,
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-6bhg54"}
													data-styles-preset={"Hjw3T0c61"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
													}}
												>
													{"Legal Pages"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-89ob94"}
											data-framer-name={"Footer links"}
											layoutDependency={layoutDependency}
											layoutId={"aNQUY_OFt"}
										>
											<motion.div
												className={"framer-1bg9ieq"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"k1NJrULN8"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-bx580r"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"cqqixe1yC"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	pathVariables: {
																		ynIdbeLdM: "privacy-cookies",
																	},
																	unresolvedPathSlugs: {
																		ynIdbeLdM: {
																			collectionId: "MIO5f4Lc8",
																			collectionItemId: "Gg2jozIIb",
																		},
																	},
																	webPageId: "rKV3trLxm",
																}}
																motionChild={true}
																nodeId={"cqqixe1yC"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Privacy Policy"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-apz9ot"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"yjrnwESUn"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1k5hj4k"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"dLGO4BVW9"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	pathVariables: {
																		ynIdbeLdM: "terms-conditions",
																	},
																	unresolvedPathSlugs: {
																		ynIdbeLdM: {
																			collectionId: "MIO5f4Lc8",
																			collectionItemId: "qS74D70pa",
																		},
																	},
																	webPageId: "rKV3trLxm",
																}}
																motionChild={true}
																nodeId={"dLGO4BVW9"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Terms of Services"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-1w3haan"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"zqAM4N6wA"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-3pdgpu"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"YpnYmRGTn"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={{
																	pathVariables: {
																		ynIdbeLdM: "refund-policy",
																	},
																	unresolvedPathSlugs: {
																		ynIdbeLdM: {
																			collectionId: "MIO5f4Lc8",
																			collectionItemId: "lmkuRycvX",
																		},
																	},
																	webPageId: "rKV3trLxm",
																}}
																motionChild={true}
																nodeId={"YpnYmRGTn"}
																openInNewTab={false}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Refund Policy"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											{isDisplayed() && (
												<motion.div
													className={"framer-144kjuc"}
													data-border={true}
													data-framer-name={"Footer Navitem"}
													layoutDependency={layoutDependency}
													layoutId={"zR3ckR2NT"}
													style={{
														"--border-bottom-width": "1px",
														"--border-color": "rgba(42, 42, 42, 0)",
														"--border-left-width": "1px",
														"--border-right-width": "1px",
														"--border-style": "solid",
														"--border-top-width": "1px",
													}}
												/>
											)}
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-1johy5b"}
										data-framer-name={"Widget three"}
										layoutDependency={layoutDependency}
										layoutId={"L71tPXXuK"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1572t0z"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"waQyqvWev"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
												"--framer-paragraph-spacing": "0px",
												opacity: 0.5,
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-6bhg54"}
													data-styles-preset={"Hjw3T0c61"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
													}}
												>
													{"Socials"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<motion.div
											className={"framer-4u608f"}
											data-framer-name={"Footer links"}
											layoutDependency={layoutDependency}
											layoutId={"p3okECwDw"}
										>
											<motion.div
												className={"framer-jgpixt"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"RTuB114Bg"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-b2be00"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"Xv1wZVOuG"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={"linkedin.com"}
																motionChild={true}
																nodeId={"Xv1wZVOuG"}
																openInNewTab={true}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"LinkedIn"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-1hllug0"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"SYniZ0k4r"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1e0e174"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"PouZRid4A"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={"discord.com"}
																motionChild={true}
																nodeId={"PouZRid4A"}
																openInNewTab={true}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Discord"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-jg0ngk"}
												data-border={true}
												data-framer-name={"Footer Navitem"}
												layoutDependency={layoutDependency}
												layoutId={"NJlHr69ue"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color": "rgba(42, 42, 42, 0)",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1yg5yq4"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"SjstPAoyl"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6bhg54"}
															data-styles-preset={"Hjw3T0c61"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
															}}
														>
															<Link
																href={"twitter.com"}
																motionChild={true}
																nodeId={"SjstPAoyl"}
																openInNewTab={true}
																relValues={[]}
																scopeId={"yvjzglA30"}
																smoothScroll={false}
															>
																<motion.a
																	className={"framer-styles-preset-1ilkga"}
																	data-styles-preset={"NrYndXeRn"}
																>
																	{"Twitter"}
																</motion.a>
															</Link>
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											{isDisplayed() && (
												<motion.div
													className={"framer-mya5w5"}
													data-border={true}
													data-framer-name={"Footer Navitem"}
													layoutDependency={layoutDependency}
													layoutId={"N7OLvf68d"}
													style={{
														"--border-bottom-width": "1px",
														"--border-color": "rgba(42, 42, 42, 0)",
														"--border-left-width": "1px",
														"--border-right-width": "1px",
														"--border-style": "solid",
														"--border-top-width": "1px",
													}}
												/>
											)}
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-nwiqs9"}
								data-framer-name={"Bottom content"}
								layoutDependency={layoutDependency}
								layoutId={"fsvfz4hjD"}
							>
								<motion.div
									className={"framer-xm8c26"}
									layoutDependency={layoutDependency}
									layoutId={"FOPt0cfhA"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-l8hnvp"}
										data-framer-name={
											"Develops conceptual design ideas, refines them into detailed plans."
										}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ADerLxsjA"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
											opacity: 0.7,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-71c1l6"}
												data-styles-preset={"r7igaR65_"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
												}}
											>
												{"Copyright 2026 to FRAMIO"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
						{isDisplayed1() && (
							<ComponentViewportProvider
								{...addPropertyOverrides(
									{
										GC4oZv7lw: {
											height: 31,
											width: "70px",
											y:
												(componentViewport?.y || 0) +
												(componentViewport?.height || 200) -
												57.5,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-qii2ii-container"}
									layoutDependency={layoutDependency}
									layoutId={"CfC9ririL-container"}
									nodeId={"CfC9ririL"}
									rendersWithMotion={true}
									scopeId={"yvjzglA30"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "CfC9ririL",
										layoutId: "CfC9ririL",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed() && (
							<ComponentViewportProvider
								height={(componentViewport?.height || 620) - 549}
								width={`calc(${componentViewport?.width || "100vw"} - 887px)`}
								y={(componentViewport?.y || 0) + 549}
								{...addPropertyOverrides(
									{
										Ohmrc2dBG: {
											height: (componentViewport?.height || 480) - 549,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-hn8z6c-container"}
									layoutDependency={layoutDependency}
									layoutId={"t5CWTO3E5-container"}
									nodeId={"t5CWTO3E5"}
									rendersWithMotion={true}
									scopeId={"yvjzglA30"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "t5CWTO3E5",
										layoutId: "t5CWTO3E5",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed() && (
							<ComponentViewportProvider
								height={(componentViewport?.height || 620) - 444}
								width={`calc(${componentViewport?.width || "100vw"} - 441px)`}
								y={(componentViewport?.y || 0) + 444}
								{...addPropertyOverrides(
									{
										Ohmrc2dBG: {
											height: (componentViewport?.height || 480) - 444,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1dvt3fk-container"}
									layoutDependency={layoutDependency}
									layoutId={"HkSTru_qS-container"}
									nodeId={"HkSTru_qS"}
									rendersWithMotion={true}
									scopeId={"yvjzglA30"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "HkSTru_qS",
										layoutId: "HkSTru_qS",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FW3Gp.framer-14xo40i, .framer-FW3Gp .framer-14xo40i { display: block; }",
	".framer-FW3Gp.framer-1n6h0kc { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 120px 30px 120px 30px; position: relative; width: 1200px; }",
	".framer-FW3Gp .framer-muuk97 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: flex-start; max-width: 900px; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 5; }",
	".framer-FW3Gp .framer-ybd4wy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-FW3Gp .framer-4shon { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 304px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-FW3Gp .framer-1ltz9qh-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-FW3Gp .framer-kataef { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-FW3Gp .framer-nw4itf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-FW3Gp .framer-fgt1kh, .framer-FW3Gp .framer-1aorf2w, .framer-FW3Gp .framer-1johy5b { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-FW3Gp .framer-cqapl5, .framer-FW3Gp .framer-1q53fdo, .framer-FW3Gp .framer-1572t0z, .framer-FW3Gp .framer-l8hnvp { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-FW3Gp .framer-1t7vfb4, .framer-FW3Gp .framer-89ob94, .framer-FW3Gp .framer-4u608f { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-FW3Gp .framer-1bunktm, .framer-FW3Gp .framer-12zpnsk, .framer-FW3Gp .framer-wy8061, .framer-FW3Gp .framer-1cqizg0, .framer-FW3Gp .framer-1lkgzsn, .framer-FW3Gp .framer-1bg9ieq, .framer-FW3Gp .framer-apz9ot, .framer-FW3Gp .framer-1w3haan, .framer-FW3Gp .framer-jgpixt, .framer-FW3Gp .framer-1hllug0, .framer-FW3Gp .framer-jg0ngk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-FW3Gp .framer-13el9e3, .framer-FW3Gp .framer-mcjkyb, .framer-FW3Gp .framer-1i1dg0n, .framer-FW3Gp .framer-17aag3j, .framer-FW3Gp .framer-1519vjw, .framer-FW3Gp .framer-bx580r, .framer-FW3Gp .framer-1k5hj4k, .framer-FW3Gp .framer-3pdgpu, .framer-FW3Gp .framer-b2be00, .framer-FW3Gp .framer-1e0e174, .framer-FW3Gp .framer-1yg5yq4 { --framer-custom-cursors: pointer; flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }",
	".framer-FW3Gp .framer-144kjuc, .framer-FW3Gp .framer-mya5w5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 31px; min-width: 48px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-FW3Gp .framer-nwiqs9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-FW3Gp .framer-xm8c26 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-FW3Gp .framer-qii2ii-container { bottom: 27px; flex: none; height: 31px; left: 130px; position: absolute; width: 70px; z-index: 1; }",
	".framer-FW3Gp .framer-hn8z6c-container { bottom: 0px; flex: none; left: 507px; position: absolute; right: 380px; top: 549px; z-index: 1; }",
	".framer-FW3Gp .framer-1dvt3fk-container { bottom: 0px; flex: none; left: 129px; position: absolute; right: 312px; top: 444px; z-index: 1; }",
	".framer-FW3Gp.framer-v-rjflw2.framer-1n6h0kc { padding: 80px 30px 80px 30px; width: 810px; }",
	".framer-FW3Gp.framer-v-rjflw2 .framer-muuk97 { gap: 60px; max-width: 100%; }",
	".framer-FW3Gp.framer-v-rjflw2 .framer-nw4itf { gap: 30px; }",
	".framer-FW3Gp.framer-v-ufa31p.framer-1n6h0kc { padding: 80px 20px 80px 20px; width: 390px; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-muuk97 { align-content: center; align-items: center; gap: 40px; justify-content: center; max-width: 100%; order: 0; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-ybd4wy { align-content: center; align-items: center; flex-direction: column; gap: 40px; justify-content: center; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-4shon { align-content: center; align-items: center; flex: none; width: 100%; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-nw4itf { align-content: center; align-items: center; flex-direction: column; gap: 40px; justify-content: center; width: 100%; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-fgt1kh { align-content: center; align-items: center; gap: 20px; justify-content: center; order: 0; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-1t7vfb4, .framer-FW3Gp.framer-v-ufa31p .framer-89ob94, .framer-FW3Gp.framer-v-ufa31p .framer-4u608f { align-content: center; align-items: center; justify-content: center; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-1aorf2w { align-content: center; align-items: center; gap: 20px; justify-content: center; order: 1; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-1johy5b { align-content: center; align-items: center; gap: 20px; justify-content: center; order: 2; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-nwiqs9 { gap: 40px; justify-content: center; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-xm8c26 { flex-direction: column; order: 0; }",
	".framer-FW3Gp.framer-v-ufa31p .framer-qii2ii-container { order: 1; }",
	...css,
	...css2,
	...css3,
	'.framer-FW3Gp[data-border="true"]::after, .framer-FW3Gp [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FrameryvjzglA30 = withCSS(Component, css4, "framer-FW3Gp");
var stdin_default4 = FrameryvjzglA30;
FrameryvjzglA30.displayName = "Footer";
FrameryvjzglA30.defaultProps = {
	height: 620,
	width: 1200,
};
addPropertyControls(FrameryvjzglA30, {
	variant: {
		options: ["C9ZJFndku", "Ohmrc2dBG", "GC4oZv7lw"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameryvjzglA30,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...LogoFonts,
		...ParticlesFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FrameryvjzglA30.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default3, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GC4oZv7lw",
	md: "Ohmrc2dBG",
	xl: "C9ZJFndku",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var footer_default = ComponentWithRoot;
export { footer_default as default };
