// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Call Card V1' | 'Call Card V2' | 'Call Card v3' // Variant
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-54CILDJG.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-5A4PSNXZ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-QAKPHGHA.js";
import "./chunks/chunk-NS43VYZ6.js";
import { stdin_default } from "./chunks/chunk-XRQ2RYSH.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-YY62L3WU.js";
import "./chunks/chunk-VU34HTVO.js";
import "./chunks/chunk-MM5BHUY4.js";
import "./chunks/chunk-NULYBL27.js";
import { className, css, fonts } from "./chunks/chunk-3BOD4WL3.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:intro-call-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8CWx5faEqEOgNVdt8GyN/6HauYM2OODRzhn4z9ewY/VX0GhcflH.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/bSG2fUXcc43766cbIglD/Ticker.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	Children,
	useLayoutEffect,
	useEffect,
	useState,
	useRef,
	useMemo,
	useCallback,
	cloneElement,
} from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import {
	useReducedMotion,
	LayoutGroup,
	useInView,
	useMotionValue,
	useTransform,
	motion,
	frame,
} from "unframer";
import { resize } from "@motionone/dom";
var MAX_DUPLICATED_ITEMS = 100;
var directionTransformers = {
	left: (offset) => `translateX(-${offset}px)`,
	right: (offset) => `translateX(${offset}px)`,
	top: (offset) => `translateY(-${offset}px)`,
	bottom: (offset) => `translateY(${offset}px)`,
};
function Ticker(props) {
	let {
		slots = [],
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		speed,
		hoverFactor,
		direction,
		alignment,
		sizingOptions,
		fadeOptions,
		style,
	} = props;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const { widthType, heightType } = sizingOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const currentTarget = RenderTarget.current();
	const isCanvas =
		currentTarget === RenderTarget.canvas ||
		currentTarget === RenderTarget.export;
	const filteredSlots = slots.filter(Boolean);
	const numChildren = Children.count(filteredSlots);
	const hasChildren = numChildren > 0;
	if (direction === true) {
		direction = "left";
	}
	const isHorizontal = direction === "left" || direction === "right";
	const offset = useMotionValue(0);
	const transformer = directionTransformers[direction];
	const transform = useTransform(offset, transformer);
	const parentRef = useRef(null);
	const childrenRef = useMemo(() => {
		return [
			{
				current: null,
			},
			{
				current: null,
			},
		];
	}, []);
	const [size, setSize] = useState({
		parent: null,
		children: null,
	});
	let clonedChildren = null;
	let dupedChildren = [];
	let duplicateBy = 0;
	let opacity = 0;
	if (isCanvas) {
		duplicateBy = numChildren ? Math.floor(10 / numChildren) : 0;
		opacity = 1;
	}
	if (!isCanvas && hasChildren && size.parent) {
		duplicateBy = Math.round((size.parent / size.children) * 2) + 1;
		duplicateBy = Math.min(duplicateBy, MAX_DUPLICATED_ITEMS);
		opacity = 1;
	}
	const measure = useCallback(() => {
		if (hasChildren && parentRef.current) {
			const parentLength = isHorizontal
				? parentRef.current.offsetWidth
				: parentRef.current.offsetHeight;
			const start = childrenRef[0].current
				? isHorizontal
					? childrenRef[0].current.offsetLeft
					: childrenRef[0].current.offsetTop
				: 0;
			const end = childrenRef[1].current
				? isHorizontal
					? childrenRef[1].current.offsetLeft +
						childrenRef[1].current.offsetWidth
					: childrenRef[1].current.offsetTop +
						childrenRef[1].current.offsetHeight
				: 0;
			const childrenLength = end - start + gap;
			setSize({
				parent: parentLength,
				children: childrenLength,
			});
		}
	}, []);
	const childrenStyles = isCanvas
		? {
				contentVisibility: "auto",
			}
		: {};
	if (hasChildren) {
		if (!isCanvas) {
			let initialResize = useRef(true);
			useLayoutEffect(() => {
				frame.read(measure, false, true);
				return resize(parentRef.current, ({ contentSize }) => {
					if (
						!initialResize.current &&
						(contentSize.width || contentSize.height)
					) {
						frame.read(measure, false, true);
					}
					initialResize.current = false;
				});
			}, []);
		}
		clonedChildren = Children.map(filteredSlots, (child, index) => {
			let ref;
			if (index === 0) {
				ref = childrenRef[0];
			}
			if (index === filteredSlots.length - 1) {
				ref = childrenRef[1];
			}
			const size2 = {
				width: widthType ? child.props?.width : "100%",
				height: heightType ? child.props?.height : "100%",
			};
			return (
				<LayoutGroup inherit={"id"}>
					<li ref={ref} style={size2}>
						{
							/* @__PURE__ */ cloneElement(
								child,
								{
									style: {
										...child.props?.style,
										...size2,
										flexShrink: 0,
										...childrenStyles,
									},
									layoutId: child.props.layoutId
										? child.props.layoutId + "-original-" + index
										: void 0,
								},
								child.props?.children,
							)
						}
					</li>
				</LayoutGroup>
			);
		});
	}
	const isInView = isCanvas ? true : useInView(parentRef);
	if (!isCanvas) {
		for (let i = 0; i < duplicateBy; i++) {
			dupedChildren = dupedChildren.concat(
				Children.map(filteredSlots, (child, childIndex) => {
					const size2 = {
						width: widthType ? child.props?.width : "100%",
						height: heightType ? child.props?.height : "100%",
						willChange: !isInView ? void 0 : "transform",
					};
					return (
						<LayoutGroup inherit={"id"}>
							<li style={size2} aria-hidden={true}>
								{
									/* @__PURE__ */ cloneElement(
										child,
										{
											key: i + " " + childIndex,
											style: {
												...child.props?.style,
												width: widthType ? child.props?.width : "100%",
												height: heightType ? child.props?.height : "100%",
												flexShrink: 0,
												...childrenStyles,
											},
											layoutId: child.props.layoutId
												? child.props.layoutId + "-dupe-" + i
												: void 0,
										},
										child.props?.children,
									)
								}
							</li>
						</LayoutGroup>
					);
				}),
			);
		}
	}
	const animateToValue =
		size.children + size.children * Math.round(size.parent / size.children);
	const initialTime = useRef(null);
	const prevTime = useRef(null);
	const xOrY = useRef(0);
	const isHover = useRef(false);
	const isReducedMotion = useReducedMotion();
	const listRef = useRef(null);
	const animationRef = useRef(null);
	if (!isCanvas) {
		useEffect(() => {
			if (isReducedMotion || !animateToValue || !speed) {
				return;
			}
			animationRef.current = listRef.current.animate(
				{
					transform: [transformer(0), transformer(animateToValue)],
				},
				{
					duration: (Math.abs(animateToValue) / speed) * 1e3,
					iterations: Infinity,
					easing: "linear",
				},
			);
			return () => animationRef.current.cancel();
		}, [hoverFactor, animateToValue, speed]);
		const playOrPause = useCallback(() => {
			if (!animationRef.current) return;
			const hidden = document.hidden;
			if (isInView && !hidden && animationRef.current.playState === "paused") {
				animationRef.current.play();
			} else if (
				(!isInView || hidden) &&
				animationRef.current.playState === "running"
			) {
				animationRef.current.pause();
			}
		}, [isInView]);
		useEffect(() => {
			playOrPause();
		}, [isInView, hoverFactor, animateToValue, speed]);
		useEffect(() => {
			document.addEventListener("visibilitychange", playOrPause);
			return () => {
				document.removeEventListener("visibilitychange", playOrPause);
			};
		}, [playOrPause]);
	}
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	if (!hasChildren) {
		return (
			<section style={placeholderStyles}>
				<div style={emojiStyles}>{"\u2728"}</div>
				<p style={titleStyles}>{"Connect to Content"}</p>
				<p style={subtitleStyles}>
					{"Add layers or components to infinitely loop on your page."}
				</p>
			</section>
		);
	}
	return (
		<section
			style={{
				...containerStyle,
				opacity,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				overflow: overflow ? "visible" : "hidden",
				padding: paddingValue,
			}}
			ref={parentRef}
		>
			<motion.ul
				ref={listRef}
				style={{
					...containerStyle,
					gap,
					top:
						direction === "bottom" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					left:
						direction === "right" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					placeItems: alignment,
					position: "relative",
					flexDirection: isHorizontal ? "row" : "column",
					...style,
					willChange: isCanvas || !isInView ? "auto" : "transform",
					transform: transformer(0),
				}}
				onMouseEnter={() => {
					isHover.current = true;
					if (animationRef.current) {
						animationRef.current.playbackRate = hoverFactor;
					}
				}}
				onMouseLeave={() => {
					isHover.current = false;
					if (animationRef.current) {
						animationRef.current.playbackRate = 1;
					}
				}}
			>
				{clonedChildren}
				{dupedChildren}
			</motion.ul>
		</section>
	);
}
Ticker.defaultProps = {
	gap: 10,
	padding: 10,
	sizingOptions: {
		widthType: true,
		heightType: true,
	},
	fadeOptions: {
		fadeContent: true,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	direction: true,
};
addPropertyControls(Ticker, {
	slots: {
		type: ControlType.Array,
		title: "Children",
		control: {
			type: ControlType.ComponentInstance,
		},
	},
	speed: {
		type: ControlType.Number,
		title: "Speed",
		min: 0,
		max: 1e3,
		defaultValue: 100,
		unit: "%",
		displayStepper: true,
		step: 5,
	},
	direction: {
		type: ControlType.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		defaultValue: "left",
		displaySegmentedControl: true,
	},
	alignment: {
		type: ControlType.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
	},
	padding: {
		title: "Padding",
		type: ControlType.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	sizingOptions: {
		type: ControlType.Object,
		title: "Sizing",
		controls: {
			widthType: {
				type: ControlType.Boolean,
				title: "Width",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
			heightType: {
				type: ControlType.Boolean,
				title: "Height",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
		},
	},
	fadeOptions: {
		type: ControlType.Object,
		title: "Clipping",
		controls: {
			fadeContent: {
				type: ControlType.Boolean,
				title: "Fade",
				defaultValue: true,
			},
			overflow: {
				type: ControlType.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
	hoverFactor: {
		type: ControlType.Number,
		title: "Hover",
		min: 0,
		max: 1,
		unit: "x",
		defaultValue: 1,
		step: 0.1,
		displayStepper: true,
		description: "Slows down the speed while you are hovering.",
	},
});
var containerStyle = {
	display: "flex",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
	padding: "20px 20px 30px 20px",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 150,
	lineHeight: 1.5,
	textAlign: "center",
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);
var isValidNumber = (value) => typeof value === "number" && !isNaN(value);

// /:https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import * as React from "react";
import { motion as motion2, LayoutGroup as LayoutGroup2 } from "unframer";
import {
	Image as Image1,
	addFonts,
	withCSS,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	useAddVariantProps,
	useVariantState,
	Stack,
} from "unframer";

// /:https://framerusercontent.com/modules/e6iTGMqgmkFJvN0mYhkr/KWXeR1JD2kMVZ95etjSs/useConstant.js
import { useRef as useRef2 } from "react";
function useConstant(init) {
	const ref = useRef2(null);
	if (ref.current === null) {
		ref.current = init();
	}
	return ref.current;
}

// /:https://framerusercontent.com/modules/9v9kZvfG4dVIvUGXWTUG/0XmuCxJqtgJLC9OHPU64/randomID.js
var BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
function randomID(length = 5) {
	return Array(length)
		.fill(0)
		.map(() => BASE62[Math.floor(Math.random() * BASE62.length)])
		.join("");
}
function useRandomID(length = 5) {
	return useConstant(() => randomID(length));
}

// /:https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js
var cycleOrder = [
	"AD1uRb789",
	"t6uYX0tBZ",
	"AnI2DvQZf",
	"JG7MxGgTY",
	"snFARdAmz",
	"Nz_Z2NTH0",
	"cHv8JY9g7",
	"tR7FlThNE",
	"bg0lLngd2",
	"FKNQjSL73",
	"UozSdcuUY",
	"EgLxQrxHD",
	"vol5AdrV3",
	"rbMcqs1eA",
	"OY_j7HdJV",
	"mcvPgNUgN",
	"Jj_gJ6raO",
	"UYFenO8zH",
	"RpMB9X2cU",
	"tExww8aRk",
	"anaA6RL0b",
	"y8osi5SA0",
	"v2n6jd8d8",
	"vrPxXX3Sq",
	"YC5psLXzO",
	"wQ9whLvFH",
	"hUi9TraZo",
	"ji0e3Gqv5",
	"nMHdUM1t6",
	"Stnp3oRU4",
	"TxmZTsvXB",
	"bNhqIdQoj",
	"OYkCSZPL0",
	"bOMpuyzc_",
	"NqCoJY2pH",
];
var variantClassNames = {
	AD1uRb789: "framer-v-rqhbs3",
	t6uYX0tBZ: "framer-v-ina8tq",
	AnI2DvQZf: "framer-v-lwbc2o",
	JG7MxGgTY: "framer-v-vqryag",
	snFARdAmz: "framer-v-kwp1i3",
	Nz_Z2NTH0: "framer-v-1h8ejmh",
	cHv8JY9g7: "framer-v-c75qsa",
	tR7FlThNE: "framer-v-1ftwjq5",
	bg0lLngd2: "framer-v-osfy8l",
	FKNQjSL73: "framer-v-5qhg5s",
	UozSdcuUY: "framer-v-5ats54",
	EgLxQrxHD: "framer-v-z5mnn6",
	vol5AdrV3: "framer-v-6xnqop",
	rbMcqs1eA: "framer-v-xmx6ye",
	OY_j7HdJV: "framer-v-a1v8wx",
	mcvPgNUgN: "framer-v-1oj0oue",
	Jj_gJ6raO: "framer-v-19e1lqz",
	UYFenO8zH: "framer-v-16en86l",
	RpMB9X2cU: "framer-v-1vzsblg",
	tExww8aRk: "framer-v-1kgllbw",
	anaA6RL0b: "framer-v-zia1yx",
	y8osi5SA0: "framer-v-9mi1m7",
	v2n6jd8d8: "framer-v-zgdwlg",
	vrPxXX3Sq: "framer-v-1dgnypb",
	YC5psLXzO: "framer-v-rum36c",
	wQ9whLvFH: "framer-v-1u5c2u8",
	hUi9TraZo: "framer-v-1dt8e1w",
	ji0e3Gqv5: "framer-v-1rkl824",
	nMHdUM1t6: "framer-v-17d51pb",
	Stnp3oRU4: "framer-v-158neyh",
	TxmZTsvXB: "framer-v-1atb71u",
	bNhqIdQoj: "framer-v-1x8h963",
	OYkCSZPL0: "framer-v-hblyuj",
	bOMpuyzc_: "framer-v-cra8ie",
	NqCoJY2pH: "framer-v-1sz721s",
};
var humanReadableVariantMap = {
	Jason: "AD1uRb789",
	Jess: "t6uYX0tBZ",
	Olli: "AnI2DvQZf",
	Myah: "JG7MxGgTY",
	Ammaar: "snFARdAmz",
	Siena: "Nz_Z2NTH0",
	Cheryl: "cHv8JY9g7",
	Aleeza: "tR7FlThNE",
	Elli: "bg0lLngd2",
	Piotr: "FKNQjSL73",
	Ayisha: "UozSdcuUY",
	Nataniel: "EgLxQrxHD",
	Nikita: "vol5AdrV3",
	Tim: "rbMcqs1eA",
	Carley: "OY_j7HdJV",
	Arda: "mcvPgNUgN",
	"Lacey-Mae": "Jj_gJ6raO",
	Bo: "UYFenO8zH",
	Shelbie: "RpMB9X2cU",
	Dillon: "tExww8aRk",
	Selin: "OYkCSZPL0",
	Rhian: "y8osi5SA0",
	Ada: "v2n6jd8d8",
	Lois: "vrPxXX3Sq",
	Maisie: "YC5psLXzO",
	Lori: "wQ9whLvFH",
	Jardel: "hUi9TraZo",
	Jethro: "ji0e3Gqv5",
	Carmen: "nMHdUM1t6",
	Patrik: "Stnp3oRU4",
	Barry: "TxmZTsvXB",
	Alejandro: "bNhqIdQoj",
	Denny: "bOMpuyzc_",
	Becca: "NqCoJY2pH",
};
var transitions = {
	default: {
		type: "spring",
		ease: [0.44, 0, 0.56, 1],
		duration: 0.3,
		delay: 0,
		stiffness: 500,
		damping: 60,
		mass: 1,
	},
};
var Component = /* @__PURE__ */ React.forwardRef(function (
	{
		style,
		className: className5,
		layoutId,
		width,
		height,
		variant: outerVariant = "AD1uRb789",
		background: VurELiPqN = "rgb(255, 219, 222)",
		radius: Z2NuoQS1k = 60,
		rotation: tc_6nmlts = 0,
		...restProps
	},
	ref,
) {
	const outerVariantId = humanReadableVariantMap[outerVariant];
	const variant = outerVariantId || outerVariant;
	const {
		variants,
		baseVariant,
		gestureVariant,
		classNames,
		transition,
		setVariant,
		setGestureState,
	} = useVariantState({
		defaultVariant: "AD1uRb789",
		variant,
		transitions,
		variantClassNames,
		cycleOrder,
	});
	const variantProps = React.useMemo(
		() => ({
			t6uYX0tBZ: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Jess",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/XfjXHJ2H7SzzlzPr1bGFm1T9BpI.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			AnI2DvQZf: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Olli",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/qCpU7HJtiveCC9wTFuh7L4wc8YM.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			JG7MxGgTY: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Myah",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/Q8IGGb6PvVKrjNuovM2HijDWFU.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			snFARdAmz: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Ammaar",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/iGk4x1NJSVgWzFvuQQADJp9I.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			Nz_Z2NTH0: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Siena",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/ikD34vgzaLM6N50MKdcR9HVBnk.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			cHv8JY9g7: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Cheryl",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/mUVPNgOqhd1MFYjLtFtiBwvxfY.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			tR7FlThNE: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Aleeza",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/62fnqd1V6QN3j0vPr4hlpB3HnQ.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			bg0lLngd2: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Elli",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/Vu8TxX7VMCMZDjoliFK7D0nOyX0.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			FKNQjSL73: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Piotr",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/ofIUD8MCjke7Xz8jkh29AWqajJo.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			UozSdcuUY: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Ayisha",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/5nnqp2inSINDktAAWpI7gxJei0w.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			EgLxQrxHD: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Nataniel",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/lKaaStgbmdIe8TfrIkFlKzHazV0.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			vol5AdrV3: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Nikita",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/bpeWvtoxuajqEtlukZhUFt9KM.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			rbMcqs1eA: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Tim",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/GoWNvgKZvVTzmZQKHoh2Ccnk4E.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			OY_j7HdJV: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Carley",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/40ioqcNOrsoBIVnpfGVsXh9jpM.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			mcvPgNUgN: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Arda",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/U8RU6HcYtcK32VUY2uTSF9QTqo.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			Jj_gJ6raO: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Lacey-Mae",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/1OwzdZHx9ElDw1ZAavs6WGWBSw.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			UYFenO8zH: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Bo",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/Tlwk5hINm0ferm6DGDyUoqL6pc.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			RpMB9X2cU: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Shelbie",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/Pm9TTOkN341IYtePLdPGmhG0E.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			tExww8aRk: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Dillon",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/GOsVbTpzcPHfZ9EMcOSPddNS6go.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			anaA6RL0b: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Selin",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/GaxkgrTkzKlxI7B3EJtZp4dabI.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			y8osi5SA0: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Rhian",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/LEd8c4Zf28fU29XZ4c04ImOzs.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			v2n6jd8d8: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Ada",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/3oPVBjvZEnTN9DZf7tUMW54TS2k.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			vrPxXX3Sq: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Lois",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/99qcDQP7xzsxlgXsq47uID7sAm4.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			YC5psLXzO: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Maisie",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/BRu6MhHhp9NjldqU9TTCEAEoGKg.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			wQ9whLvFH: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Lori",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/ebCaegtDakUaQGRtXSYmPR43Q.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			hUi9TraZo: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Jardel",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/B8580pOtLEBrg7wIFp62oXfFQ.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			ji0e3Gqv5: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Jethro",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/szTmT1K4f8nn5CutvLWFlBdt8k.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			nMHdUM1t6: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Carmen",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/e6GZhp0s96FXaIiLYSRyZYZYypo.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			Stnp3oRU4: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Patrik",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/6xGPl1j87mG8XoUzCwRYzEohM8.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			TxmZTsvXB: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Barry",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/mhC7dhzvLcqmUofPcC2BW8vh4.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			bNhqIdQoj: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Alejandro",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/YynUn6LSLWVQia4pOtIxhY77SSA.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			OYkCSZPL0: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Selin",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/u2K6WSbQVKHiOUvOF3auFya79y8.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			bOMpuyzc_: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Denny",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/BJytCbStiWSy9rxpQ0wU6I3SNiI.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
			NqCoJY2pH: {
				AD1uRb789: {
					center: false,
					"data-framer-name": "Becca",
					__contentWrapperStyle: {
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					},
				},
				XGgsiaAin: {
					background: {
						src: new URL(
							"assets/xyIaIR0LhPm1PVVUVrQ7TDGTyA.png",
							"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
						).href,
						pixelWidth: 440,
						pixelHeight: 440,
						intrinsicWidth: 440,
						intrinsicHeight: 440,
						fit: "fill",
					},
					intrinsicWidth: 440,
					intrinsicHeight: 440,
				},
			},
		}),
		[],
	);
	const addVariantProps = useAddVariantProps(
		baseVariant,
		gestureVariant,
		variantProps,
	);
	const defaultLayoutId = useRandomID();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion2.div
				initial={variant}
				animate={variants}
				className={cx("framer-47hmZ", classNames)}
				style={{
					display: "contents",
				}}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
			>
				<Stack
					{...restProps}
					layoutId={"AD1uRb789"}
					className={cx("framer-rqhbs3", className5)}
					style={{
						borderBottomLeftRadius: Z2NuoQS1k,
						borderBottomRightRadius: Z2NuoQS1k,
						borderTopRightRadius: Z2NuoQS1k,
						borderTopLeftRadius: Z2NuoQS1k,
						backgroundColor: VurELiPqN,
						...style,
					}}
					direction={"horizontal"}
					distribution={"center"}
					alignment={"center"}
					gap={10}
					__fromCanvasComponent={true}
					__contentWrapperStyle={{
						width: "100%",
						height: "100%",
						padding: "0px 0px 0px 0px",
					}}
					center={false}
					data-framer-name={"Jason"}
					transition={transition}
					ref={ref}
					{...addVariantProps("AD1uRb789")}
				>
					<Image1
						layoutId={"XGgsiaAin"}
						className={"framer-kj56m6"}
						style={{
							borderBottomLeftRadius: 60,
							borderBottomRightRadius: 60,
							borderTopRightRadius: 60,
							borderTopLeftRadius: 60,
							rotate: tc_6nmlts,
						}}
						background={{
							src: new URL(
								"assets/CPGgYEBeFy4gDXe5dDzh1qjQG1w.png",
								"https://framerusercontent.com/modules/PLP5SWQpFPuFrn7tLf3t/suo2OcdmUu5xmjtBXZ7I/dkRfXNUhM.js",
							).href,
							pixelWidth: 440,
							pixelHeight: 440,
							intrinsicWidth: 440,
							intrinsicHeight: 440,
							fit: "fill",
						}}
						data-framer-name={"Avatar"}
						variants={{
							t6uYX0tBZ: {
								borderBottomLeftRadius: 60,
								borderBottomRightRadius: 60,
								borderTopRightRadius: 60,
								borderTopLeftRadius: 60,
							},
						}}
						transition={transition}
						{...addVariantProps("XGgsiaAin")}
					/>
				</Stack>
			</motion2.div>
		</LayoutGroup2>
	);
});
var css4 = [
	'.framer-47hmZ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none;}',
	".framer-47hmZ .framer-rqhbs3 { position: relative; overflow: hidden; width: 100px; height: 100px; }",
	".framer-47hmZ .framer-kj56m6 { position: relative; overflow: visible; width: 1px; height: 100%; flex: 1 0 0px; }",
	".framer-47hmZ.framer-v-ina8tq .framer-rqhbs3, .framer-47hmZ.framer-v-lwbc2o .framer-rqhbs3, .framer-47hmZ.framer-v-vqryag .framer-rqhbs3, .framer-47hmZ.framer-v-kwp1i3 .framer-rqhbs3, .framer-47hmZ.framer-v-1h8ejmh .framer-rqhbs3, .framer-47hmZ.framer-v-c75qsa .framer-rqhbs3, .framer-47hmZ.framer-v-1ftwjq5 .framer-rqhbs3, .framer-47hmZ.framer-v-osfy8l .framer-rqhbs3, .framer-47hmZ.framer-v-5qhg5s .framer-rqhbs3, .framer-47hmZ.framer-v-5ats54 .framer-rqhbs3, .framer-47hmZ.framer-v-z5mnn6 .framer-rqhbs3, .framer-47hmZ.framer-v-6xnqop .framer-rqhbs3, .framer-47hmZ.framer-v-xmx6ye .framer-rqhbs3, .framer-47hmZ.framer-v-a1v8wx .framer-rqhbs3, .framer-47hmZ.framer-v-1oj0oue .framer-rqhbs3, .framer-47hmZ.framer-v-19e1lqz .framer-rqhbs3, .framer-47hmZ.framer-v-16en86l .framer-rqhbs3, .framer-47hmZ.framer-v-1vzsblg .framer-rqhbs3, .framer-47hmZ.framer-v-1kgllbw .framer-rqhbs3, .framer-47hmZ.framer-v-zia1yx .framer-rqhbs3, .framer-47hmZ.framer-v-9mi1m7 .framer-rqhbs3, .framer-47hmZ.framer-v-zgdwlg .framer-rqhbs3, .framer-47hmZ.framer-v-1dgnypb .framer-rqhbs3, .framer-47hmZ.framer-v-rum36c .framer-rqhbs3, .framer-47hmZ.framer-v-1u5c2u8 .framer-rqhbs3, .framer-47hmZ.framer-v-1dt8e1w .framer-rqhbs3, .framer-47hmZ.framer-v-1rkl824 .framer-rqhbs3, .framer-47hmZ.framer-v-17d51pb .framer-rqhbs3, .framer-47hmZ.framer-v-158neyh .framer-rqhbs3, .framer-47hmZ.framer-v-1atb71u .framer-rqhbs3, .framer-47hmZ.framer-v-1x8h963 .framer-rqhbs3, .framer-47hmZ.framer-v-hblyuj .framer-rqhbs3, .framer-47hmZ.framer-v-cra8ie .framer-rqhbs3, .framer-47hmZ.framer-v-1sz721s .framer-rqhbs3 { width: 100px; height: 100px; }",
	".framer-47hmZ.framer-v-1ftwjq5 .framer-kj56m6, .framer-47hmZ.framer-v-osfy8l .framer-kj56m6 { width: 1px; height: 100%; right: auto; bottom: auto; left: auto; top: auto; flex: 1 0 0px; }",
];
var FramerdkRfXNUhM = withCSS(Component, css4);
var stdin_default4 = FramerdkRfXNUhM;
FramerdkRfXNUhM.displayName = "Memoji";
FramerdkRfXNUhM.defaultProps = {
	width: 100,
	height: 100,
};
addPropertyControls2(FramerdkRfXNUhM, {
	variant: {
		type: ControlType2.Enum,
		title: "Variant",
		options: [
			"AD1uRb789",
			"t6uYX0tBZ",
			"AnI2DvQZf",
			"JG7MxGgTY",
			"snFARdAmz",
			"Nz_Z2NTH0",
			"cHv8JY9g7",
			"tR7FlThNE",
			"bg0lLngd2",
			"FKNQjSL73",
			"UozSdcuUY",
			"EgLxQrxHD",
			"vol5AdrV3",
			"rbMcqs1eA",
			"OY_j7HdJV",
			"mcvPgNUgN",
			"Jj_gJ6raO",
			"UYFenO8zH",
			"RpMB9X2cU",
			"tExww8aRk",
			"anaA6RL0b",
			"y8osi5SA0",
			"v2n6jd8d8",
			"vrPxXX3Sq",
			"YC5psLXzO",
			"wQ9whLvFH",
			"hUi9TraZo",
			"ji0e3Gqv5",
			"nMHdUM1t6",
			"Stnp3oRU4",
			"TxmZTsvXB",
			"bNhqIdQoj",
			"OYkCSZPL0",
			"bOMpuyzc_",
			"NqCoJY2pH",
		],
		optionTitles: [
			"Jason",
			"Jess",
			"Olli",
			"Myah",
			"Ammaar",
			"Siena",
			"Cheryl",
			"Aleeza",
			"Elli",
			"Piotr",
			"Ayisha",
			"Nataniel",
			"Nikita",
			"Tim",
			"Carley",
			"Arda",
			"Lacey-Mae",
			"Bo",
			"Shelbie",
			"Dillon",
			"Selin",
			"Rhian",
			"Ada",
			"Lois",
			"Maisie",
			"Lori",
			"Jardel",
			"Jethro",
			"Carmen",
			"Patrik",
			"Barry",
			"Alejandro",
			"Selin",
			"Denny",
			"Becca",
		],
	},
	VurELiPqN: {
		type: ControlType2.Color,
		title: "Background",
		defaultValue: "rgb(255, 219, 222)",
	},
	Z2NuoQS1k: {
		type: ControlType2.Number,
		title: "Radius",
		defaultValue: 60,
		min: 0,
	},
	tc_6nmlts: {
		type: ControlType2.Number,
		title: "Rotation",
		defaultValue: 0,
		min: -180,
		max: 180,
		unit: "\xB0",
	},
});
addFonts(FramerdkRfXNUhM, []);

// /:https://framerusercontent.com/modules/WSJGNFei4vVAC0msI8cK/7LWQx1UbOXnctDIqSRW4/PtxPTmiY_.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Plus Jakarta Sans-semibold",
	"FS;Plus Jakarta Sans-bold",
	"FS;Plus Jakarta Sans-bold italic",
	"FS;Plus Jakarta Sans-semibold italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/ZLH2B3SFZRQ3US4ZUYG2367OYUMTVTGK/RSOPFK2EORTGBCOBZRY42GDLXFFB4IQW/JZ35FM4UJSKC7X2PM65RH75Q5KLE552S.woff2",
				weight: "600",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/AJVGEOXGB2ALQKAZEK2LDOLCVBCMCOIT/LDEP4R7SNNABDEG433DCQGM2A7YCBHLU/OWABOLGBAKFVLPZ756IYS6EKYKU54K3I.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/57U2OK2BISA74Z4RT4CRD5GR4O3PNVPY/K4TDAPUNBYK24HOCNW4JIOTEXSAE2BEF/GV5XODI2YD2DJA5RVTMJOSDHYESL7IYT.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/DG3FNZZAXTT6HZWYCQT3SK2X2XDKA6XH/KWXXWQ4T72VNT2BQDELHDOCDISYUBIWM/XMNYCZFXUH3EYMLHCQEDXUTZTCNGZHL5.woff2",
				weight: "600",
			},
		],
	},
];
var css5 = [
	'.framer-fGzmz .framer-styles-preset-ca74r1:not(.rich-text-wrapper), .framer-fGzmz .framer-styles-preset-ca74r1.rich-text-wrapper h3 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 36px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 600; --framer-letter-spacing: -1.5px; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, #171717); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-fGzmz .framer-styles-preset-ca74r1:not(.rich-text-wrapper), .framer-fGzmz .framer-styles-preset-ca74r1.rich-text-wrapper h3 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 600; --framer-letter-spacing: -1.5px; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, #171717); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-fGzmz .framer-styles-preset-ca74r1:not(.rich-text-wrapper), .framer-fGzmz .framer-styles-preset-ca74r1.rich-text-wrapper h3 { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 23px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 600; --framer-letter-spacing: -1.5px; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: left; --framer-text-color: var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, #171717); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className4 = "framer-fGzmz";

// /:https://framerusercontent.com/modules/8CWx5faEqEOgNVdt8GyN/6HauYM2OODRzhn4z9ewY/VX0GhcflH.js
var MemojiFonts = getFonts(stdin_default4);
var ButtonButtonFonts = getFonts(stdin_default2);
var FeatureCardFonts = getFonts(stdin_default3);
var TickerFonts = getFonts(Ticker);
var ParticlesFonts = getFonts(stdin_default);
var cycleOrder2 = ["OIPq05f1b", "ycU0N2u_N", "ZzIspNLGr"];
var serializationHash = "framer-RuI3j";
var variantClassNames2 = {
	OIPq05f1b: "framer-v-zmxhiq",
	ycU0N2u_N: "framer-v-8wevzx",
	ZzIspNLGr: "framer-v-1pdw1r5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap2 = {
	"Call Card V1": "OIPq05f1b",
	"Call Card V2": "ycU0N2u_N",
	"Call Card v3": "ZzIspNLGr",
};
var Variants = motion3.create(React2.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "OIPq05f1b",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "OIPq05f1b",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className4, className2, className, className3];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["ycU0N2u_N", "ZzIspNLGr"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["ycU0N2u_N", "ZzIspNLGr"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-zmxhiq",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Call Card V1"}
						layoutDependency={layoutDependency}
						layoutId={"OIPq05f1b"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "dashed",
							"--border-top-width": "1px",
							...style,
						}}
						variants={{
							ycU0N2u_N: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
							ZzIspNLGr: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
						}}
						{...addPropertyOverrides(
							{
								ycU0N2u_N: {
									"data-framer-name": "Call Card V2",
								},
								ZzIspNLGr: {
									"data-framer-name": "Call Card v3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-z0my0w"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"gFWTINgsl"}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
							variants={{
								ycU0N2u_N: {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "dashed",
									"--border-top-width": "1px",
								},
								ZzIspNLGr: {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "dashed",
									"--border-top-width": "1px",
								},
							}}
							{...addPropertyOverrides(
								{
									ycU0N2u_N: {
										"data-border": true,
									},
									ZzIspNLGr: {
										"data-border": true,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion3.div
								className={"framer-tomgoz"}
								data-framer-name={"Card Title "}
								layoutDependency={layoutDependency}
								layoutId={"S6c3S9S2U"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-fm8xi2-container"}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"aPwJdx_5L-container"}
										nodeId={"aPwJdx_5L"}
										rendersWithMotion={true}
										scopeId={"VX0GhcflH"}
									>
										{_jsx3(stdin_default4, {
											background:
												"var(--token-7fe55cf6-3aeb-4bf8-bddc-29b461b9b1df, rgb(252, 252, 252))",
											height: "100%",
											id: "aPwJdx_5L",
											layoutId: "aPwJdx_5L",
											radius: 60,
											rotation: 0,
											style: {
												height: "100%",
												width: "100%",
											},
											variant: matchVariant("anaA6RL0b"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1qh6i3u"}
									data-framer-name={"Basic Plan"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"F05O4gGQO"}
									style={{
										"--extracted-a0htzi":
											"var(--token-7fe55cf6-3aeb-4bf8-bddc-29b461b9b1df, rgb(252, 252, 252))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											ycU0N2u_N: {
												children: (
													<React2.Fragment>
														<motion3.h3
															className={"framer-styles-preset-ca74r1"}
															data-styles-preset={"PtxPTmiY_"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-7fe55cf6-3aeb-4bf8-bddc-29b461b9b1df, rgb(252, 252, 252)))",
															}}
														>
															{"Book a 15-min intro call"}
														</motion3.h3>
													</React2.Fragment>
												),
											},
											ZzIspNLGr: {
												children: (
													<React2.Fragment>
														<motion3.h3
															className={"framer-styles-preset-ca74r1"}
															data-styles-preset={"PtxPTmiY_"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-a0htzi, var(--token-7fe55cf6-3aeb-4bf8-bddc-29b461b9b1df, rgb(252, 252, 252)))",
															}}
														>
															{"Book a 15-min intro call"}
														</motion3.h3>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion3.h3
											className={"framer-styles-preset-ca74r1"}
											data-styles-preset={"PtxPTmiY_"}
											style={{
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-7fe55cf6-3aeb-4bf8-bddc-29b461b9b1df, rgb(252, 252, 252)))",
											}}
										>
											{"Book a 15-min intro call"}
										</motion3.h3>
									</React2.Fragment>
								</RichText>
								<ComponentViewportProvider
									height={60}
									y={(componentViewport?.y || 0) + 0 + 0 + 25 + 0 + 0 + 183.2}
									{...addPropertyOverrides(
										{
											ycU0N2u_N: {
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													20 +
													0 +
													0 +
													159.2,
											},
											ZzIspNLGr: {
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													20 +
													0 +
													0 +
													159.2,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1rtquns-container"}
										layoutDependency={layoutDependency}
										layoutId={"O2mOAHnMz-container"}
										nodeId={"O2mOAHnMz"}
										rendersWithMotion={true}
										scopeId={"VX0GhcflH"}
									>
										{_jsx3(stdin_default2, {
											height: "100%",
											id: "O2mOAHnMz",
											layoutId: "O2mOAHnMz",
											QPXgBsk7h: "Get Started",
											variant: matchVariant("t2ANagDuC"),
											width: "100%",
											...addPropertyOverrides(
												{
													ycU0N2u_N: {
														variant: matchVariant("XS4Fn3AGp"),
													},
													ZzIspNLGr: {
														variant: matchVariant("httELeRMt"),
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion3.div>
							<motion3.div
								className={"framer-1eu1ky6"}
								data-framer-name={"Email"}
								layoutDependency={layoutDependency}
								layoutId={"LrMedM6TH"}
							>
								<motion3.div
									className={"framer-fy7bhx"}
									layoutDependency={layoutDependency}
									layoutId={"diShATbGw"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-7ls43c"}
										data-framer-name={"Txt"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"bfm1qyyky"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												ycU0N2u_N: {
													children: (
														<React2.Fragment>
															<motion3.p
																className={"framer-styles-preset-71c1l6"}
																data-styles-preset={"r7igaR65_"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
																}}
															>
																{"Prefer to Email?"}
															</motion3.p>
														</React2.Fragment>
													),
												},
												ZzIspNLGr: {
													children: (
														<React2.Fragment>
															<motion3.p
																className={"framer-styles-preset-71c1l6"}
																data-styles-preset={"r7igaR65_"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
																}}
															>
																{"Prefer to Email?"}
															</motion3.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion3.p
												className={"framer-styles-preset-6bhg54"}
												data-styles-preset={"Hjw3T0c61"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
												}}
											>
												{"Prefer to Email?"}
											</motion3.p>
										</React2.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-14ebi0u"}
										data-framer-name={"Mail"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"NnfjxALyz"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
											opacity: 0.7,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												ycU0N2u_N: {
													children: (
														<React2.Fragment>
															<motion3.p
																className={"framer-styles-preset-71c1l6"}
																data-styles-preset={"r7igaR65_"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
																}}
															>
																<Link
																	href={"mailto:ajoy.sayhello@gmail.com"}
																	motionChild={true}
																	nodeId={"NnfjxALyz"}
																	openInNewTab={true}
																	relValues={[]}
																	scopeId={"VX0GhcflH"}
																	smoothScroll={false}
																>
																	<motion3.a
																		className={"framer-styles-preset-1ilkga"}
																		data-styles-preset={"NrYndXeRn"}
																	>
																		{"ajoy.sayhello@gmail.com"}
																	</motion3.a>
																</Link>
															</motion3.p>
														</React2.Fragment>
													),
												},
												ZzIspNLGr: {
													children: (
														<React2.Fragment>
															<motion3.p
																className={"framer-styles-preset-71c1l6"}
																data-styles-preset={"r7igaR65_"}
																dir={"auto"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
																}}
															>
																<Link
																	href={"mailto:framio.info@gmail.com"}
																	motionChild={true}
																	nodeId={"NnfjxALyz"}
																	openInNewTab={true}
																	relValues={[]}
																	scopeId={"VX0GhcflH"}
																	smoothScroll={false}
																>
																	<motion3.a
																		className={"framer-styles-preset-1ilkga"}
																		data-styles-preset={"NrYndXeRn"}
																	>
																		{"framio.info@gmail.com"}
																	</motion3.a>
																</Link>
															</motion3.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion3.p
												className={"framer-styles-preset-6bhg54"}
												data-styles-preset={"Hjw3T0c61"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
												}}
											>
												<Link
													href={"mailto:ajoy.sayhello@gmail.com"}
													motionChild={true}
													nodeId={"NnfjxALyz"}
													openInNewTab={true}
													relValues={[]}
													scopeId={"VX0GhcflH"}
													smoothScroll={false}
												>
													<motion3.a
														className={"framer-styles-preset-1ilkga"}
														data-styles-preset={"NrYndXeRn"}
													>
														{"ajoy.sayhello@gmail.com"}
													</motion3.a>
												</Link>
											</motion3.p>
										</React2.Fragment>
									</RichText>
								</motion3.div>
								{isDisplayed() && (
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-rpv4lv-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"vGdhuSKIQ-container"}
											nodeId={"vGdhuSKIQ"}
											rendersWithMotion={true}
											scopeId={"VX0GhcflH"}
										>
											<Ticker
												alignment={"center"}
												direction={"left"}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: true,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={10}
												height={"100%"}
												hoverFactor={1}
												id={"vGdhuSKIQ"}
												layoutId={"vGdhuSKIQ"}
												padding={0}
												paddingBottom={0}
												paddingLeft={0}
												paddingPerSide={false}
												paddingRight={0}
												paddingTop={0}
												sizingOptions={{
													heightType: true,
													widthType: true,
												}}
												slots={[
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-16mxddh-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"O2aAIA1Zw-container"}
															nodeId={"O2aAIA1Zw"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "O2aAIA1Zw",
																layoutId: "O2aAIA1Zw",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Business Inquiry",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-1k25toi-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"VvijNpW4U-container"}
															nodeId={"VvijNpW4U"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "VvijNpW4U",
																layoutId: "VvijNpW4U",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Want My Videos Edited",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-y8jvpe-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"YvCqA7Q3u-container"}
															nodeId={"YvCqA7Q3u"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "YvCqA7Q3u",
																layoutId: "YvCqA7Q3u",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Send Me Samples",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-gxrqy1-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"UDckvdSVb-container"}
															nodeId={"UDckvdSVb"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "UDckvdSVb",
																layoutId: "UDckvdSVb",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Long-Term Collaboration",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
												]}
												speed={30}
												style={{
													height: "100%",
													width: "100%",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
								{isDisplayed1() && (
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-eqwbjl-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"XKVBi2ehX-container"}
											nodeId={"XKVBi2ehX"}
											rendersWithMotion={true}
											scopeId={"VX0GhcflH"}
										>
											<Ticker
												alignment={"center"}
												direction={"left"}
												fadeOptions={{
													fadeAlpha: 0,
													fadeContent: true,
													fadeInset: 0,
													fadeWidth: 25,
													overflow: false,
												}}
												gap={5}
												height={"100%"}
												hoverFactor={1}
												id={"XKVBi2ehX"}
												layoutId={"XKVBi2ehX"}
												padding={0}
												paddingBottom={0}
												paddingLeft={0}
												paddingPerSide={false}
												paddingRight={0}
												paddingTop={0}
												sizingOptions={{
													heightType: true,
													widthType: true,
												}}
												slots={[
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-16mxddh-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"O2aAIA1Zw-container"}
															nodeId={"O2aAIA1Zw"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "O2aAIA1Zw",
																layoutId: "O2aAIA1Zw",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Business Inquiry",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-1k25toi-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"VvijNpW4U-container"}
															nodeId={"VvijNpW4U"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "VvijNpW4U",
																layoutId: "VvijNpW4U",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Want My Videos Edited",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-y8jvpe-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"YvCqA7Q3u-container"}
															nodeId={"YvCqA7Q3u"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "YvCqA7Q3u",
																layoutId: "YvCqA7Q3u",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Send Me Samples",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
													<ComponentViewportProvider height={48}>
														<SmartComponentScopedContainer
															className={"framer-gxrqy1-container"}
															inComponentSlot={true}
															layoutDependency={layoutDependency}
															layoutId={"UDckvdSVb-container"}
															nodeId={"UDckvdSVb"}
															rendersWithMotion={true}
															scopeId={"VX0GhcflH"}
														>
															{_jsx3(stdin_default3, {
																height: "100%",
																id: "UDckvdSVb",
																layoutId: "UDckvdSVb",
																variant: matchVariant("kRX8fkKcU"),
																width: "100%",
																YRK4OykBe: "Long-Term Collaboration",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>,
												]}
												speed={30}
												style={{
													height: "100%",
													width: "100%",
												}}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</motion3.div>
						</motion3.div>
						<ComponentViewportProvider
							height={82}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 492) -
								82
							}
							{...addPropertyOverrides(
								{
									ycU0N2u_N: {
										y:
											(componentViewport?.y || 0) +
											(componentViewport?.height || 452) -
											82,
									},
									ZzIspNLGr: {
										y:
											(componentViewport?.y || 0) +
											(componentViewport?.height || 452) -
											82,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-iuw47s-container"}
								layoutDependency={layoutDependency}
								layoutId={"K9S7YB0f3-container"}
								nodeId={"K9S7YB0f3"}
								rendersWithMotion={true}
								scopeId={"VX0GhcflH"}
							>
								{_jsx3(stdin_default, {
									height: "100%",
									id: "K9S7YB0f3",
									layoutId: "K9S7YB0f3",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion3.div>
				</Transition>
			</Variants>
		</LayoutGroup3>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RuI3j.framer-1tteikz, .framer-RuI3j .framer-1tteikz { display: block; }",
	".framer-RuI3j.framer-zmxhiq { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 380px; }",
	".framer-RuI3j .framer-z0my0w { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 25px 25px 20px 25px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-RuI3j .framer-tomgoz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 350px; z-index: 5; }",
	".framer-RuI3j .framer-fm8xi2-container { flex: none; height: 100px; position: relative; width: 100px; }",
	".framer-RuI3j .framer-1qh6i3u, .framer-RuI3j .framer-7ls43c, .framer-RuI3j .framer-14ebi0u { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-RuI3j .framer-1rtquns-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-RuI3j .framer-1eu1ky6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 350px; z-index: 5; }",
	".framer-RuI3j .framer-fy7bhx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-RuI3j .framer-rpv4lv-container, .framer-RuI3j .framer-eqwbjl-container { flex: none; height: 52px; position: relative; width: 100%; }",
	".framer-RuI3j .framer-16mxddh-container, .framer-RuI3j .framer-1k25toi-container, .framer-RuI3j .framer-y8jvpe-container, .framer-RuI3j .framer-gxrqy1-container { height: auto; position: relative; width: auto; }",
	".framer-RuI3j .framer-iuw47s-container { bottom: 0px; flex: none; height: 82px; left: 0px; position: absolute; right: 0px; z-index: 1; }",
	".framer-RuI3j.framer-v-8wevzx.framer-zmxhiq, .framer-RuI3j.framer-v-1pdw1r5.framer-zmxhiq { width: 390px; }",
	".framer-RuI3j.framer-v-8wevzx .framer-z0my0w, .framer-RuI3j.framer-v-1pdw1r5 .framer-z0my0w { align-content: center; align-items: center; gap: 30px; padding: 20px 15px 20px 15px; width: 100%; }",
	".framer-RuI3j.framer-v-8wevzx .framer-tomgoz, .framer-RuI3j.framer-v-1pdw1r5 .framer-tomgoz { align-content: center; align-items: center; }",
	".framer-RuI3j.framer-v-8wevzx .framer-fm8xi2-container, .framer-RuI3j.framer-v-1pdw1r5 .framer-fm8xi2-container { height: 76px; width: 76px; }",
	".framer-RuI3j.framer-v-8wevzx .framer-1eu1ky6, .framer-RuI3j.framer-v-1pdw1r5 .framer-1eu1ky6 { gap: 16px; }",
	".framer-RuI3j.framer-v-8wevzx .framer-fy7bhx, .framer-RuI3j.framer-v-1pdw1r5 .framer-fy7bhx { gap: 0px; }",
	...css5,
	...css2,
	...css,
	...css3,
	'.framer-RuI3j[data-border="true"]::after, .framer-RuI3j [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerVX0GhcflH = withCSS2(Component2, css6, "framer-RuI3j");
var stdin_default5 = FramerVX0GhcflH;
FramerVX0GhcflH.displayName = "Intro Call Card";
FramerVX0GhcflH.defaultProps = {
	height: 492,
	width: 380,
};
addPropertyControls3(FramerVX0GhcflH, {
	variant: {
		options: ["OIPq05f1b", "ycU0N2u_N", "ZzIspNLGr"],
		optionTitles: ["Call Card V1", "Call Card V2", "Call Card v3"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts2(
	FramerVX0GhcflH,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MemojiFonts,
		...ButtonButtonFonts,
		...FeatureCardFonts,
		...TickerFonts,
		...ParticlesFonts,
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerVX0GhcflH.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default4, {}, context),
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default3, {}, context),
			forwardLoader(stdin_default, {}, context),
		]);
	},
};

// virtual:intro-call-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ycU0N2u_N",
	xl: "ZzIspNLGr",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IntroCallCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var intro_call_card_default = ComponentWithRoot;
export { intro_call_card_default as default };
