// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * start?: number // Start
 * end?: number // End
 * duration?: number // Duration
 * delay?: number // Delay
 * decimals?: number // Decimals
 * easing?: 'Linear' | 'Ease In' | 'Ease Out' | 'Ease In Out' // Easing
 * font?: any // Font
 * color?: string // Color
 * align?: 'Left' | 'Center' | 'Right' // Align
 * suffix?: string // Suffix
 * autoStart?: boolean // Auto Start
 * loop?: boolean // Loop
 * resetOnReEntry?: boolean // Reset on Re-entry
}} Props

 */
import { NumberCounter } from "./chunks/chunk-YOJPOGWW.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:number-counter
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<NumberCounter {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NumberCounterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={NumberCounter}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, NumberCounter);
var number_counter_default = ComponentWithRoot;
export { number_counter_default as default };
