// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Light Version' | 'Dark Version' // Variant
 * sectionTitle?: string // Section Title
}} Props

 */
import { Icon } from "./chunks/chunk-NS43VYZ6.js";
import "./chunks/chunk-MM5BHUY4.js";
import "./chunks/chunk-NULYBL27.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:section-name
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fA7n4FSLhP6jBfd4dAsP/iH9bzm1NH9rOsOh8HzrZ/daCmFYtYF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["LnMorYbbO", "Ag16aFEMr"];
var serializationHash = "framer-o1KnT";
var variantClassNames = {
	Ag16aFEMr: "framer-v-1cu6ati",
	LnMorYbbO: "framer-v-n5ttc9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var transition1 = {
	delay: 0.1,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 20,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition3 = {
	delay: 0,
	duration: 5,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Dark Version": "Ag16aFEMr",
	"Light Version": "LnMorYbbO",
};
var getProps = ({ height, id, sectionTitle, width, ...props }) => {
	return {
		...props,
		LSDJBRwcs: sectionTitle ?? props.LSDJBRwcs ?? "About",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "LnMorYbbO",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, LSDJBRwcs, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LnMorYbbO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-n5ttc9",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Light Version"}
						layoutDependency={layoutDependency}
						layoutId={"LnMorYbbO"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(217, 217, 217))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "dashed",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
							borderBottomLeftRadius: 33,
							borderBottomRightRadius: 33,
							borderTopLeftRadius: 33,
							borderTopRightRadius: 33,
							...style,
						}}
						variants={{
							Ag16aFEMr: {
								"--border-color":
									"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
								backgroundColor:
									"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
							},
						}}
						{...addPropertyOverrides(
							{
								Ag16aFEMr: {
									"data-framer-name": "Dark Version",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-zbuc8"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"f6UpMIoPU"}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainerWithFX
									__framer__loop={animation2}
									__framer__loopEffectEnabled={true}
									__framer__loopPauseOffscreen={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition3}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-h3wepp-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"kEq5iqLol-container"}
									nodeId={"kEq5iqLol"}
									rendersWithMotion={true}
									scopeId={"daCmFYtYF"}
								>
									<Icon
										color={
											"var(--token-c9831028-2838-4766-90a4-c4911c0f418b, rgb(255, 81, 0))"
										}
										height={"100%"}
										iconSearch={"star"}
										iconSelection={"StarFour"}
										id={"kEq5iqLol"}
										layoutId={"kEq5iqLol"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"fill"}
										width={"100%"}
									/>
								</SmartComponentScopedContainerWithFX>
							</ComponentViewportProvider>
						</motion.div>
						<motion.div
							className={"framer-1ev0vi7"}
							data-framer-name={"Texts"}
							layoutDependency={layoutDependency}
							layoutId={"LCj9FxUhl"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-16w3m5t"}
								data-framer-name={"text"}
								fonts={["FS;Plus Jakarta Sans-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"x3Kf9T_5n"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={LSDJBRwcs}
								variants={{
									Ag16aFEMr: {
										"--extracted-r6o4lv":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										Ag16aFEMr: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector":
																"RlM7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
															"--framer-font-family":
																'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
														}}
													>
														{"About"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector":
												"RlM7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
											"--framer-font-family":
												'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
											"--framer-letter-spacing": "-0.02em",
											"--framer-line-height": "1.4em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
										}}
									>
										{"About"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-o1KnT.framer-1f0pk9i, .framer-o1KnT .framer-1f0pk9i { display: block; }",
	".framer-o1KnT.framer-n5ttc9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 5px 15px 5px 15px; position: relative; width: min-content; }",
	".framer-o1KnT .framer-zbuc8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 2px 0px; position: relative; width: min-content; }",
	".framer-o1KnT .framer-h3wepp-container { flex: none; height: 11px; position: relative; width: 9px; }",
	".framer-o1KnT .framer-1ev0vi7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 5px 0px; position: relative; width: min-content; }",
	".framer-o1KnT .framer-16w3m5t { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-o1KnT[data-border="true"]::after, .framer-o1KnT [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerdaCmFYtYF = withCSS(Component, css, "framer-o1KnT");
var stdin_default = FramerdaCmFYtYF;
FramerdaCmFYtYF.displayName = "Section Name";
FramerdaCmFYtYF.defaultProps = {
	height: 37.5,
	width: 92.5,
};
addPropertyControls(FramerdaCmFYtYF, {
	variant: {
		options: ["LnMorYbbO", "Ag16aFEMr"],
		optionTitles: ["Light Version", "Dark Version"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LSDJBRwcs: {
		defaultValue: "About",
		displayTextArea: false,
		title: "Section Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerdaCmFYtYF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Plus Jakarta Sans",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TX2N2Q6ZO2LBO34H72H5RVJTBQFGU4GV/ZICVNTLTT4V7CCIJPWNY363N6LIP2AET/OUUAK2X2MEGEKC6ULA4CFSBY4PE5EGPV.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-name
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "LnMorYbbO",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionNameFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var section_name_default = ComponentWithRoot;
export { section_name_default as default };
