// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Title' | 'Title Left' | 'Title Mobile' // Variant
 * sectionName?: string // Section Name
 * title?: string // Title
 * paragraph?: string // Paragraph
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-XPWBJ3HQ.js";
import { Icon } from "./chunks/chunk-NS43VYZ6.js";
import "./chunks/chunk-MM5BHUY4.js";
import "./chunks/chunk-NULYBL27.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:section-title
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/yKvTqhFioxJ8RJebiziU/2pHKp0IN6sB47PbUWLH8/vLg9TzB_4.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX as withFX2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/6jgiTJ5LTTfdzqACtcFo/0RxGSEFgAo8udM7iJqJs/Hjw3T0c61.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Plus Jakarta Sans-medium",
	"FS;Plus Jakarta Sans-bold",
	"FS;Plus Jakarta Sans-bold italic",
	"FS;Plus Jakarta Sans-medium italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/3U7D2WJULAFN5UCDE2DSKFPDTJNUSRPY/XTZGHUDFURQVBRVTOPX7XHP5YBIQJL2U/FVNNCZHGTHUOM3RCJDOO45QMBIJISVEG.woff2",
				weight: "500",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/AJVGEOXGB2ALQKAZEK2LDOLCVBCMCOIT/LDEP4R7SNNABDEG433DCQGM2A7YCBHLU/OWABOLGBAKFVLPZ756IYS6EKYKU54K3I.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/57U2OK2BISA74Z4RT4CRD5GR4O3PNVPY/K4TDAPUNBYK24HOCNW4JIOTEXSAE2BEF/GV5XODI2YD2DJA5RVTMJOSDHYESL7IYT.woff2",
				weight: "700",
			},
			{
				family: "Plus Jakarta Sans",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/UABF25CCX23LBLOOMOCUSPFEXYUNKOIQ/NGF5IU7BZUA2FUOVWECHGUFSHNEIX4YK/QDINYT7WQXBD2IDFQGGJ74DWIUFHOOZD.woff2",
				weight: "500",
			},
		],
	},
];
var css2 = [
	'.framer-iGTiD .framer-styles-preset-6bhg54:not(.rich-text-wrapper), .framer-iGTiD .framer-styles-preset-6bhg54.rich-text-wrapper p { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.01em; --framer-line-height: 150%; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, #171717); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-iGTiD .framer-styles-preset-6bhg54:not(.rich-text-wrapper), .framer-iGTiD .framer-styles-preset-6bhg54.rich-text-wrapper p { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.01em; --framer-line-height: 150%; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, #171717); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-iGTiD .framer-styles-preset-6bhg54:not(.rich-text-wrapper), .framer-iGTiD .framer-styles-preset-6bhg54.rich-text-wrapper p { --framer-font-family: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-family-italic: "Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.01em; --framer-line-height: 150%; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, #171717); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-iGTiD";

// /:https://framerusercontent.com/modules/zwpp8tIcOO8kci2ashei/KJkT96E9sWkzjIvGEKcS/daCmFYtYF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PhosphorFonts = getFonts(Icon);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["LnMorYbbO", "Ag16aFEMr"];
var serializationHash = "framer-o1KnT";
var variantClassNames = {
	Ag16aFEMr: "framer-v-1cu6ati",
	LnMorYbbO: "framer-v-n5ttc9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var transition1 = {
	delay: 0.1,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 20,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition3 = {
	delay: 0,
	duration: 5,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Dark Version": "Ag16aFEMr",
	"Light Version": "LnMorYbbO",
};
var getProps = ({ height, id, sectionTitle, width, ...props }) => {
	return {
		...props,
		LSDJBRwcs: sectionTitle ?? props.LSDJBRwcs ?? "About",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "LnMorYbbO",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		LSDJBRwcs,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LnMorYbbO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__exit={animation1}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-n5ttc9",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Light Version"}
						layoutDependency={layoutDependency}
						layoutId={"LnMorYbbO"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(217, 217, 217))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "dashed",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
							borderBottomLeftRadius: 33,
							borderBottomRightRadius: 33,
							borderTopLeftRadius: 33,
							borderTopRightRadius: 33,
							...style,
						}}
						variants={{
							Ag16aFEMr: {
								"--border-color":
									"var(--token-cee1c9ca-bedd-4482-8dad-cb5270e5fc5d, rgba(230, 230, 230, 0.1))",
								backgroundColor:
									"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
							},
						}}
						{...addPropertyOverrides(
							{
								Ag16aFEMr: {
									"data-framer-name": "Dark Version",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-zbuc8"}
							data-framer-name={"Icon"}
							layoutDependency={layoutDependency}
							layoutId={"f6UpMIoPU"}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainerWithFX
									__framer__loop={animation2}
									__framer__loopEffectEnabled={true}
									__framer__loopPauseOffscreen={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition3}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-h3wepp-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"kEq5iqLol-container"}
									nodeId={"kEq5iqLol"}
									rendersWithMotion={true}
									scopeId={"daCmFYtYF"}
								>
									<Icon
										color={
											"var(--token-c9831028-2838-4766-90a4-c4911c0f418b, rgb(255, 81, 0))"
										}
										height={"100%"}
										iconSearch={"star"}
										iconSelection={"StarFour"}
										id={"kEq5iqLol"}
										layoutId={"kEq5iqLol"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"fill"}
										width={"100%"}
									/>
								</SmartComponentScopedContainerWithFX>
							</ComponentViewportProvider>
						</motion.div>
						<motion.div
							className={"framer-1ev0vi7"}
							data-framer-name={"Texts"}
							layoutDependency={layoutDependency}
							layoutId={"LCj9FxUhl"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-16w3m5t"}
								data-framer-name={"text"}
								fonts={["FS;Plus Jakarta Sans-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"x3Kf9T_5n"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={LSDJBRwcs}
								variants={{
									Ag16aFEMr: {
										"--extracted-r6o4lv":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										Ag16aFEMr: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector":
																"RlM7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
															"--framer-font-family":
																'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
															"--framer-letter-spacing": "-0.02em",
															"--framer-line-height": "1.4em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
														}}
													>
														{"About"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector":
												"RlM7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
											"--framer-font-family":
												'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
											"--framer-letter-spacing": "-0.02em",
											"--framer-line-height": "1.4em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
										}}
									>
										{"About"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-o1KnT.framer-1f0pk9i, .framer-o1KnT .framer-1f0pk9i { display: block; }",
	".framer-o1KnT.framer-n5ttc9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 5px 15px 5px 15px; position: relative; width: min-content; }",
	".framer-o1KnT .framer-zbuc8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 2px 0px; position: relative; width: min-content; }",
	".framer-o1KnT .framer-h3wepp-container { flex: none; height: 11px; position: relative; width: 9px; }",
	".framer-o1KnT .framer-1ev0vi7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 5px 0px; position: relative; width: min-content; }",
	".framer-o1KnT .framer-16w3m5t { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-o1KnT[data-border="true"]::after, .framer-o1KnT [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerdaCmFYtYF = withCSS(Component, css3, "framer-o1KnT");
var stdin_default = FramerdaCmFYtYF;
FramerdaCmFYtYF.displayName = "Section Name";
FramerdaCmFYtYF.defaultProps = {
	height: 37.5,
	width: 92.5,
};
addPropertyControls(FramerdaCmFYtYF, {
	variant: {
		options: ["LnMorYbbO", "Ag16aFEMr"],
		optionTitles: ["Light Version", "Dark Version"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LSDJBRwcs: {
		defaultValue: "About",
		displayTextArea: false,
		title: "Section Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerdaCmFYtYF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Plus Jakarta Sans",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TX2N2Q6ZO2LBO34H72H5RVJTBQFGU4GV/ZICVNTLTT4V7CCIJPWNY363N6LIP2AET/OUUAK2X2MEGEKC6ULA4CFSBY4PE5EGPV.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/yKvTqhFioxJ8RJebiziU/2pHKp0IN6sB47PbUWLH8/vLg9TzB_4.js
var SectionNameFonts = getFonts2(stdin_default);
var RichTextWithFX = withFX2(RichText2);
var cycleOrder2 = ["FWXm95Vib", "u_S6xUZ5g", "saRZC5VOX"];
var serializationHash2 = "framer-zvOrT";
var variantClassNames2 = {
	FWXm95Vib: "framer-v-1cg7fxb",
	saRZC5VOX: "framer-v-151i04k",
	u_S6xUZ5g: "framer-v-12a5miq",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation3 = {
	filter: "blur(4px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition22 = {
	bounce: 0,
	delay: 0.05,
	duration: 0.4,
	type: "spring",
};
var textEffect = {
	effect: animation3,
	startDelay: 0,
	tokenization: "word",
	transition: transition22,
	trigger: "onInView",
	type: "appear",
};
var animation12 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var transition32 = {
	delay: 0.1,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation22 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition32,
	x: 0,
	y: 20,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Title Left": "u_S6xUZ5g",
	"Title Mobile": "saRZC5VOX",
	Title: "FWXm95Vib",
};
var getProps2 = ({
	height,
	id,
	paragraph,
	sectionName,
	title,
	width,
	...props
}) => {
	return {
		...props,
		E_rWjEvLZ: title ?? props.E_rWjEvLZ ?? "Why Most Creators Burn Out",
		EzsIz6zOm: sectionName ?? props.EzsIz6zOm ?? "Our Solution",
		SFLyMyOrS:
			paragraph ??
			props.SFLyMyOrS ??
			"A quick side-by-side of the struggles you shouldn\u2019t have to deal with and how we make sure you don\u2019t.",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "FWXm95Vib",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		EzsIz6zOm,
		E_rWjEvLZ,
		SFLyMyOrS,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "FWXm95Vib",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1cg7fxb",
							className3,
							classNames,
						)}
						data-framer-name={"Title"}
						layoutDependency={layoutDependency}
						layoutId={"FWXm95Vib"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								saRZC5VOX: {
									"data-framer-name": "Title Mobile",
								},
								u_S6xUZ5g: {
									"data-framer-name": "Title Left",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2
							height={37}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 169) - 0 - 250.6) / 2 + 0 + 0)
							}
							{...addPropertyOverrides2(
								{
									saRZC5VOX: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 244.6) / 2 +
												0 +
												0),
									},
									u_S6xUZ5g: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 174) - 0 - 255.6) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-15f1pwy-container"}
								layoutDependency={layoutDependency}
								layoutId={"x6ddPUiSM-container"}
								nodeId={"x6ddPUiSM"}
								rendersWithMotion={true}
								scopeId={"vLg9TzB_4"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "x6ddPUiSM",
									layoutId: "x6ddPUiSM",
									LSDJBRwcs: EzsIz6zOm,
									variant: "LnMorYbbO",
									width: "100%",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						<motion2.div
							className={"framer-jav17t"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"m5lzLHoN3"}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-191u9ck"}
								data-framer-name={"Title"}
								effect={textEffect}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"i3bdBGnWm"}
								style={{
									"--extracted-1of0zx5":
										"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={E_rWjEvLZ}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										u_S6xUZ5g: {
											children: (
												<React2.Fragment>
													<motion2.h2
														className={"framer-styles-preset-4fkw8l"}
														data-styles-preset={"x3k2llX6m"}
														style={{
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
														}}
													>
														{"Why Most Creators Burn Out"}
													</motion2.h2>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.h2
										className={"framer-styles-preset-4fkw8l"}
										data-styles-preset={"x3k2llX6m"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-1of0zx5, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
										}}
									>
										{"Why Most Creators Burn Out"}
									</motion2.h2>
								</React2.Fragment>
							</RichText2>
							<RichTextWithFX
								__framer__animate={{
									transition: transition32,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation12}
								__framer__exit={animation22}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-zztj7e"}
								fonts={["Inter", "Inter-Italic"]}
								layoutDependency={layoutDependency}
								layoutId={"s16eI_s1B"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={SFLyMyOrS}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										u_S6xUZ5g: {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-6bhg54"}
														data-styles-preset={"Hjw3T0c61"}
														style={{
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33)))",
														}}
													>
														{"A quick side-by-side of the struggles you "}
														<motion2.em>{"shouldn\u2019t"}</motion2.em>
														{
															" have to deal with and how we make sure you don\u2019t."
														}
													</motion2.p>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-6bhg54"}
										data-styles-preset={"Hjw3T0c61"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33)))",
										}}
									>
										{"A quick side-by-side of the struggles you "}
										<motion2.em>{"shouldn\u2019t"}</motion2.em>
										{" have to deal with and how we make sure you don\u2019t."}
									</motion2.p>
								</React2.Fragment>
							</RichTextWithFX>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zvOrT.framer-wycplw, .framer-zvOrT .framer-wycplw { display: block; }",
	".framer-zvOrT.framer-1cg7fxb { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 900px; }",
	".framer-zvOrT .framer-15f1pwy-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-zvOrT .framer-jav17t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: wrap; gap: 16px 10px; height: min-content; justify-content: flex-start; max-width: 630px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-zvOrT .framer-191u9ck { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-zvOrT .framer-zztj7e { flex: none; height: auto; max-width: 500px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-zvOrT.framer-v-12a5miq.framer-1cg7fxb { align-content: flex-start; align-items: flex-start; gap: 10px; }",
	".framer-zvOrT.framer-v-12a5miq .framer-jav17t { align-content: flex-start; align-items: flex-start; }",
	".framer-zvOrT.framer-v-151i04k.framer-1cg7fxb { width: 390px; }",
	".framer-zvOrT.framer-v-151i04k .framer-jav17t { gap: 10px 10px; }",
	".framer-zvOrT.framer-v-151i04k .framer-191u9ck { max-width: 380px; }",
	".framer-zvOrT.framer-v-151i04k .framer-zztj7e { max-width: 330px; }",
	...css,
	...css2,
];
var FramervLg9TzB_4 = withCSS2(Component2, css4, "framer-zvOrT");
var stdin_default2 = FramervLg9TzB_4;
FramervLg9TzB_4.displayName = "Section Title";
FramervLg9TzB_4.defaultProps = {
	height: 169,
	width: 900,
};
addPropertyControls2(FramervLg9TzB_4, {
	variant: {
		options: ["FWXm95Vib", "u_S6xUZ5g", "saRZC5VOX"],
		optionTitles: ["Title", "Title Left", "Title Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	EzsIz6zOm: {
		defaultValue: "Our Solution",
		displayTextArea: false,
		title: "Section Name",
		type: ControlType2.String,
	},
	E_rWjEvLZ: {
		defaultValue: "Why Most Creators Burn Out",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	SFLyMyOrS: {
		defaultValue:
			"A quick side-by-side of the struggles you shouldn\u2019t have to deal with and how we make sure you don\u2019t.",
		displayTextArea: false,
		title: "Paragraph",
		type: ControlType2.String,
	},
});
addFonts2(
	FramervLg9TzB_4,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
					weight: "400",
				},
			],
		},
		...SectionNameFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-title
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "saRZC5VOX",
	xl: "FWXm95Vib",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionTitleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var section_title_default = ComponentWithRoot;
export { section_title_default as default };
