// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * description?: string // Description
 * visible1?: boolean // Visible 1
 * icon1?: any // Icon 1
 * tag1?: string // Tag 1
 * visible2?: boolean // Visible 2
 * icon2?: any // Icon 2
 * tag2?: string // Tag 2
 * visible3?: boolean // Visible 3
 * icon3?: any // Icon 3
 * tag3?: string // Tag 3
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-F2DWXKGV.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PRGAOH24.js";
import { stdin_default } from "./chunks/chunk-LHCNLORJ.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:service-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1iwyndo5NucOMMfJDCId/MqNphUGNdtDvmah0W90J/F0Z24uJm_.js
import { jsx as _jsx4, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls4,
	ComponentViewportProvider,
	ControlType as ControlType4,
	cx as cx4,
	getFonts,
	getFontsFromSharedStyle,
	Instance,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS4,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion as motion4, MotionConfigContext } from "unframer";
import * as React4 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/Gnd5Kt0xT4CvkLltfxC2/65ajNBA8y6lY9NBHalCb/G2W0now0k.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ezTt3ayMo: fill ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		...restProps
	} = getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-OqGKN", className3)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--21h8s6": ezTt3ayMo,
				...style,
			}}
		/>
	);
});
var css3 = [
	`.framer-OqGKN { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url('data:image/svg+xml,<svg aria-label="Align Left Simple" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 1.5 0.75 L 1.5 14.25 C 1.5 14.664 1.164 15 0.75 15 C 0.336 15 0 14.664 0 14.25 L 0 0.75 C 0 0.336 0.336 0 0.75 0 C 1.164 0 1.5 0.336 1.5 0.75 Z M 20.25 4.5 L 20.25 10.5 C 20.25 11.328 19.578 12 18.75 12 L 4.5 12 C 3.672 12 3 11.328 3 10.5 L 3 4.5 C 3 3.672 3.672 3 4.5 3 L 18.75 3 C 19.578 3 20.25 3.672 20.25 4.5 Z M 18.75 10.5 L 18.75 4.5 L 4.5 4.5 L 4.5 10.5 Z" fill="var(--21h8s6, rgb(0,0,0))" height="15px" id="H7ymuFguQ" opacity="1" transform="translate(2.25 4.5)" width="20.25px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-OqGKN");
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType.Color,
	},
});

// /:https://framerusercontent.com/modules/mQm2d94Rodc2tst18R1y/SBIM3UFv2lSHSlOY22mG/cSzDy9yq0.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion2.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps2 = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ezTt3ayMo: fill ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		...restProps
	} = getProps2(props);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-0o2Pg", className3)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--21h8s6": ezTt3ayMo,
				...style,
			}}
		/>
	);
});
var css4 = [
	`.framer-0o2Pg { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url('data:image/svg+xml,<svg aria-label="Megaphone" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 20.25 8.999 C 20.247 6.515 18.234 4.501 15.75 4.499 L 12.019 4.499 C 11.746 4.483 6.992 4.148 2.465 0.351 C 2.018 -0.023 1.395 -0.106 0.867 0.14 C 0.338 0.386 0 0.916 0 1.499 L 0 16.499 C 0 17.082 0.338 17.612 0.866 17.858 C 1.395 18.105 2.018 18.022 2.465 17.647 C 6.006 14.677 9.683 13.826 11.25 13.588 L 11.25 16.562 C 11.249 17.064 11.5 17.533 11.917 17.811 L 12.949 18.499 C 13.353 18.769 13.863 18.826 14.318 18.652 C 14.772 18.478 15.113 18.095 15.234 17.624 L 16.338 13.465 C 18.577 13.167 20.25 11.258 20.25 8.999 Z M 1.5 16.492 L 1.5 1.499 L 1.5 1.499 C 5.513 4.865 9.622 5.718 11.25 5.928 L 11.25 12.066 C 9.623 12.28 5.516 13.13 1.5 16.492 Z M 13.781 17.242 L 13.781 17.253 L 12.75 16.565 L 12.75 13.499 L 14.775 13.499 Z M 15.75 11.999 L 12.75 11.999 L 12.75 5.999 L 15.75 5.999 C 17.407 5.999 18.75 7.342 18.75 8.999 C 18.75 10.656 17.407 11.999 15.75 11.999 Z" fill="var(--21h8s6, rgb(0,0,0))" height="18.75094693000249px" id="ZLMcAUWe_" opacity="1" transform="translate(3 2.251)" width="20.25px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css4, "framer-0o2Pg");
var stdin_default3 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType2.Color,
	},
});

// /:https://framerusercontent.com/modules/PkSncObeVm89eur0bNIO/HBaepVYz1tRPlh2agbqr/F10WU4tAl.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx3,
	motion as motion3,
	withCSS as withCSS3,
} from "unframer";
import * as React3 from "react";
import { forwardRef as forwardRef6 } from "react";
var SVG3 = /* @__PURE__ */ forwardRef6((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion3.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps3 = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ezTt3ayMo: fill ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
	};
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		...restProps
	} = getProps3(props);
	return (
		<SVG3
			{...restProps}
			className={cx3("framer-rCxy1", className3)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--21h8s6": ezTt3ayMo,
				...style,
			}}
		/>
	);
});
var css5 = [
	`.framer-rCxy1 { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url('data:image/svg+xml,<svg aria-label="Subtitles" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 19.5 0 L 1.5 0 C 0.672 0 0 0.672 0 1.5 L 0 13.5 C 0 14.328 0.672 15 1.5 15 L 19.5 15 C 20.328 15 21 14.328 21 13.5 L 21 1.5 C 21 0.672 20.328 0 19.5 0 Z M 19.5 13.5 L 1.5 13.5 L 1.5 1.5 L 19.5 1.5 Z M 3 8.25 C 3 7.836 3.336 7.5 3.75 7.5 L 5.25 7.5 C 5.664 7.5 6 7.836 6 8.25 C 6 8.664 5.664 9 5.25 9 L 3.75 9 C 3.336 9 3 8.664 3 8.25 Z M 18 8.25 C 18 8.664 17.664 9 17.25 9 L 8.25 9 C 7.836 9 7.5 8.664 7.5 8.25 C 7.5 7.836 7.836 7.5 8.25 7.5 L 17.25 7.5 C 17.664 7.5 18 7.836 18 8.25 Z M 13.5 11.25 C 13.5 11.664 13.164 12 12.75 12 L 3.75 12 C 3.336 12 3 11.664 3 11.25 C 3 10.836 3.336 10.5 3.75 10.5 L 12.75 10.5 C 13.164 10.5 13.5 10.836 13.5 11.25 Z M 18 11.25 C 18 11.664 17.664 12 17.25 12 L 15.75 12 C 15.336 12 15 11.664 15 11.25 C 15 10.836 15.336 10.5 15.75 10.5 L 17.25 10.5 C 17.664 10.5 18 10.836 18 11.25 Z" fill="var(--21h8s6, rgb(0,0,0))" height="15px" id="TT14Z9lgP" opacity="1" transform="translate(1.5 4.5)" width="21px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon3 = withCSS3(Component3, css5, "framer-rCxy1");
var stdin_default4 = Icon3;
addPropertyControls3(Icon3, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType3.Color,
	},
});

// /:https://framerusercontent.com/modules/1iwyndo5NucOMMfJDCId/MqNphUGNdtDvmah0W90J/F0Z24uJm_.js
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion4.div),
);
var ParticlesFonts = getFonts(stdin_default);
var serializationHash = "framer-FABVX";
var variantClassNames = {
	SwA4pSuhC: "framer-v-lcn23n",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0.4,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var Transition = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion4.create(React4.Fragment);
var getProps4 = ({
	description,
	height,
	icon1,
	icon2,
	icon3,
	id,
	tag1,
	tag2,
	tag3,
	title,
	visible1,
	visible2,
	visible3,
	width,
	...props
}) => {
	return {
		...props,
		beTztt3Mx: tag1 ?? props.beTztt3Mx ?? "Snappy Pacing\xA0",
		CQRuUqzNq:
			description ??
			props.CQRuUqzNq ??
			"We turn raw clips into high-retention, caption-packed vertical videos that pop on Reels, Shorts, and TikTok. Great for content repurposing and explosive growth.",
		egjS7JFVG: visible2 ?? props.egjS7JFVG ?? true,
		ExkEVtJ0U: title ?? props.ExkEVtJ0U ?? "Youtube Shorts Editing",
		fogtJqlnj: tag3 ?? props.fogtJqlnj ?? "Subtitled",
		JBz7GV2Xw: icon1 ?? props.JBz7GV2Xw ?? stdin_default2,
		kblgZJZ2C: visible1 ?? props.kblgZJZ2C ?? true,
		MGDJ56mxI: icon2 ?? props.MGDJ56mxI ?? stdin_default3,
		uAIk9nD9r: tag2 ?? props.uAIk9nD9r ?? "Viral-Ready",
		wmeEbX7ah: visible3 ?? props.wmeEbX7ah ?? true,
		WOQOhzaDV: icon3 ?? props.WOQOhzaDV ?? stdin_default4,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ExkEVtJ0U,
		CQRuUqzNq,
		kblgZJZ2C,
		JBz7GV2Xw,
		beTztt3Mx,
		egjS7JFVG,
		MGDJ56mxI,
		uAIk9nD9r,
		wmeEbX7ah,
		WOQOhzaDV,
		fogtJqlnj,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "SwA4pSuhC",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx4(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion4.div
						{...restProps}
						{...gestureHandlers}
						className={cx4(
							scopingClassNames,
							"framer-lcn23n",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"SwA4pSuhC"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
					>
						<motion4.div
							className={"framer-58nouj"}
							data-framer-name={"Card Title"}
							layoutDependency={layoutDependency}
							layoutId={"btWrS0hn1"}
						>
							<motion4.div
								className={"framer-hvkql2"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"JSYhjcinV"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1cvpo5w"}
									data-framer-name={"Sign Up Today"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"cEAe_uXok"}
									style={{
										"--extracted-1lwpl3i":
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={ExkEVtJ0U}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React4.Fragment>
										<motion4.h5
											className={"framer-styles-preset-1ca70s3"}
											data-styles-preset={"DBxzZNmNW"}
											style={{
												"--framer-text-color":
													"var(--extracted-1lwpl3i, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
											}}
										>
											{"Youtube Shorts Editing"}
										</motion4.h5>
									</React4.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1dh1gkl"}
									data-framer-name={
										"Create your account quickly and start your financial journey effortlessly."
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lChkakUM2"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(230, 230, 230))",
										"--framer-paragraph-spacing": "0px",
										opacity: 0.8,
									}}
									text={CQRuUqzNq}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React4.Fragment>
										<motion4.p
											className={"framer-styles-preset-71c1l6"}
											data-styles-preset={"r7igaR65_"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(230, 230, 230)))",
											}}
										>
											{
												"We turn raw clips into high-retention, caption-packed vertical videos that pop on Reels, Shorts, and TikTok. Great for content repurposing and explosive growth."
											}
										</motion4.p>
									</React4.Fragment>
								</RichText>
							</motion4.div>
							<motion4.div
								className={"framer-rvv81y"}
								data-framer-name={"TagBars"}
								layoutDependency={layoutDependency}
								layoutId={"GyBh_Cz5C"}
							>
								{kblgZJZ2C && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1uj01tu"}
										data-border={true}
										data-framer-appear-id={"1uj01tu"}
										data-framer-name={"1"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"RZ49VKgMR"}
										optimized={true}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(230, 230, 230, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
											borderBottomLeftRadius: 33,
											borderBottomRightRadius: 33,
											borderTopLeftRadius: 33,
											borderTopRightRadius: 33,
										}}
									>
										<Instance
											animated={true}
											className={"framer-4tzqyv"}
											Component={JBz7GV2Xw}
											layoutDependency={layoutDependency}
											layoutId={"aKJbSGQ6I"}
											style={{
												"--21h8s6":
													"var(--token-c9831028-2838-4766-90a4-c4911c0f418b, rgb(255, 81, 0))",
											}}
										/>
										<motion4.div
											className={"framer-zbkptx"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"RZ49VKgMRLCj9FxUhl"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1vv9k2i"}
												data-framer-name={"text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"RZ49VKgMRx3Kf9T_5n"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={beTztt3Mx}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React4.Fragment>
													<motion4.p
														className={"framer-styles-preset-71c1l6"}
														data-styles-preset={"r7igaR65_"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
														}}
													>
														{"Snappy Pacing\xA0"}
													</motion4.p>
												</React4.Fragment>
											</RichText>
										</motion4.div>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{egjS7JFVG && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-12egy5i"}
										data-border={true}
										data-framer-appear-id={"12egy5i"}
										data-framer-name={"2"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"WuMI3ruox"}
										optimized={true}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(230, 230, 230, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
											borderBottomLeftRadius: 33,
											borderBottomRightRadius: 33,
											borderTopLeftRadius: 33,
											borderTopRightRadius: 33,
										}}
									>
										<Instance
											animated={true}
											className={"framer-zlm3dr"}
											Component={MGDJ56mxI}
											layoutDependency={layoutDependency}
											layoutId={"xIyZwfrLx"}
											style={{
												"--21h8s6":
													"var(--token-c9831028-2838-4766-90a4-c4911c0f418b, rgb(255, 81, 0))",
											}}
										/>
										<motion4.div
											className={"framer-6yw1u5"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"ssTrT04oL"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-tqk1g1"}
												data-framer-name={"text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"VyDpQpeMx"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={uAIk9nD9r}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React4.Fragment>
													<motion4.p
														className={"framer-styles-preset-71c1l6"}
														data-styles-preset={"r7igaR65_"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
														}}
													>
														{"Viral-Ready"}
													</motion4.p>
												</React4.Fragment>
											</RichText>
										</motion4.div>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
								{wmeEbX7ah && (
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1cu3kus"}
										data-border={true}
										data-framer-appear-id={"1cu3kus"}
										data-framer-name={"3"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"Aah8qnLoY"}
										optimized={true}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(230, 230, 230, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-c9815d1b-8285-4dd9-ad9a-6fd9a34bdaa2, rgb(33, 33, 33))",
											borderBottomLeftRadius: 33,
											borderBottomRightRadius: 33,
											borderTopLeftRadius: 33,
											borderTopRightRadius: 33,
										}}
									>
										<Instance
											animated={true}
											className={"framer-2gee6q"}
											Component={WOQOhzaDV}
											layoutDependency={layoutDependency}
											layoutId={"ZHFi5YIx6"}
											style={{
												"--21h8s6":
													"var(--token-c9831028-2838-4766-90a4-c4911c0f418b, rgb(255, 81, 0))",
											}}
										/>
										<motion4.div
											className={"framer-1pc4i16"}
											layoutDependency={layoutDependency}
											layoutId={"By1IUDs3h"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1upuze1"}
												data-framer-name={"text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"DVOuxCNGN"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
													"--framer-paragraph-spacing": "0px",
												}}
												text={fogtJqlnj}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React4.Fragment>
													<motion4.p
														className={"framer-styles-preset-71c1l6"}
														data-styles-preset={"r7igaR65_"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255)))",
														}}
													>
														{"Subtitled"}
													</motion4.p>
												</React4.Fragment>
											</RichText>
										</motion4.div>
									</MotionDivWithFXWithOptimizedAppearEffect>
								)}
							</motion4.div>
						</motion4.div>
						<ComponentViewportProvider
							height={87}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 300) -
								86.5
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1tjvxjh-container"}
								layoutDependency={layoutDependency}
								layoutId={"lulbPglq5-container"}
								nodeId={"lulbPglq5"}
								rendersWithMotion={true}
								scopeId={"F0Z24uJm_"}
								style={{
									opacity: 0.5,
								}}
							>
								{_jsx4(stdin_default, {
									height: "100%",
									id: "lulbPglq5",
									layoutId: "lulbPglq5",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion4.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FABVX.framer-i25mfy, .framer-FABVX .framer-i25mfy { display: block; }",
	".framer-FABVX.framer-lcn23n { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: 300px; justify-content: flex-start; overflow: hidden; padding: 25px; position: relative; width: 580px; will-change: var(--framer-will-change-override, transform); }",
	".framer-FABVX .framer-58nouj { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 5; }",
	".framer-FABVX .framer-hvkql2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-FABVX .framer-1cvpo5w, .framer-FABVX .framer-1dh1gkl { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-FABVX .framer-rvv81y { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-FABVX .framer-1uj01tu, .framer-FABVX .framer-12egy5i, .framer-FABVX .framer-1cu3kus { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 5px 15px 5px 15px; position: relative; width: min-content; }",
	".framer-FABVX .framer-4tzqyv, .framer-FABVX .framer-zlm3dr, .framer-FABVX .framer-2gee6q { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-FABVX .framer-zbkptx, .framer-FABVX .framer-6yw1u5, .framer-FABVX .framer-1pc4i16 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 5px 0px; position: relative; width: min-content; }",
	".framer-FABVX .framer-1vv9k2i, .framer-FABVX .framer-tqk1g1, .framer-FABVX .framer-1upuze1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-FABVX .framer-1tjvxjh-container { bottom: 0px; flex: none; height: 87px; left: 0px; position: absolute; right: 0px; z-index: 1; }",
	...css,
	...css2,
	'.framer-FABVX[data-border="true"]::after, .framer-FABVX [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerF0Z24uJm_ = withCSS4(Component4, css6, "framer-FABVX");
var stdin_default5 = FramerF0Z24uJm_;
FramerF0Z24uJm_.displayName = "Service Card";
FramerF0Z24uJm_.defaultProps = {
	height: 300,
	width: 580,
};
addPropertyControls4(FramerF0Z24uJm_, {
	ExkEVtJ0U: {
		defaultValue: "Youtube Shorts Editing",
		displayTextArea: false,
		title: "Title",
		type: ControlType4.String,
	},
	CQRuUqzNq: {
		defaultValue:
			"We turn raw clips into high-retention, caption-packed vertical videos that pop on Reels, Shorts, and TikTok. Great for content repurposing and explosive growth.",
		displayTextArea: false,
		title: "Description",
		type: ControlType4.String,
	},
	kblgZJZ2C: {
		defaultValue: true,
		title: "Visible 1",
		type: ControlType4.Boolean,
	},
	JBz7GV2Xw: {
		defaultValue: {
			identifier:
				"module:Gnd5Kt0xT4CvkLltfxC2/65ajNBA8y6lY9NBHalCb/G2W0now0k.js:default",
			moduleId: "Gnd5Kt0xT4CvkLltfxC2",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon 1",
		type: ControlType4.VectorSetItem,
	},
	beTztt3Mx: {
		defaultValue: "Snappy Pacing\xA0",
		displayTextArea: false,
		title: "Tag 1",
		type: ControlType4.String,
	},
	egjS7JFVG: {
		defaultValue: true,
		title: "Visible 2",
		type: ControlType4.Boolean,
	},
	MGDJ56mxI: {
		defaultValue: {
			identifier:
				"module:mQm2d94Rodc2tst18R1y/SBIM3UFv2lSHSlOY22mG/cSzDy9yq0.js:default",
			moduleId: "mQm2d94Rodc2tst18R1y",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon 2",
		type: ControlType4.VectorSetItem,
	},
	uAIk9nD9r: {
		defaultValue: "Viral-Ready",
		displayTextArea: false,
		title: "Tag 2",
		type: ControlType4.String,
	},
	wmeEbX7ah: {
		defaultValue: true,
		title: "Visible 3",
		type: ControlType4.Boolean,
	},
	WOQOhzaDV: {
		defaultValue: {
			identifier:
				"module:PkSncObeVm89eur0bNIO/HBaepVYz1tRPlh2agbqr/F10WU4tAl.js:default",
			moduleId: "PkSncObeVm89eur0bNIO",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon 3",
		type: ControlType4.VectorSetItem,
	},
	fogtJqlnj: {
		defaultValue: "Subtitled",
		displayTextArea: false,
		title: "Tag 3",
		type: ControlType4.String,
	},
});
addFonts(
	FramerF0Z24uJm_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ParticlesFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:service-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var service_card_default = ComponentWithRoot;
export { service_card_default as default };
