// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-2LE5K7IJ.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:trust-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rYafKaCA259MDJA9UNSG/et3iKnapiQCoiPDeyOrb/WQKUlbWQo.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-dmUvR";
var variantClassNames = {
	uiThFpyQ4: "framer-v-qj4fo8",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	image,
	image2,
	image3,
	title,
	width,
	...props
}) => {
	return {
		...props,
		GjRuKs1Y2: image3 ??
			props.GjRuKs1Y2 ?? {
				alt: "Hero Image",
				pixelHeight: 3264,
				pixelWidth: 4928,
				src: "https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/IQKddGGUVKfESbTRhHhxUrBqwQ.jpg 4928w",
			},
		JLLSLn3YE: image ??
			props.JLLSLn3YE ?? {
				alt: "Hero Image",
				pixelHeight: 6720,
				pixelWidth: 4480,
				src: "https://framerusercontent.com/images/YR5ogHEHXqNnMFsCoiZCW76yG4.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/YR5ogHEHXqNnMFsCoiZCW76yG4.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/YR5ogHEHXqNnMFsCoiZCW76yG4.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/YR5ogHEHXqNnMFsCoiZCW76yG4.jpg?scale-down-to=4096 2730w,https://framerusercontent.com/images/YR5ogHEHXqNnMFsCoiZCW76yG4.jpg 4480w",
			},
		REzw5nRG9: title ?? props.REzw5nRG9 ?? "Trusted By 100+ Creators",
		VXA0EzCgK: image2 ??
			props.VXA0EzCgK ?? {
				alt: "Hero Image",
				pixelHeight: 3993,
				pixelWidth: 2662,
				src: "https://framerusercontent.com/images/Y9KmJAQ4w53hsc4jJojfokLZ7D8.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/Y9KmJAQ4w53hsc4jJojfokLZ7D8.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/Y9KmJAQ4w53hsc4jJojfokLZ7D8.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/Y9KmJAQ4w53hsc4jJojfokLZ7D8.jpg 2662w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		REzw5nRG9,
		JLLSLn3YE,
		VXA0EzCgK,
		GjRuKs1Y2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "uiThFpyQ4",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-qj4fo8",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Card"}
						layoutDependency={layoutDependency}
						layoutId={"uiThFpyQ4"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(217, 217, 217))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "dashed",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
							borderBottomLeftRadius: 40,
							borderBottomRightRadius: 40,
							borderTopLeftRadius: 40,
							borderTopRightRadius: 40,
							boxShadow: "0px 4px 10px 0px rgba(0, 0, 0, 0.02)",
							...style,
						}}
					>
						<motion.div
							className={"framer-5qhcf7"}
							data-framer-name={"Image List "}
							layoutDependency={layoutDependency}
							layoutId={"xWxZdOZDm"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(11 +
												((componentViewport?.height || 45.5) - 22 - 23.72) /
													2) +
											0,
									),
									pixelHeight: 6720,
									pixelWidth: 4480,
									sizes: "23.72px",
									...toResponsiveImage(JLLSLn3YE),
								}}
								className={"framer-17nlhzg"}
								data-border={true}
								data-framer-name={"Image 04"}
								layoutDependency={layoutDependency}
								layoutId={"GnxrssK2B"}
								style={{
									"--border-bottom-width": "0.74px",
									"--border-color": "rgb(255, 255, 255)",
									"--border-left-width": "0.74px",
									"--border-right-width": "0.74px",
									"--border-style": "solid",
									"--border-top-width": "0.74px",
									borderBottomLeftRadius: "74.13%",
									borderBottomRightRadius: "74.13%",
									borderTopLeftRadius: "74.13%",
									borderTopRightRadius: "74.13%",
								}}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(11 +
												((componentViewport?.height || 45.5) - 22 - 23.72) /
													2) +
											0,
									),
									pixelHeight: 3993,
									pixelWidth: 2662,
									sizes: "23.72px",
									...toResponsiveImage(VXA0EzCgK),
								}}
								className={"framer-1l0boxd"}
								data-border={true}
								data-framer-name={"Image 03"}
								layoutDependency={layoutDependency}
								layoutId={"OxpmcgsGU"}
								style={{
									"--border-bottom-width": "0.74px",
									"--border-color": "rgb(255, 255, 255)",
									"--border-left-width": "0.74px",
									"--border-right-width": "0.74px",
									"--border-style": "solid",
									"--border-top-width": "0.74px",
									borderBottomLeftRadius: "74.13%",
									borderBottomRightRadius: "74.13%",
									borderTopLeftRadius: "74.13%",
									borderTopRightRadius: "74.13%",
								}}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(11 +
												((componentViewport?.height || 45.5) - 22 - 23.72) /
													2) +
											0,
									),
									pixelHeight: 3264,
									pixelWidth: 4928,
									sizes: "23.72px",
									...toResponsiveImage(GjRuKs1Y2),
								}}
								className={"framer-fabn2o"}
								data-border={true}
								data-framer-name={"Image 02"}
								layoutDependency={layoutDependency}
								layoutId={"fQLkuEJ4f"}
								style={{
									"--border-bottom-width": "0.74px",
									"--border-color": "rgb(255, 255, 255)",
									"--border-left-width": "0.74px",
									"--border-right-width": "0.74px",
									"--border-style": "solid",
									"--border-top-width": "0.74px",
									borderBottomLeftRadius: "74.13%",
									borderBottomRightRadius: "74.13%",
									borderTopLeftRadius: "74.13%",
									borderTopRightRadius: "74.13%",
								}}
							/>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-geaj8v"}
							data-framer-name={"text"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"mi5T708u6"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={REzw5nRG9}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-19bvac3"}
									data-styles-preset={"ZTKtBvUjS"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23)))",
									}}
								>
									{"Trusted By 100+ Creators"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dmUvR.framer-1bqc3st, .framer-dmUvR .framer-1bqc3st { display: block; }",
	".framer-dmUvR.framer-qj4fo8 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: hidden; padding: 11px 17px 11px 17px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-dmUvR .framer-5qhcf7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 7.41px; height: 24px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 57px; }",
	".framer-dmUvR .framer-17nlhzg { aspect-ratio: 1 / 1; bottom: 0px; flex: none; left: 0px; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 24px); z-index: 1; }",
	".framer-dmUvR .framer-1l0boxd { aspect-ratio: 1 / 1; bottom: 0px; flex: none; left: 16px; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 24px); z-index: 2; }",
	".framer-dmUvR .framer-fabn2o { aspect-ratio: 1 / 1; bottom: 0px; flex: none; left: 33px; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 24px); z-index: 2; }",
	".framer-dmUvR .framer-geaj8v { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
	'.framer-dmUvR[data-border="true"]::after, .framer-dmUvR [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerWQKUlbWQo = withCSS(Component, css2, "framer-dmUvR");
var stdin_default = FramerWQKUlbWQo;
FramerWQKUlbWQo.displayName = "Trust Card";
FramerWQKUlbWQo.defaultProps = {
	height: 45.5,
	width: 264,
};
addPropertyControls(FramerWQKUlbWQo, {
	REzw5nRG9: {
		defaultValue: "Trusted By 100+ Creators",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	JLLSLn3YE: {
		__defaultAssetReference:
			"data:framer/asset-reference,YR5ogHEHXqNnMFsCoiZCW76yG4.jpg?originalFilename=photo-1664575602554-2087b04935a5%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxfHx3b21hbnxlbnwwfHx8fDE3NDY0MzY5ODl8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "Hero Image",
			assetReference:
				"data:framer/asset-reference,YR5ogHEHXqNnMFsCoiZCW76yG4.jpg?originalFilename=photo-1664575602554-2087b04935a5%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxfHx3b21hbnxlbnwwfHx8fDE3NDY0MzY5ODl8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	VXA0EzCgK: {
		__defaultAssetReference:
			"data:framer/asset-reference,Y9KmJAQ4w53hsc4jJojfokLZ7D8.jpg?originalFilename=photo-1539571696357-5a69c17a67c6%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw1fHxtYW58ZW58MHx8fHwxNzQ2NDA5MDg3fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "Hero Image",
			assetReference:
				"data:framer/asset-reference,Y9KmJAQ4w53hsc4jJojfokLZ7D8.jpg?originalFilename=photo-1539571696357-5a69c17a67c6%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw1fHxtYW58ZW58MHx8fHwxNzQ2NDA5MDg3fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		},
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	GjRuKs1Y2: {
		__defaultAssetReference:
			"data:framer/asset-reference,IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?originalFilename=photo-1564564321837-a57b7070ac4f%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw2fHxtYW58ZW58MHx8fHwxNzQ2NDA5MDg3fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "Hero Image",
			assetReference:
				"data:framer/asset-reference,IQKddGGUVKfESbTRhHhxUrBqwQ.jpg?originalFilename=photo-1564564321837-a57b7070ac4f%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw2fHxtYW58ZW58MHx8fHwxNzQ2NDA5MDg3fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		},
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerWQKUlbWQo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:trust-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TrustCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var trust_card_default = ComponentWithRoot;
export { trust_card_default as default };
