// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8432de3c3dd39f1f "CreatorFlow Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Dark' | 'Dark Mobile Version' | 'Dark Desktop Playing' | 'Dark Mobile Playing' // Variant
 * youtubeVideoURL?: string // Youtube Video URL
 * onXPOFLGbNtChange?: any // onXPOFLGbNtChange
 * youtubeVisible?: boolean // Youtube Visible
 * ond3z5agfpnChange?: any // ond3z5agfpnChange
 * videoFileVisible?: boolean // Video File Visible
 * oncOv1RTY21Change?: any // oncOv1RTY21Change
 * cursor1?: any // Cursor 1
 * cursor2?: any // Cursor 2
}} Props

 */
import { Icon as Icon2 } from "./chunks/chunk-66EJKQKM.js";
import { Icon } from "./chunks/chunk-NS43VYZ6.js";
import "./chunks/chunk-MM5BHUY4.js";
import "./chunks/chunk-NULYBL27.js";
import {
	Youtube,
	borderRadiusControl,
	defaultEvents,
	useIsBrowserSafari,
	useIsOnCanvas,
	useOnEnter,
	useOnExit,
	useRadius,
	useRenderTarget,
} from "./chunks/chunk-SVFCGEDN.js";
import { routes } from "./chunks/chunk-6YUVG4ZJ.js";

// virtual:youtube-video
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/b5zs63ozvAt3JHMD5ROJ/R1RqOSTkgUszWr6ifGXv/yl67s275s.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image as Image1,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/lRDHiNWNVWmE0lqtoVHP/7qT0r3So12155VV5Jq5x/Video.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	useIsInCurrentNavigationTarget,
	RenderTarget,
} from "unframer";
import { isMotionValue, useInView } from "unframer";
import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react";
var ObjectFitType;
(function (ObjectFitType2) {
	ObjectFitType2["Fill"] = "fill";
	ObjectFitType2["Contain"] = "contain";
	ObjectFitType2["Cover"] = "cover";
	ObjectFitType2["None"] = "none";
	ObjectFitType2["ScaleDown"] = "scale-down";
})(ObjectFitType || (ObjectFitType = {}));
var SrcType;
(function (SrcType2) {
	SrcType2["Video"] = "Upload";
	SrcType2["Url"] = "URL";
})(SrcType || (SrcType = {}));
var defaultVideo =
	"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4";
function getProps(props) {
	const {
		width,
		height,
		topLeft,
		topRight,
		bottomRight,
		bottomLeft,
		id,
		children,
		...rest
	} = props;
	return rest;
}
function Video(props) {
	const newProps = getProps(props);
	return <VideoMemo {...newProps} />;
}
function usePlaybackControls(videoRef) {
	const isInCurrentNavigationTarget = useIsInCurrentNavigationTarget();
	const requestingPlay = useRef(false);
	const isPlayingRef = useRef(false);
	const setProgress = useCallback((rawProgress) => {
		if (!videoRef.current) return;
		const newProgress =
			(rawProgress === 1 ? 0.999 : rawProgress) * videoRef.current.duration;
		const isAlreadySet =
			Math.abs(videoRef.current.currentTime - newProgress) < 0.1;
		if (videoRef.current.duration > 0 && !isAlreadySet) {
			videoRef.current.currentTime = newProgress;
		}
	}, []);
	const play = useCallback(() => {
		const video = videoRef.current;
		if (!video) return;
		video.preload = "auto";
		const isPlaying =
			video.currentTime > 0 &&
			video.onplaying &&
			!video.paused &&
			!video.ended &&
			video.readyState >= video.HAVE_CURRENT_DATA;
		if (
			!isPlaying &&
			video &&
			!requestingPlay.current &&
			isInCurrentNavigationTarget
		) {
			requestingPlay.current = true;
			isPlayingRef.current = true;
			video
				.play()
				.catch((e) => {})
				.finally(() => (requestingPlay.current = false));
		}
	}, []);
	const pause = useCallback(() => {
		if (!videoRef.current || requestingPlay.current) return;
		videoRef.current.pause();
		isPlayingRef.current = false;
	}, []);
	return {
		play,
		pause,
		setProgress,
		isPlaying: isPlayingRef,
	};
}
function useAutoplayBehavior({
	playingProp,
	muted,
	loop,
	playsinline,
	controls,
}) {
	const [initialPlayingProp] = useState(() => playingProp);
	const [hasPlayingPropChanged, setHasPlayingPropChanged] = useState(false);
	if (playingProp !== initialPlayingProp && !hasPlayingPropChanged) {
		setHasPlayingPropChanged(true);
	}
	const behavesAsGif =
		// passing `playing === true` on mount indicates that the video should
		// autoplay, like a GIF
		initialPlayingProp &&
		muted &&
		loop &&
		playsinline &&
		!controls &&
		// Some users of the <Video> component use it by wrapping it with
		// another smart component and adding their own controls on top. (The
		// controls use transitions to control the video: e.g., when clicking
		// the play button, the smart component will transition to a state with
		// <Video playing={true} />.) In this case, we don't want the video to
		// behave as a gif, as it will be weird if the video suddenly started
		// acting as such (and auto-pausing when leaving the viewport) as soon
		// as the site visitor mutes it and clicks “Play”.
		!hasPlayingPropChanged;
	let autoplay;
	if (behavesAsGif) autoplay = "on-viewport";
	else if (initialPlayingProp) autoplay = "on-mount";
	else autoplay = "no-autoplay";
	return autoplay;
}
var VideoMemo = /* @__PURE__ */ memo(function VideoInner(props) {
	const {
		// default props
		srcType = "URL",
		srcUrl,
		srcFile = "",
		posterEnabled = false,
		controls = false,
		playing = true,
		loop = true,
		muted = true,
		playsinline = true,
		restartOnEnter = false,
		objectFit = "cover",
		backgroundColor = "rgba(0,0,0,0)",
		radius = 0,
		volume = 25,
		startTime: startTimeProp = 0,
		poster,
		playing: playingProp,
		progress,
		onSeeked,
		onPause,
		onPlay,
		onEnd,
		onClick,
		onMouseEnter,
		onMouseLeave,
		onMouseDown,
		onMouseUp,
	} = props;
	const videoRef = useRef();
	const isSafari = useIsBrowserSafari();
	const wasPausedOnLeave = useRef(null);
	const wasEndedOnLeave = useRef(null);
	const isOnCanvas = useIsOnCanvas();
	const renderTarget = useRenderTarget();
	const isStaticRenderer = isOnCanvas || renderTarget === RenderTarget.export;
	const borderRadius = useRadius(props);
	const autoplayBehavior = isStaticRenderer
		? "no-autoplay"
		: useAutoplayBehavior({
				playingProp,
				muted,
				loop,
				playsinline,
				controls,
			});
	const isInViewport = isStaticRenderer ? true : useInView(videoRef);
	const isCloseToViewport = isStaticRenderer
		? false
		: useInView(videoRef, {
				margin: "10%",
				once: true,
			});
	const startTime = startTimeProp === 100 ? 99.9 : startTimeProp;
	const { play, pause, setProgress, isPlaying } = usePlaybackControls(videoRef);
	useEffect(() => {
		if (isStaticRenderer) return;
		if (autoplayBehavior === "on-viewport") return;
		if (playingProp) play();
		else pause();
	}, [autoplayBehavior, playingProp]);
	useEffect(() => {
		if (isStaticRenderer) return;
		if (isInViewport && playingProp && autoplayBehavior !== "no-autoplay")
			play();
		if (autoplayBehavior !== "on-viewport") return;
		pause();
	}, [autoplayBehavior, isInViewport, playingProp]);
	useEffect(() => {
		if (
			!isOnCanvas ||
			poster ||
			posterEnabled ||
			startTime ||
			!videoRef.current
		)
			return;
		videoRef.current.currentTime = 0.01;
	}, [posterEnabled, poster, startTime]);
	const isMountedAndReadyForProgressChanges = useRef(false);
	useEffect(() => {
		if (!isMountedAndReadyForProgressChanges.current) {
			isMountedAndReadyForProgressChanges.current = true;
			return;
		}
		const rawProgressValue = isMotionValue(progress)
			? progress.get()
			: (progress ?? 0) * 0.01;
		setProgress(
			// When the progress value exists (e.g. <Video startTime={10}
			// progress={50} />), we respect the `progress` value over
			// `startTime`, even if `startTime` changes. That’s because
			// `startTime` == start == changing it shouldn’t affect the current
			// progress
			(rawProgressValue ?? 0) ||
				// Then why fall back to `startTime` when `progress` doesn’t exist,
				// you might ask? Now, that’s for
				// - canvas UX: we want the video progress to change when the user
				//   is scrobbling the “Start Time” in component settings.
				// - backwards compatibility: maybe some users *are* scrobbling
				//   using `startTime` instead of `progress`? We don’t know, and it
				//   always supported it, so let’s not break it
				(startTime ?? 0) / 100,
		);
	}, [startTime, srcFile, srcUrl, progress]);
	useEffect(() => {
		if (!isMotionValue(progress)) return;
		return progress.on("change", (value) => setProgress(value));
	}, [progress]);
	useOnEnter(() => {
		if (wasPausedOnLeave.current === null) return;
		if (videoRef.current) {
			if ((!wasEndedOnLeave && loop) || !wasPausedOnLeave.current) play();
		}
	});
	useOnExit(() => {
		if (videoRef.current) {
			wasEndedOnLeave.current = videoRef.current.ended;
			wasPausedOnLeave.current = videoRef.current.paused;
			pause();
		}
	});
	const src = useMemo(() => {
		let fragment = "";
		if (srcType === "URL") return srcUrl + fragment;
		if (srcType === "Upload") return srcFile + fragment;
	}, [srcType, srcFile, srcUrl, startTime]);
	useEffect(() => {
		if (isSafari && videoRef.current && autoplayBehavior === "on-mount") {
			setTimeout(() => play(), 50);
		}
	}, []);
	useEffect(() => {
		if (videoRef.current && !muted)
			videoRef.current.volume = (volume ?? 0) / 100;
	}, [volume]);
	const handleReady = () => {
		const video = videoRef.current;
		if (!video) return;
		if (video.currentTime < 0.3 && startTime > 0)
			setProgress((startTime ?? 0) * 0.01);
		if (
			// when the component updates (e.g. only srcFile/url changes), and the video was already playing, keep playing
			isPlaying.current ||
			autoplayBehavior === "on-mount" ||
			(playingProp && autoplayBehavior === "on-viewport" && isInViewport)
		)
			play();
	};
	return (
		<video
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
			src={src}
			loop={loop}
			ref={videoRef}
			onSeeked={(e) => onSeeked?.(e)}
			onPause={(e) => onPause?.(e)}
			onPlay={(e) => onPlay?.(e)}
			onEnded={(e) => onEnd?.(e)}
			autoPlay={
				isPlaying.current ||
				autoplayBehavior === "on-mount" ||
				(playingProp && autoplayBehavior === "on-viewport" && isInViewport)
			}
			preload={
				isPlaying.current
					? "auto"
					: isStaticRenderer && !poster
						? "metadata"
						: autoplayBehavior !== "on-mount" && !isCloseToViewport
							? "none"
							: // `autoplay` overrides this too
								"metadata"
			}
			poster={
				posterEnabled && !srcFile && srcUrl === defaultVideo
					? "https://framerusercontent.com/images/5ILRvlYXf72kHSVHqpa3snGzjU.jpg"
					: posterEnabled && poster
						? poster
						: void 0
			}
			onLoadedData={handleReady}
			controls={controls}
			muted={isStaticRenderer ? true : muted}
			playsInline={playsinline}
			style={{
				cursor: !!onClick ? "pointer" : "auto",
				width: "100%",
				height: "100%",
				borderRadius,
				display: "block",
				objectFit,
				backgroundColor,
				objectPosition: "50% 50%",
			}}
		/>
	);
});
Video.displayName = "Video";
function capitalizeFirstLetter(value) {
	return value.charAt(0).toUpperCase() + value.slice(1);
}
function titleCase(value) {
	const groups = value.match(/[A-Z]{2,}|[A-Z][a-z]+|[a-z]+|[A-Z]|\d+/gu) || [];
	return groups.map(capitalizeFirstLetter).join(" ");
}
var objectFitOptions = ["cover", "fill", "contain", "scale-down", "none"];
addPropertyControls(Video, {
	srcType: {
		type: ControlType.Enum,
		displaySegmentedControl: true,
		title: "Source",
		options: ["URL", "Upload"],
	},
	srcUrl: {
		type: ControlType.String,
		title: "URL",
		defaultValue:
			"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4",
		hidden(props) {
			return props.srcType === "Upload";
		},
	},
	srcFile: {
		type: ControlType.File,
		title: "File",
		allowedFileTypes: ["mp4", "webm"],
		hidden(props) {
			return props.srcType === "URL";
		},
	},
	playing: {
		type: ControlType.Boolean,
		title: "Playing",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	...borderRadiusControl,
	posterEnabled: {
		type: ControlType.Boolean,
		title: "Poster",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	poster: {
		type: ControlType.Image,
		title: "Image",
		hidden: ({ posterEnabled }) => !posterEnabled,
		description:
			"We recommend adding a poster. [Learn more](https://www.framer.com/help/articles/how-are-videos-optimized-in-framer/).",
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "rgba(0,0,0,0)",
	},
	startTime: {
		title: "Start Time",
		type: ControlType.Number,
		min: 0,
		max: 100,
		step: 0.1,
		unit: "%",
	},
	loop: {
		type: ControlType.Boolean,
		title: "Loop",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	objectFit: {
		type: ControlType.Enum,
		title: "Fit",
		options: objectFitOptions,
		optionTitles: objectFitOptions.map(titleCase),
	},
	// restartOnEnter: {
	//     type: ControlType.Boolean,
	//     title: "On ReEnter",
	//     enabledTitle: "Restart",
	//     disabledTitle: "Resume",
	// },
	controls: {
		type: ControlType.Boolean,
		title: "Controls",
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: false,
	},
	muted: {
		type: ControlType.Boolean,
		title: "Muted",
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	volume: {
		type: ControlType.Number,
		max: 100,
		min: 0,
		unit: "%",
		hidden: ({ muted }) => muted,
		defaultValue: 25,
	},
	onEnd: {
		type: ControlType.EventHandler,
	},
	onSeeked: {
		type: ControlType.EventHandler,
	},
	onPause: {
		type: ControlType.EventHandler,
	},
	onPlay: {
		type: ControlType.EventHandler,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/b5zs63ozvAt3JHMD5ROJ/R1RqOSTkgUszWr6ifGXv/yl67s275s.js
var PhosphorFonts = getFonts(Icon);
var FeatherFonts = getFonts(Icon2);
var VideoFonts = getFonts(Video);
var YouTubeFonts = getFonts(Youtube);
var Image1WithFX = withFX(Image1);
var cycleOrder = ["mMu0CBYNY", "cAxUjPzJz", "bexjzXY4B", "B4MS7ynyg"];
var serializationHash = "framer-rBRAB";
var variantClassNames = {
	B4MS7ynyg: "framer-v-jmul7g",
	bexjzXY4B: "framer-v-bfuzhk",
	cAxUjPzJz: "framer-v-i653km",
	mMu0CBYNY: "framer-v-hs19la",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var transition2 = {
	delay: 0,
	duration: 5,
	ease: [0.54, 0, 0.29, 0.99],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Dark Desktop Playing": "bexjzXY4B",
	"Dark Mobile Playing": "B4MS7ynyg",
	"Dark Mobile Version": "cAxUjPzJz",
	Dark: "mMu0CBYNY",
};
var Variants = motion.create(React.Fragment);
var getProps2 = ({
	cursor1,
	cursor2,
	height,
	id,
	videoFileVisible,
	width,
	youtubeVideoURL,
	youtubeVisible,
	...props
}) => {
	return {
		...props,
		cOv1RTy21: videoFileVisible ?? props.cOv1RTy21 ?? true,
		d3z5agfpn: youtubeVisible ?? props.d3z5agfpn,
		p5VkeDSdK: cursor1 ?? props.p5VkeDSdK,
		t50nNyw9a: cursor2 ?? props.t50nNyw9a,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "mMu0CBYNY",
		XPoFLgbNt:
			youtubeVideoURL ??
			props.XPoFLgbNt ??
			"https://www.youtube.com/watch?v=HjOQOMfg2cM",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		XPoFLgbNt: XPoFLgbNt2,
		d3z5agfpn: d3z5agfpn2,
		cOv1RTy21: cOv1RTy212,
		p5VkeDSdK: p5VkeDSdK2,
		t50nNyw9a: t50nNyw9a2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "mMu0CBYNY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1t07r6c = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("bexjzXY4B");
	});
	const onTap1uvmgpf = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("B4MS7ynyg");
	});
	const onTapo41ng = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("mMu0CBYNY");
	});
	const onTap8tt7cz = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("cAxUjPzJz");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "cAxUjPzJz") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["cAxUjPzJz", "B4MS7ynyg"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-hs19la",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-cursor={p5VkeDSdK2}
						data-framer-name={"Dark"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"mMu0CBYNY"}
						onTap={onTap1t07r6c}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-56b68b0d-e1a0-4c7c-8f2e-235960b623f1, rgb(217, 217, 217))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "dashed",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
						variants={{
							B4MS7ynyg: {
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							},
							cAxUjPzJz: {
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							},
						}}
						{...addPropertyOverrides(
							{
								B4MS7ynyg: {
									"data-framer-cursor": void 0,
									"data-framer-name": "Dark Mobile Playing",
									onTap: onTap8tt7cz,
								},
								bexjzXY4B: {
									"data-framer-cursor": t50nNyw9a2,
									"data-framer-name": "Dark Desktop Playing",
									onTap: onTapo41ng,
								},
								cAxUjPzJz: {
									"data-framer-cursor": void 0,
									"data-framer-name": "Dark Mobile Version",
									onTap: onTap1uvmgpf,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								className={"framer-1e8zgky"}
								data-framer-name={"Cursor"}
								layoutDependency={layoutDependency}
								layoutId={"Io4D2ZMZP"}
								style={{
									backdropFilter: "blur(35px)",
									borderBottomLeftRadius: 110,
									borderBottomRightRadius: 110,
									borderTopLeftRadius: 110,
									borderTopRightRadius: 110,
									boxShadow: "inset 0px 1px 2px 0px rgba(255, 255, 255, 0.25)",
									WebkitBackdropFilter: "blur(35px)",
								}}
								transformTemplate={transformTemplate1}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-adgqwl-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"Io4D2ZMZPOJOM3Rrby-container"}
										nodeId={"Io4D2ZMZPOJOM3Rrby"}
										rendersWithMotion={true}
										scopeId={"yl67s275s"}
									>
										<Icon
											color={
												"var(--token-7fe55cf6-3aeb-4bf8-bddc-29b461b9b1df, rgb(252, 252, 252))"
											}
											height={"100%"}
											iconSearch={"play"}
											iconSelection={"House"}
											id={"Io4D2ZMZPOJOM3Rrby"}
											layoutId={"Io4D2ZMZPOJOM3Rrby"}
											mirrored={false}
											selectByList={false}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"fill"}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						)}
						<motion.div
							className={"framer-42rcwk"}
							data-framer-name={"Youtube UI"}
							layoutDependency={layoutDependency}
							layoutId={"hM17Dk_PV"}
							style={{
								backgroundColor:
									"var(--token-630affeb-398d-46d0-8dce-69e819b8d7bc, rgb(23, 23, 23))",
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
							}}
							variants={{
								B4MS7ynyg: {
									borderTopLeftRadius: 15,
									borderTopRightRadius: 15,
								},
								cAxUjPzJz: {
									borderTopLeftRadius: 15,
									borderTopRightRadius: 15,
								},
							}}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-slq3me-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"fH_VSyCTI-container"}
									nodeId={"fH_VSyCTI"}
									rendersWithMotion={true}
									scopeId={"yl67s275s"}
								>
									<Icon2
										color={
											"var(--token-6a66765f-c594-4e59-a0c5-f0e90219549f, rgb(255, 255, 255))"
										}
										height={"100%"}
										iconSearch={"menu"}
										iconSelection={"home"}
										id={"fH_VSyCTI"}
										layoutId={"fH_VSyCTI"}
										mirrored={false}
										selectByList={false}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<Image1
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 89,
									intrinsicWidth: 403,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											10 +
											(((componentViewport?.height || 753) - 20 - 184) / 2 +
												0 +
												0) +
											22.5,
									),
									pixelHeight: 178,
									pixelWidth: 806,
									sizes: "122px",
									src: "https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?width=806&height=178",
									srcSet:
										"https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?scale-down-to=512&width=806&height=178 512w,https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?width=806&height=178 806w",
								}}
								className={"framer-1uxxaap"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"bT2DSuA6A"}
								{...addPropertyOverrides(
									{
										B4MS7ynyg: {
											background: {
												alt: "",
												fit: "fill",
												intrinsicHeight: 89,
												intrinsicWidth: 403,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														5 +
														(((componentViewport?.height || 250) - 10 - 139) /
															2 +
															0 +
															0) +
														7.08,
												),
												pixelHeight: 178,
												pixelWidth: 806,
												sizes: "58px",
												src: "https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?width=806&height=178",
												srcSet:
													"https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?scale-down-to=512&width=806&height=178 512w,https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?width=806&height=178 806w",
											},
										},
										cAxUjPzJz: {
											background: {
												alt: "",
												fit: "fill",
												intrinsicHeight: 89,
												intrinsicWidth: 403,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														5 +
														(((componentViewport?.height || 250) - 10 - 139) /
															2 +
															0 +
															0) +
														7.08,
												),
												pixelHeight: 178,
												pixelWidth: 806,
												sizes: "58px",
												src: "https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?width=806&height=178",
												srcSet:
													"https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?scale-down-to=512&width=806&height=178 512w,https://framerusercontent.com/images/uhdGL46UIzXfs2VpdKcsuI2rlnI.png?width=806&height=178 806w",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
						<motion.div
							className={"framer-1d52c2a"}
							data-framer-name={"Youtube Video"}
							layoutDependency={layoutDependency}
							layoutId={"zNSI8l6b7"}
							style={{
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
							}}
							variants={{
								B4MS7ynyg: {
									borderBottomLeftRadius: 15,
									borderBottomRightRadius: 15,
								},
								cAxUjPzJz: {
									borderBottomLeftRadius: 15,
									borderBottomRightRadius: 15,
								},
							}}
						>
							{cOv1RTy212 !== false && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-10pyo18-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"F2tbYtSl6-container"}
										nodeId={"F2tbYtSl6"}
										rendersWithMotion={true}
										scopeId={"yl67s275s"}
									>
										<Video
											backgroundColor={"rgba(0, 0, 0, 0)"}
											borderRadius={0}
											bottomLeftRadius={0}
											bottomRightRadius={0}
											controls={false}
											height={"100%"}
											id={"F2tbYtSl6"}
											isMixedBorderRadius={false}
											layoutId={"F2tbYtSl6"}
											loop={true}
											muted={true}
											objectFit={"cover"}
											playing={false}
											poster={
												"https://framerusercontent.com/images/XpkGQdEUEAl4EMzo7AIt3w7UnRE.jpg?width=1280&height=720"
											}
											posterEnabled={true}
											srcFile={
												"https://framerusercontent.com/assets/C73ahPiiIMjwpWyVqtQdbXZHJFI.mp4"
											}
											srcType={"Upload"}
											srcUrl={""}
											startTime={0}
											style={{
												height: "100%",
												width: "100%",
											}}
											topLeftRadius={0}
											topRightRadius={0}
											volume={25}
											width={"100%"}
											{...addPropertyOverrides(
												{
													B4MS7ynyg: {
														muted: false,
														playing: true,
													},
													bexjzXY4B: {
														muted: false,
														playing: true,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{d3z5agfpn2 !== false && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-v0yuaj-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"SO6GaHNfn-container"}
										nodeId={"SO6GaHNfn"}
										rendersWithMotion={true}
										scopeId={"yl67s275s"}
									>
										<Youtube
											borderRadius={0}
											bottomLeftRadius={0}
											bottomRightRadius={0}
											height={"100%"}
											id={"SO6GaHNfn"}
											isMixedBorderRadius={false}
											isRed={false}
											layoutId={"SO6GaHNfn"}
											play={"Off"}
											shouldMute={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											thumbnail={"Medium Quality"}
											topLeftRadius={0}
											topRightRadius={0}
											url={XPoFLgbNt2}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.div>
						{isDisplayed1() && (
							<Image1WithFX
								__framer__loop={animation}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"mirror"}
								__framer__loopTransition={transition2}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 358,
									intrinsicWidth: 328.5,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 753) * 0.8577235772357725 -
												67.5),
									),
									pixelHeight: 716,
									pixelWidth: 657,
									sizes: "124px",
									src: "https://framerusercontent.com/images/0paVKLcpbJBiIQ7P5Hi70dR8P4.png?width=657&height=716",
								}}
								className={"framer-13dqjz"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"K6YPdJlrc"}
								style={{
									rotate: 29,
								}}
							/>
						)}
						{isDisplayed1() && (
							<Image1WithFX
								__framer__loop={animation}
								__framer__loopEffectEnabled={true}
								__framer__loopPauseOffscreen={true}
								__framer__loopRepeatDelay={0}
								__framer__loopRepeatType={"mirror"}
								__framer__loopTransition={transition2}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 358,
									intrinsicWidth: 328.5,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											((componentViewport?.height || 753) *
												0.08943089430894331 -
												67),
									),
									pixelHeight: 716,
									pixelWidth: 657,
									sizes: "123px",
									src: "https://framerusercontent.com/images/0paVKLcpbJBiIQ7P5Hi70dR8P4.png?width=657&height=716",
								}}
								className={"framer-8kvpoh"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"EProWifbM"}
								style={{
									filter: "blur(5px)",
									rotate: -41,
									WebkitFilter: "blur(5px)",
								}}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-rBRAB.framer-lnmqkf, .framer-rBRAB .framer-lnmqkf { display: block; }",
	".framer-rBRAB.framer-hs19la { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 10px; position: relative; width: 1200px; }",
	".framer-rBRAB .framer-1e8zgky { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 116px); justify-content: center; left: 50%; overflow: hidden; padding: 0px; position: absolute; top: 51%; width: 116px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-rBRAB .framer-adgqwl-container, .framer-rBRAB .framer-slq3me-container { flex: none; height: 32px; position: relative; width: 32px; }",
	".framer-rBRAB .framer-42rcwk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 20px 0px 20px 30px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-rBRAB .framer-1uxxaap { aspect-ratio: 4.52808988764045 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 26px); overflow: visible; position: relative; width: 122px; }",
	".framer-rBRAB .framer-1d52c2a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-rBRAB .framer-10pyo18-container { aspect-ratio: 1.7857142857142858 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 661px); position: relative; width: 1px; }",
	".framer-rBRAB .framer-v0yuaj-container { aspect-ratio: 1.826625386996904 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 109px); position: relative; width: 1px; }",
	".framer-rBRAB .framer-13dqjz { flex: none; height: 135px; left: calc(15.41666666666669% - 124px / 2); overflow: visible; position: absolute; top: calc(85.77235772357726% - 135px / 2); width: 124px; z-index: 1; }",
	".framer-rBRAB .framer-8kvpoh { flex: none; height: 134px; left: calc(59.66666666666669% - 123px / 2); overflow: visible; position: absolute; top: calc(8.94308943089433% - 134px / 2); width: 123px; z-index: 1; }",
	".framer-rBRAB.framer-v-i653km.framer-hs19la, .framer-rBRAB.framer-v-jmul7g.framer-hs19la { padding: 5px; width: 390px; }",
	".framer-rBRAB.framer-v-i653km .framer-1e8zgky { height: var(--framer-aspect-ratio-supported, 46px); width: 46px; }",
	".framer-rBRAB.framer-v-i653km .framer-adgqwl-container { height: 20px; width: 20px; }",
	".framer-rBRAB.framer-v-i653km .framer-42rcwk, .framer-rBRAB.framer-v-jmul7g .framer-42rcwk { padding: 5px 0px 5px 30px; }",
	".framer-rBRAB.framer-v-i653km .framer-slq3me-container, .framer-rBRAB.framer-v-jmul7g .framer-slq3me-container { height: 17px; width: 17px; }",
	".framer-rBRAB.framer-v-i653km .framer-1uxxaap, .framer-rBRAB.framer-v-jmul7g .framer-1uxxaap { height: var(--framer-aspect-ratio-supported, 13px); width: 58px; }",
	".framer-rBRAB.framer-v-i653km .framer-10pyo18-container, .framer-rBRAB.framer-v-jmul7g .framer-10pyo18-container { height: var(--framer-aspect-ratio-supported, 213px); }",
	'.framer-rBRAB[data-border="true"]::after, .framer-rBRAB [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Frameryl67s275s = withCSS(Component, css, "framer-rBRAB");
var stdin_default = Frameryl67s275s;
Frameryl67s275s.displayName = "Youtube Video";
Frameryl67s275s.defaultProps = {
	height: 753,
	width: 1200,
};
addPropertyControls2(Frameryl67s275s, {
	variant: {
		options: ["mMu0CBYNY", "cAxUjPzJz", "bexjzXY4B", "B4MS7ynyg"],
		optionTitles: [
			"Dark",
			"Dark Mobile Version",
			"Dark Desktop Playing",
			"Dark Mobile Playing",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	XPoFLgbNt: {
		defaultValue: "https://www.youtube.com/watch?v=HjOQOMfg2cM",
		title: "Youtube Video URL",
		type: ControlType2.String,
	},
	onXPoFLgbNtChange: {
		changes: "XPoFLgbNt",
		type: ControlType2.ChangeHandler,
	},
	d3z5agfpn: {
		defaultValue: false,
		title: "Youtube Visible",
		type: ControlType2.Boolean,
	},
	ond3z5agfpnChange: {
		changes: "d3z5agfpn",
		type: ControlType2.ChangeHandler,
	},
	cOv1RTy21: {
		defaultValue: true,
		title: "Video File Visible",
		type: ControlType2.Boolean,
	},
	oncOv1RTy21Change: {
		changes: "cOv1RTy21",
		type: ControlType2.ChangeHandler,
	},
	p5VkeDSdK: {
		title: "Cursor 1",
		type: ControlType2.CustomCursor,
	},
	t50nNyw9a: {
		title: "Cursor 2",
		type: ControlType2.CustomCursor,
	},
});
addFonts(
	Frameryl67s275s,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...PhosphorFonts,
		...FeatherFonts,
		...VideoFonts,
		...YouTubeFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:youtube-video
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "cAxUjPzJz",
	xl: "mMu0CBYNY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders YoutubeVideoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8432de3c3dd39f1f01a1e5cb3f0f00d114acfd0a6639cd6a2c09a196e074189f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var youtube_video_default = ComponentWithRoot;
export { youtube_video_default as default };
